apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  storageClass: local-path-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
