- name: Install required system packages
  ansible.builtin.apt:
    name:
      - curl
    state: present
    update_cache: true

- name: Create system group
  ansible.builtin.group:
    name: "sonarr"
    system: true
    state: present

- name: Create system user
  ansible.builtin.user:
    name: "sonarr"
    group: "sonarr"
    system: true
    shell: /bin/bash
    home: "/var/lib/sonarr"
    create_home: true
    password_lock: true

- name: Create required directory structure
  ansible.builtin.file:
    path: "/opt/sonarr"
    state: directory
    owner: "sonarr"
    group: "sonarr"
    mode: '0755'

- name: Extract archive
  ansible.builtin.unarchive:
    src: "https://services.sonarr.tv/v1/download/main/latest?version={{ version }}&os=linux&arch=x64"
    dest: /opt/Sonarr/
    creates: /opt/Sonarr/Sonarr
    remote_src: yes
  notify: Restart Sonarr

- name: Set owner
  ansible.builtin.file:
    path: /opt/sonarr/
    state: directory
    owner: sonarr
    group: sonarr
    recurse: yes

- name: Deploy systemd service
  ansible.builtin.template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: sonarr
    state: started
    enabled: true
    daemon_reload: true
