apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-seed
  namespace: media
  labels:
    app: cross-seed
spec:
  selector:
    matchLabels:
      app: cross-seed
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cross-seed
    spec:
      volumes:
        - name: nas-qbittorrent
          hostPath:
            path: /mnt/nas/qBittorrent
        - name: nas-movies
          hostPath:
            path: /mnt/nas/Movies
        - name: nas-shows
          hostPath:
            path: /mnt/nas/Shows
        - name: nas-nsfw
          hostPath:
            path: /mnt/nas/NSFW
        - name: cross-seed-data
          persistentVolumeClaim:
            claimName: cross-seed-data
        - name: cross-seed-config
          secret:
            secretName: cross-seed-config
      containers:
        - name: cross-seed
          image: ghcr.io/cross-seed/cross-seed:6
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/cross-seed", "daemon"]
          ports:
            - name: webui
              containerPort: 2468
          volumeMounts:
            - name: cross-seed-data
              mountPath: /config
            - name: cross-seed-config
              mountPath: /config/config.js
              subPath: config.js
            - name: nas-qbittorrent
              mountPath: /mnt/nas/qBittorrent
            - name: nas-movies
              mountPath: /mnt/nas/Movies
            - name: nas-shows
              mountPath: /mnt/nas/Shows
            - name: nas-nsfw
              mountPath: /mnt/nas/NSFW
