apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-nic-optimizer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node-nic-optimizer
  template:
    metadata:
      labels:
        app: node-nic-optimizer
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: ethtool
          image: alpine
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add ethtool;
              # This logic finds the physical interface used for the default gateway
              INTERFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
              echo "Found physical interface: $INTERFACE"

              # Disable hardware offloading that breaks VXLAN/IPv6 checksums on bare metal
              echo "Applying ethtool optimization..."
              ethtool -K "$INTERFACE" tx-checksum-ip-generic off rx off

              echo "Optimization applied to $INTERFACE. Sleeping forever."
              sleep infinity
