apiVersion: v1
kind: Secret
metadata:
    name: headscale-reconciler
    namespace: headscale
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:YfGB8sr6uABRYbgabhDrepXT0lQzENkcAIpxfZzIIy22iqFbfB3Tet376VKOiOrMwCvHls308tnX4WZ9lcV4caBv70PdBtmJxDJWXCs2/WYX5+cnd5lR,iv:jiiLK3c8cc303H4wN0xG8Kc8zAoq/zvYz6LFuHby3vE=,tag:NXPtS7MQWj5Q8zxMpEWJpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCenh2Zi9hai9zbFROY2ZM
            OThlcVNQcE8rd2gweGhmNTk0ZDJ0djQzcGxnClF5MDcrREMwcDFaRVVBU0ZjN0RU
            SFNvY2ZpVTFyR1VrZjUvbFdlTGp3RXMKLS0tIGN5Q2txSnR1b2FISzE1bTF6OU9R
            bm8vcSszam1FL1dBdHIyOVBnTSt2Nm8KDI4iJjz3tYHm9AIdYSxLBfLB/c8b5q4u
            4YBWJF9J1aDF5hoDK1ejpvSwd9KBIRnpJUOZZ+9EidD0tHyyN5aykw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeEFBSUNEYmZBSWlQYXFP
            anhsN0UreUY1TUdmN1o1UDVnek9aM215SlhJCmhnMHhEK0hMemlKV3I4Y1RwcmhX
            bzg4Q0RYaGRNeFdRVlYyNWNzbmc1NE0KLS0tIGhJWEo3U01FMXovOVZac1RNV3pF
            ajlFeHo2bHBUVTh0SG90S3pBOENnTEkKfvO7spAr3NNfGTwMlx0uYpnG/5rRk9JF
            vXuNXEfBxthtMouZB+d/lC541dK5pOLJlfH2+RsJI0QZrdhcw5c0Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWklOWDNtMUVJZmdiU2lO
            M21hT0RGbHAyM3Vlc25DUWpkcmU4ZkVrVWtBClBNTjhEcklTQlJ1R0luNXFkTHB4
            a0xwcTZMdllmTCtDcUhBU1U1M08xUUkKLS0tIFZDMHp6VkdqdGQwU3FPcENUOGp0
            OVBFbHltcEZtdGhWMUJ4bkJrQ0FOSlUKF413yRVbxq85PdphqyRRuqnU2Z0n5KRv
            eoEB3UwTDUSFe4HeLBKKWGwwFOZZIbZRf9pwl/O2fxoReOtxJJkQ0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T20:00:10Z"
    mac: ENC[AES256_GCM,data:1rd/PDLtR97mPU2kSKBjXpkccKJqL1yhwDj0c+GptNDr9qd6QoLdzBTu04FwFe/8bwIRLLgD2WRzWK+jQ/edK6xrF6sq4LNKT2Vjyh78r6l4e8LNVZinUMsBwSYil6grONbGovxFvqkUGgehtZWmS5MAZsTDYTUQS7kl3bQhHh0=,iv:whKs8tHT/R79wdCxsdRRuCQDR6yWjkQkOsEsEcCeV6w=,tag:SHbx7pg64Vw8CxTf7Pl+2w==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
