apiVersion: v1
kind: Secret
metadata:
    name: pvc-explorer-auth
    namespace: pvc-explorer-system
type: Opaque
#ENC[AES256_GCM,data:4cTajVrWI2aj9fz5XRyQgeNjwPtRmYAusP+QwMQxugUOD+rTYa7SYbC+gIrbxKQTnorI9xe+lagJGRZ/xG9O3TzHt5vrKcIM4LeddAYM3M9b,iv:3/2Bb51MYG6TIM29mm0lpcJDjTqeeZoexJOZDQm0+oE=,tag:TUN88tQ3KN2GM9p7r0Tc8A==,type:comment]
#ENC[AES256_GCM,data:vpfwbE5wbJVcvu9+DR7CK00EW+EwmKrHz6QRCjGYRlV0xaxjl91N5PIj1xM3xR41F3z5RyjpzQ==,iv:GtDYDZNTZ+Iv6dRRqxxSM7gD91/WcCVLQ3iBymxUjGI=,tag:Suy9yvGpS80fhofpTLlItw==,type:comment]
stringData:
    admin: ENC[AES256_GCM,data:tDuONeiWPcijOEARMvfvquDVnvXO0XJLEiLjA8OE4aY8LQDm+I90EDMgkapsacyXSCvVItSBm98/8Prz,iv:SINeZSZiU4jGlXx0VFsGyukeTP6pQStTiYT5h7nNod0=,tag:UbEhz/9ucimYeMVepZmMvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbTFqUDhHMXB0MG5rTWRT
            K1U5dlFnaVhZblhaS2NTdWVTNlo4NVc2b3d3CkJrRC9hTVhYeWlUMGZ1Z2FEZlh0
            YWRuZlpMU3ZITWwrZFFaVkFENXkvWHcKLS0tIFR6dG5TS09ienBkdktzNkhDY1NM
            eEZlZFhoSW9QY0xpNnNZR2ZZd0VaM00KpYzRYD3uyvX+lXWL1kqalIBH+26Ea1iS
            vXUJ3SiJJEaTfKWpDQgkkgxRPHA104I3RPw44WaDPEgC1RtZg2ie+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMTc1U2VJcGpBZXNmOEZ2
            NDBPcDFPd3VuS3ViSUNvNXkrZ0tNeWl1bGp3CmJEMFlYZFJFSDNCY1JGREE3VGhJ
            U3BESE42Y1lIWi85aUlyaFY1YkEyV0kKLS0tIGhoaEd4L1pOd2NNcUV2Z1p4ZVJT
            T09VaWxkc3BDN2RnVERvQXUwUXRoYTAKF50fv7hESK2qkUVZNgmylRJlIWBYs1LQ
            UdsWc86hpV/zweeUVQqEHJncrn07WyoHi/v+tO57fkXjFG24wCTsLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib3NRWnNLTjZaenU0b08z
            ZDdEdWFxUkF2K2R6ZllXd1Zhd2ZHNi8wWjA0Cll1Rm9SaTU4RE5xSmV2V1grbk85
            YXlTRXpyVEt3b1hHeFBlNG5teHQ3bFkKLS0tIC9LNFFuV0kwM05FaXNadXF0aEcy
            V3NuaitQMDlrZDlaQWk5Y1l0SHFSVUUKKCqFUH7z3yzetK1ig2V2K1CRNdqQ/y3Q
            wClqlLfXv5C1mCHFGPry4j1DxKJRJWmIHSkcX1MB4ikdAei1zX1UaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-24T23:49:16Z"
    mac: ENC[AES256_GCM,data:8z+6qoXvd7a9ztBp7ofYZy0xBP0nWsai4gguaOe/QhL7xLwzqCHncwmeWuXXLSCYEBy5TL+yyjjjWz22lr9gERF4KBfRSmD26XU4MK9tCJ4lHhdwUhlN8LnDbL3fim5N1ryl2RX1FQgtNdE7PnB0/Nn/ia1ewVKlt9F5Ny4tXUU=,iv:YdFFiSxu95sUMQ1T5Gt9IPyJIVLK9nndIrG0gEg+Yis=,tag:6sZFznlaU7yUYOgrm0d98w==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
