- name: Install extrepo
  ansible.builtin.apt:
    name:
      - extrepo
      - curl 
      - gnupg
    state: present
    update_cache: true

- name: Enable jellyfin extrepo
  ansible.builtin.shell:
    command: extrepo enable jellyfin

- name: Refresh apt cache
  ansible.builtin.apt:
    name:
      - jellyfin
    state: present
    update_cache: true

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: jellyfin
    state: started
    enabled: true
    daemon_reload: true
