---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 1.3.x
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      interval: 5m
  releaseName: vaultwarden
  targetNamespace: vaultwarden
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
            patch: |
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: any
                labels:
                  recurring-job-group.longhorn.io/trim: enabled
                  recurring-job-group.longhorn.io/snapshot: enabled
                  recurring-job-group.longhorn.io/backup: enabled
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
    ingress:
      enabled: true
      host: vaultwarden.sakul-flee.de
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - secretName: vaultwarden-sakul-flee-de-tls
          hosts: [vaultwarden.sakul-flee.de]
    vaultwarden:
      allowSignups: false
      requireEmail: true
      domain: https://vaultwarden.sakul-flee.de
      admin:
        enabled: false
      smtp:
        enabled: true
        existingSecret: vaultwarden-smtp
        host: smtp.purelymail.com
        port: '465'
        authMechanism: Login
        security: force_tls
        from: vaultwarden@sakul-flee.de
        fromName: VaultWarden
