apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teamcity
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: teamcity
      version: '2025.7.x'
      sourceRef:
        kind: HelmRepository
        name: teamcity
      interval: 5m
  releaseName: teamcity
  targetNamespace: teamcity
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    server:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik
        tls:
          - hosts:
              - teamcity.sakul-flee.de
            secretName: teamcity-tls
        rules:
          - host: teamcity.sakul-flee.de
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: teamcity-server
                      port:
                        number: 8111
    agent:
      replicaCount: 3
      volumeClaimTemplates:
      - metadata:
          name: teamcity-agent
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi
          storageClassName: longhorn-volatile
