apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: teamcity
  namespace: teamcity
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"] 
- apiGroups: [""]
  resources: ["pods", "pods/exec", "podtemplates"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
