when:
  event: [push, tag, manual]
  branch: main
steps:
  deploy:
    image: alpine/ansible
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      ANSIBLE_VAULT_PASSWORD:
        from_secret: ANSIBLE_VAULT_PASSWORD
    commands:
      - ansible-galaxy role install geerlingguy.postgresql
      - printf "%s" "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
      - printf "%s" "$SSH_KEY" > .private_key
      - chmod 600 .vault_pass
      - chmod 600 .private_key
      - ansible-playbook -i inventory.ini playbook.yml --private-key .private_key --vault-password-file .vault_pass
