[pve]
caddy ansible_host=10.0.0.101

[pve:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key root@192.168.178.200 -W %h:%p"'
