[pve]
caddy       ansible_host=10.0.0.101
website     ansible_host=10.0.0.102
forgejo     ansible_host=10.0.0.103
woodpecker  ansible_host=10.0.0.104
hytale      ansible_host=10.0.0.105
minecraft   ansible_host=10.0.0.106
jellyfin    ansible_host=10.0.0.107
prowlarr    ansible_host=10.0.0.108
sonarr      ansible_host=10.0.0.109
radarr      ansible_host=10.0.0.110
qbittorrent ansible_host=10.0.0.111
syncthing   ansible_host=10.0.0.112
renovate    ansible_host=10.0.0.113
crossseed   ansible_host=10.0.0.114

[pve:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 -i {{ playbook_dir }}/.private_key root@192.168.178.200 -W %h:%p"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
