# - name: APT Update
#   hosts: all
#   roles:
#     - role: apt

- name: Caddy
  hosts: caddy
  roles:
    - role: caddy

- name: Website
  hosts: website
  roles:
    - role: website

- name: Forgejo
  hosts: forgejo
  roles:
    - role: forgejo

- name: Woodpecker
  hosts: woodpecker
  roles:
    - role: woodpecker

- name: Minecraft
  hosts: minecraft
  roles:
    - role: minecraft

- name: Jellyfin
  hosts: jellyfin
  roles:
    - role: jellyfin

- name: Prowlarr
  hosts: prowlarr
  roles:
    - role: prowlarr

- name: Sonarr
  hosts: sonarr
  roles:
    - role: sonarr

- name: Radarr
  hosts: radarr
  roles:
    - role: radarr

- name: qBittorrent
  hosts: qbittorrent
  roles:
    - role: qbittorrent

- name: Renovate
  hosts: renovate
  roles:
    - role: renovate
