- name: APT Update
  hosts: all
  roles:
    - role: apt

- name: Caddy
  hosts: caddy
  roles:
    - role: caddy

- name: Website
  hosts: website
  roles:
    - role: website

- name: Forgejo
  hosts: forgejo
  roles:
    - role: forgejo

- name: Woodpecker
  hosts: woodpecker
  roles:
    - role: woodpecker
