- name: APT Update
  hosts: all
  roles:
    - role: apt

- name: Caddy
  hosts: caddy
  roles:
    - role: caddy

- name: Website
  hosts: website
  roles:
    - role: website

- name: Forgejo
  hosts: forgejo
  vars_files:
    - roles/forgejo/vars/vault.yml
  roles:
    - role: forgejo
