apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: dev@sakul-flee.de
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-cluster-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
