---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jellyfin
      version: 0.8.x
      sourceRef:
        kind: HelmRepository
        name: alekc
      interval: 5m
  releaseName: jellyfin
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  values:
    persistence:
      enabled: true
      config:
        storageClass: longhorn-replicated
        size: 8Gi
      cache:
        storageClass: longhorn-volatile
        size: 4Gi
      # Media mount
      additionalVolumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: cache-images
          emptyDir:
        - name: cache-transcodes
          emptyDir:
      additionalMounts:
        - name: media
          mountPath: /mnt/media
        - name: cache-images
          mountPath: /cache/images
        - name: cache-transcodes
          mountPath: /cache/transcodes
    service:
      type: ClusterIP
      port: 8096
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: jellyfin.sakul-flee.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: jellyfin-sakul-flee-de-tls
          hosts: [jellyfin.sakul-flee.de]
