apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  releaseName: qbittorrent
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    qbittorrent:
      config:
        persistence:
          enabled: true
          storageClass: longhorn-replicated
  
      # Media mount
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media     

      volumeMounts:
      - name: media
        mountPath: /mnt/media

      service:
        port: 80 # Required for tests?
        web:
          type: ClusterIP
          port: 80
        torrent:
          type: ClusterIP
          port: 8388

      ingress:
        enabled: true
        className: traefik        
        annotations: 
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: qbittorrent.sakul-flee.de
          paths:
          - path: /
            pathType: ImplementationSpecific
        tls:
        - secretName: qbittorrent-sakul-flee-de-tls
          hosts:
          - qbittorrent.sakul-flee.de

      gluetun:
        enabled: true
        extraEnvFrom:
        - secretRef:
            name: secret-env-qbittorrent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          sysctls:
          - name: net.ipv6.conf.all.disable_ipv6
            value: "1"
