apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: qbittorrent
      version: '1.2.x'
      sourceRef:
        kind: HelmRepository
        name: alekc
      interval: 5m
  releaseName: qbittorrent
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated

      # Media mount
      additionalVolumes:
      - name: media
        persistentVolumeClaim:
          claimName: media     
      - name: wg0            
        secret:
          secretName: secret-vpn-pia
          items:
          - key: wg0
            path: wg0
      additionalMounts:
      - name: media
        mountPath: /mnt/media
      - name: wg0
        mountPath: /config/wireguard/wg0.conf

    service:
      type: "ClusterIP"
      port: 8989

    ingress:
      enabled: true
      className: traefik        
      annotations: 
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: qbittorrent.sakul-flee.de
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: qbittorrent-sakul-flee-de-tls
        hosts:
        - qbittorrent.sakul-flee.de

    vpn:
      enabled: true

