apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/m0nsterrr/helm-charts/flaresolverr
