apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: radarr
      version: '2.0.x'
      sourceRef:
        kind: HelmRepository
        name: alekc
      interval: 5m
  releaseName: radarr
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated

      # Media mount
      additionalVolumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      additionalMounts:
      - name: media
        mountPath: /mnt/media

    ingress:
      enabled: true
      className: traefik        
      annotations: 
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: radarr.sakul-flee.de
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: radarr-sakul-flee-de-tls
        hosts:
        - radarr.sakul-flee.de
