apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: prowlarr
      version: '2.2.x'
      sourceRef:
        kind: HelmRepository
        name: alekc
      interval: 5m
  releaseName: prowlarr
  targetNamespace: media
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
            patch: |
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: any
                labels:
                  recurring-job-group.longhorn.io/trim: enabled
                  recurring-job-group.longhorn.io/snapshot: enabled
                  recurring-job-group.longhorn.io/backup: enabled
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
    service:
      type: "ClusterIP"
      port: 9696
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: prowlarr.sakul-flee.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: prowlarr-sakul-flee-de-tls
          hosts:
            - prowlarr.sakul-flee.de
