apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  storageClassName: longhorn-volatile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi

