apiVersion: v1
kind: Secret
metadata:
    name: unsloth-secrets
    namespace: unsloth
type: Opaque
stringData:
    UNSLOTH_STUDIO_PASSWORD: ENC[AES256_GCM,data:TnYjMzR9Z6EVMIA83nuUm+O8wwUN9QU4,iv:jMSDWwCGZIOWaVfU0NiOSO/uU8PUWQsijz0iUs3yylM=,tag:ijAzMHt8+DFbI/pUIk5bIg==,type:str]
    JUPYTER_PASSWORD: ENC[AES256_GCM,data:BxWnjlMbzbUAOJvT4nasJ90evWljaia/,iv:dxcs0zFIg1LOtpZcJyzR/n2VJzfkC+xls0kRuJ5OzHQ=,tag:/OolE6Giod70qbbE4ph75A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUlpEKzlDQ2VFclVQS3VH
            TzhmK1REOG9tYkh4OGtwZ3hhOTJ6ZlN2eVU4CmtEUzRuak9SZFdYL3ZrQVN3QkVs
            SnFUcjkxclZFaFJBcTlHdEhVTjFya28KLS0tIEd5TnA2MlRqZEVlbVNBR0RLQTZL
            cVYwWTVUNGw1VGhCZ0o2b2cyc3ZTSEkKRsRYDRx1e5PJL5rfa5pRr4vY81M8VUB3
            Mq+pQBY4qeOmz97TWrVIB+ONlnfdBq5QvDpAQ9nzLVoaNlzRIMMV/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMFczYnNta1lBaWdTRGFW
            dWs0UktKVnRRbnBRRVdMTjM4cXpIVjFwS0NJCmJhczJTSGJIc1BYWUZwZzBHNEJn
            ek5uQlNMaDE0UXJ3T1Q2aHYrL3l1UmcKLS0tIGQ3ODJ1SEtCaFFWNHU1QUFtY21w
            YW9ISmt2R2ZmVUlnMGNqbDR0bVcvK0EKc4zHRBv+AkeV0f4mAmMIZA/WwLNqhq1C
            PEDdiMmd7h5vMPb3wAmCjXu8BQOnXh9Emx2PEoxpN+931P4eTglvEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTERWTndTSVRnWHVleUx6
            MERQOEVWclJlZVZkdys0N2pNT0RLMzNaemhZCi9PbmJydkJHbzArZEhhTGNvOWRV
            bytzUjFZTUdIR2hyTTh2YWd5aWVKZEUKLS0tIERSYzBTaVlIcGgvdkt5L0hBclpP
            U1ZBTktXVFUzK3BrQWlwUit2R0REUFUKHh5gDjVjPj9JIaZAmxWouKdgUulZSAdf
            3pG6E/NpJwxROBW7+8fcUI5oebiZwinWdLqqlRlEZXuRUd1eBPrWtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-24T20:53:50Z"
    mac: ENC[AES256_GCM,data:SgbIzTmJa3K5IhfBrIaG4erTqgX5P7aItbqtzIyCMvM8VcR7uR9Gpt4sSiwMcWKDpnQW3M+N/TBWsmOICL+dxj4GycP8ATj+NVMlqzvymGNb4egm31dvpDxR2z33PS36OIi6po4/+XAa8wjdRwyEifYR2E7tsy8R7ykJJNJg2VE=,iv:ocoE8YWXLt1MjABSx9kWiJ32Jnio8l7XA7UVayW8cbY=,tag:uJ7UxTpJMe4wS+z28R6oPw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
