apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headplane
  namespace: headplane
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: headscale-vpn-only@kubernetescrd, headplane-headplane-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: headplane.sakul-flee.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headplane
                port:
                  number: 3000
  tls:
    - hosts:
        - headplane.sakul-flee.de
      secretName: headplane-sakul-flee-de-tls