apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subnet-router-state
  namespace: headscale
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi