- name: Install
  ansible.builtin.apt:
    package: caddy
    state: present

- name: Upload static configuration file
  ansible.builtin.copy:
    src: files/Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  notify: Restart Caddy

- name: Service
  systemd:
    name: caddy
    state: started
    enabled: yes
