# System account configurations
hytale_user: "hytale"
hytale_group: "hytale"

# Installation ecosystem paths
hytale_install_dir: "/opt/hytale"

# JVM Resource Allocations
hytale_xms: "2G"
hytale_xmx: "4G"
hytale_jar_name: "hytale_server.jar"

# Download routing (Placeholder for official Hypixel package release)
hytale_download_url: "https://launcher.hytale.com/download/server/{{ hytale_jar_name }}"
