apiVersion: ENC[AES256_GCM,data:3mE=,iv:t93bBUfkgh6zaGZmJAGq4vrmLdlrS+XRM7yIKid5xXg=,tag:P32CwqpxjjbEyvlkazdNSg==,type:str]
kind: ENC[AES256_GCM,data:1m5uPQSI,iv:A5WfsNZqppu/Tro0p1zUrO/jwCpoHaOs3p63gT5OFsU=,tag:+ca6fHfS240Dq/VSlYTnXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YnoMnAcCmL+tSYXqIfMv6Vvz8LmaZg==,iv:qhXUdCUJ8GnaRGAUnHDM8r6gFByEdO4f7TpjEL0H920=,tag:NeY1cGrZfVFWpY80C17B6A==,type:str]
    namespace: ENC[AES256_GCM,data:Zcuj2o9srX591/KGgYMz,iv:R8guDFUJ8/Qi75gwuhxSucLsbkZUjg69GGKLdc67dCk=,tag:Qgywjvk++Td9//ERT+OJHw==,type:str]
type: ENC[AES256_GCM,data:VxroIR2Q,iv:xVCL2wGVVEuBUIehzWA0BTJyg0qhVomuVT33m50zka0=,tag:z5BVueOfo3hqMRfKj0M3Ew==,type:str]
stringData:
    username: ENC[AES256_GCM,data:UlAiZqg=,iv:vQsUHY8dg16vrNEUHJ+t/8YHQchpOF9Q05lQc4Oj4Xo=,tag:5+1sNzL60U3fnsG0lYB6iw==,type:str]
    password: ENC[AES256_GCM,data:pANTZEosxaBwE+LObbiZSnw4ChNV6H418Nx7zG9UPv0=,iv:ATFs1/dNI9YlEcj71TxJVXys8T5MRezQzIW3yWe3TIQ=,tag:VSwd68tiY7yp5CixFXxTUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRTBSaWoyUjljMEhnazFU
            MGgweTM5eWNCUFcrVUVQNCtyNmJhS1VueVFNCi9zeWFEYms3cVB6SzNoNy9zaVFM
            QWpNRXJUcUlTWTBDcm10dURMWmhWZWMKLS0tIDUzeTNiTTdSUC9hdTJUaHNnMWY1
            M3JwcTBmY0hUN3B5bTU2UEkxUjl3NkUK+6XGWFHojNcEvTdTcPIr40haFglBikwh
            qAW1Ewj3H4qYwduDTQZiBa/fogftHcEPTzuE7EwYx7kWGs2KxtO2qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRUdjZVdsUHhReDZpK3A1
            T3FFOEt1am11eDdUa1RMaHY4b0dWcmhzK1dZClJCaStrcm9FVzNiWlFlVmZxYWov
            RnVpdjUrWndYN004b3JoZFVzdG90R2MKLS0tIExzendHaUpxVm9GYlhLcTNPMHdT
            OE1DOGljbHE4REN6WFBnUHI2MmJpdWMKB2CBkMiA/QaZloQGoFroZ5F65U0noOEw
            siQZVJHB7OYXcxoWwLflU2QvJfEa0iNLRAfNHyHSOoaM6Sua1ob6Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFek84QVhhT1RJUEpaVUNp
            dU1hUlQ3QzI4amxlUTFHRWJoNnZuUHhVeWt3CllHNk4ya3FjQ0tjSDZXdGhUcm1r
            RE1WUWNlMm1pL2JZMkRidXZ6MzJoYVUKLS0tIGZzYXV3a3NDaUF0ZXNkSUZUNE1i
            cVFYSlRNTHJ4U2tnbFI2UndOS2p5RzQKuXWxmSAaiDuDia2WtIy8Hto/glt6tfdP
            plNj1ut5r0ZXg+f2baSFpOsIa6vYcZHyQ97yQ114BvR2zJL80ect/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-23T14:38:50Z"
    mac: ENC[AES256_GCM,data:yqWB21/qnXj9/4gCzyYC7P4F2OiVfi4x5VAD4ka5xdoogNEcXvKq2t0t9asMXan/Bz15KmAV1GRNlC7/baFKx2p/KlyxYob0LJehTKm1gWbhyiF3ufTX8YcU2LeI7vLB/9FJYcdM50OVj8vWuO7dtu0MHdkApClS0QGmWLo36Ls=,iv:VIpONcv/qJKdYVJa9f5xsv5v30Tqf//HqGiZtxXV+d4=,tag:IBlYfSeuvWKMskcTAPpNUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
