apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pg-dumps
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-backup
  resources:
    requests:
      storage: 5Gi
