apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.10.*'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  releaseName: longhorn
  targetNamespace: longhorn-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    global:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    defaultSettings:
      taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
