apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: pool-worker-1
  namespace: openebs
spec:
  node: k0s-worker-1
  disks: ["aio:///dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S4EWNX0R523347D"]
