apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudflare-ddns-ipv4-last
  namespace: cloudflare-ddns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ki

