apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-enterprise-operator
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: redis-enterprise-operator
      version: '8.0.2-2'
      sourceRef:
        kind: HelmRepository
        name: redis-enterprise-operator
      interval: 5m
  releaseName: redis-enterprise-operator
  targetNamespace: redis-enterprise-operator
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    existingSecret: secret-redis-enterprise-operator
    env:
      email: "redis-enterprise-operator@sakul-flee.de" 
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
      hosts:
        - host: redis-enterprise-operator.sakul-flee.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: redis-enterprise-operator-sakul-flee-de-tls
          hosts:
          - redis-enterprise-operator.sakul-flee.de
