apiVersion: ENC[AES256_GCM,data:PFM=,iv:6tuesjDtq/X84XO2JRQ3hLBpzitgGRGLnMInBrEfcmg=,tag:EC3o3389GVYXuqY0B2+gtw==,type:str]
kind: ENC[AES256_GCM,data:WGY5zDI6,iv:7YZHdyLiwRqaUppXtNrfotzoXs7RMTJCNAUxNvliTFE=,tag:OLoPLz8GmV+fUXjqQ8Ly8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WIOF18uGM9DBxIQc0CRNWw==,iv:b+ISRe3QCBQpq/iZG1HsnpjDd64THL2dT+fCdyt2r/I=,tag:dnGpiejfVsnmSctRanLSfg==,type:str]
    namespace: ENC[AES256_GCM,data:v/DBAMNVzcHa,iv:MSNSClH4TwON2VvDjds9CBoqiZo8COwj9/zrLmR3Sn8=,tag:a9LenKuXzQdfZfo7TlSDFg==,type:str]
type: ENC[AES256_GCM,data:hc7pWTcE,iv:mr0hNjosIr7i8/9I22hBStX/pKsS7NLYTlFisVSZkyo=,tag:lUEEcvZfMAEWmtb+DHdtUg==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:XyBomYRzCwPPsXog+nG2zwJK5NSI/OmH7G5l//wchFBcWyFXtwBoBmxnp6EPI5Y/tOh8a/2howEIWe4jG6Xtpw==,iv:efM4ItcBiXEiMheUG0YnZm48mgNQZXesjL/fntsFLbI=,tag:7/QrwCbpsEvz9fO79ac5AQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:YTLWvWY=,iv:4GwvVWClrC5950jnExQkvs5bOiDomodnUXVh/SZ2Gow=,tag:di3wto0xgAGMQQM0zXJ+nw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:5nNcNBt0Fa2B5/qsEFsScQzqUodtcQ55hkaztgudc9A=,iv:HF96l9XbCgddaQuTtYfAGuxn4itD7aZmSjIqF3sZQx4=,tag:MXW07W5qTMsbTKR56heIuA==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:o3xd8RfQQ3hg3fCFek3X7x2utWwHtfs=,iv:k9sDxsllYzBQB0dZBc1ZQrw8cFbpVc1nszVrSjn7Lhc=,tag:UejhYrQnLwbPcrgV/p8QUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR1JqZ3dwN1g1QjVyRk9p
            UDArd0tiakFmanhSYlhubTZkbHhpUHdXRW5ZCnFpSUpEM0F6anNmZnp5NFU2d2o4
            aGNPa1gyVEhzN2NJTlUzS2JYN0lvUFUKLS0tIHZKZHR1WUd5TVFuZWJjZWVCQ3Yv
            SkoydFdXYy9ta01iRGVvYzhHWU1NTDQK1K7Nrjrj8kp61hwobLs8by4Bg1w0tD8f
            d0A8UYnUubvU1UchPEHHFqq2U9zLtFz41odRJgok945DIRDwhnE6oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ2dKKzdxNU5vRkJma2tj
            VDJKVWFHMmFBek1mTlR4YU5MYUdhQ0hWMENVCkFEOWh6MTZRdndQTUc5RWlhaXZ4
            OUFwaWN3bnMrRnRCYUVZZnZZb1FOdlEKLS0tIGNOYUo5T3pIVFpjUjVCYmZCbXBi
            ckF6WlQ0WkovdUlTbjRxV1d0T0Mya3MKHme5gmPhhw24plquQ66/g8+rP58MhIZr
            HTFONdzGL+bPKyViV6YjAhXr6ae3ia4dscDe9E6SskJmnCCEyVev4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT3BXQjU2ZlI3NkFQaUo1
            eU5TaFlwWU0vYzhoNVZSazl0OVA4TWVsN1hjCmdsamd3V21jdlVzaFJuQnhPcC9Q
            K3RRQnVCYmZMbGxIaUhOak1SdENmbTQKLS0tIGxiaTRXZndQdlZSVTN3eFJOY09C
            bUlsMW5TVmU0TkFkbUJkSjVORDNRKzQKmix/c+GW+52N8cptiroTaeD02GHaiHpD
            uKahWovouwUboBOQvViPwJ+efKOA3OMfBA4hSIXHgQWst9cEK/KxLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-22T15:39:09Z"
    mac: ENC[AES256_GCM,data:yCDjPrj7T2hmXcn8wzaF30jyaW03MXJOdHuyY8k8XQEMpi1rC1bWz+E2eWNuC88kuYxsrcxhC8OSXhV3HAt1/cpE0uwU5asJRccMcGN9P04G+jL1yJdCR+Z6C0/EswcIVbUe5dwSqWsrrBOXMo86m6lOpIP/BamWsRO31Pk4+zo=,iv:gDYNk1jYMGMC6TZRn4/8g6dVMI/t0KqlnVHj/jC4J+M=,tag:D2Yc6CG5kFpHsYfU6zVOlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
