apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: nextcloud
      version: '8.5.x'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 5m
  releaseName: nextcloud
  targetNamespace: nextcloud
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    # Nextcloud settings
    nextcloud:
      host: nextcloud.sakul-flee.de
      existingSecret:
        enabled: true
        secretName: secret-nextcloud
        usernameKey: username
        passwordKey: password
        smtpUsernameKey: smtpUsername
        smtpPasswordKey: smtpPassword
        smtpHostKey: smtpHost
      mail:
        enabled: true
        fromAddress: 'nextcloud'
        domain: 'sakul-flee.de'
        smtp:
          secure: ''
          authType: 'LOGIN'
          port: 587
      defaultConfigs:
        s3.config.php: false 
        swift.config.php: false 
        imaginary.config.php: true
      configs:
        previews.config.php: |-
          <?php
          $CONFIG = array (
            'enable_previews' => true,
            'enabledPreviewProviders' => array (
              'OC\Preview\Movie',
              'OC\Preview\PNG',
              'OC\Preview\JPEG',
              'OC\Preview\GIF',
              'OC\Preview\BMP',
              'OC\Preview\XBitmap',
              'OC\Preview\MP3',
              'OC\Preview\MP4',
              'OC\Preview\TXT',
              'OC\Preview\MarkDown',
              'OC\Preview\PDF'
            ),
          );
        https.config.php: |-
          <?php
          $CONFIG = array(
            'overwriteprotocol' => 'https',
            'overwritehost' => 'nextcloud.sakul-flee.de',
            'trusted_proxies' => [
              '10.0.0.0/8',
            ],
            'forwarded_for_headers' => [
              'HTTP_X_FORWARDED_FOR',
              'HTTP_X_FORWARDED_HOST',
              'HTTP_X_FORWARDED_PROTO'
            ],
          );
        trash.config.php: |-
          <?php
          $CONFIG = array (
            'trashbin_retention_obligation' => 'auto'
          );
      trustedDomains:
        - nextcloud.sakul-flee.de
      extraEnv:
        # Set cluster CIDR as trusted
        - name: TRUSTED_PROXIES
          value: "10.0.0.0/8"
    
      extraVolumes:
        - name: app-hook
          configMap:
            name: nextcloud-app-hook
            defaultMode: 0777

      extraVolumeMounts:
        - name: app-hook
          mountPath: /docker-entrypoint-hooks.d/before-starting/app-start-hook.sh
          subPath: app-hook.sh
          readOnly: true

    startupProbe:
      enabled: true
      initialDelaySeconds: 45

    # Ingress 
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: nextcloud-middleware-nextcloud@kubernetescrd
      hosts:
        - nextcloud.sakul-flee.de
      tls:
        - secretName: nextcloud-tls
          hosts:
            - nextcloud.sakul-flee.de
    
    # Service 
    service:
      annotations:
        traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    
    # Persistence 
    persistence:
      enabled: true
      storageClass: longhorn-replicated
      size: 8Gi
      accessMode: ReadWriteOnce 
      nextcloudData:
        enabled: true
        storageClass: longhorn-replicated 
        size: 256Gi
        accessMode: ReadWriteOnce 
    
    # Database 
    internalDatabase:
      enabled: false
    
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-postgres-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname

    # Redis 
    externalRedis:
      enabled: true
      existingSecret:
        enabled: true
        secretName: nextcloud-redis 
        passwordKey: redis-password
      host: nextcloud-redis-master
    
    # Cron 
    cronjob:
      enabled: true
      type: sidecar
    
    # Imaginary (Galery)
    imaginary:
      enabled: true
    
    # Collabora (Office)
    collabora:
      enabled: true

      autoscaling:
        enabled: false
    
      collabora:
        existingSecret:
          enabled: true
          secretName: secret-nextcloud-collabora
          usernameKey: username
          passwordKey: password
        server_name: collabora.sakul-flee.de
        aliasgroups:
          - host: https://nextcloud.sakul-flee.de    
        extra_params: --o:ssl.enable=false --o:ssl.termination=true 
    
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: nextcloud-middleware-nextcloud@kubernetescrd
        hosts:
          - host: collabora.sakul-flee.de
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: collabora-tls
            hosts:
              - collabora.sakul-flee.de
    
    # Metrics (Prometheus Exporter)
    metrics:
      enabled: true
    
