apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-hsts
  namespace: nextcloud
spec:
  headers:
    # Use the dedicated HSTS fields for clarity
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    forceSTSHeader: true
