apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: rook-ceph
      version: '1.18.*'
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
      interval: 5m
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    csi:
      kubeletDirPath: "/var/lib/k0s/kubelet"

