apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins
      version: '5.8.x'
      sourceRef:
        kind: HelmRepository
        name: jenkins
      interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-volatile
      size: 8Gi

    controller:
      admin:
        username: SakulFlee
        createSecret: true

      # Ingress
      ingress:
        enabled: true
        className: traefik
        annotations: 
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hostname: jenkins.sakul-flee.de
        path: /
        tls:
         - secretName: jenkins-sakul-flee-de-tls
           hosts:
             - jenkins.sakul-flee.de

      prometheus:
        enabled: true

      installPlugins:
        - kubernetes
        - workflow-aggregator
        - git
        - configuration-as-code
        - locale
        - dark-theme
        - matrix-auth
        - job-dsl
        - blueocean

      JCasC:
        authorizationStrategy: |-
          globalMatrix:
            entries:
              - user:
                  name: "${chart-admin-username}"
                  permissions:
                    - "Overall/Administer"
              - user:
                  name: "anonymous"
                  permissions:
                    - "Overall/Read"
                    - "Job/Read"
              - group:
                  name: "authenticated"
                  permissions:
                    - "Overall/Read"
                    - "Job/Build"
                    - "Job/Create"
        configScripts:
          # locale-config: |
          #   locale:
          #     languageCode: "en"
          #     ignoreAcceptLanguage: false
          #     countryCode: "US"
          seed-job-config: |
            jobs:
              - script: >
                  job('Job-Seeder') {
                    description('Job that runs all Job DSL Groovy scripts from SCM.')

                    scm {
                      git {
                        url('https://forgejo.sakul-flee.de/SakulFlee/Jenkins-Job-Configurations')
                        branch('main')

                        extensions {}
                      }
                    }

                    steps {
                      jobDsl {
                        // Process all Groovy Job definition files in the repository.
                        // This will add each Job definition to Jenkins.
                        targets('**/*.groovy') 
                      }
                    }

                    triggers {
                      // Run every 5 minutes
                      cron('H/5 * * * *')
                    }
                  }
