apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins-operator
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins-operator
      version: '0.8.x'
      sourceRef:
        kind: HelmRepository
        name: jenkins-operator
      interval: 5m
  releaseName: jenkins-operator
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    jenkins:
      enabled: true
      name: jenkins
      namespace: jenkins
      image: jenkins/jenkins:2.539-slim-jdk21
    #   configuration:
    #     configurationAsCode: []
    # #    - configMapName: jenkins-casc
    # #      content: {}
