apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins
      version: '5.8.x'
      sourceRef:
        kind: HelmRepository
        name: jenkins
      interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
      size: 8Gi

    controller:
      admin:
        username: SakulFlee
        createSecret: true
  
      jenkinsUrl: jenkins.sakul-flee.de
      jenkinsUrlProtocol: https
      jenkinsAdminEmail: jenkins@sakul-flee.de
  
      image:
        registry: "docker.io"
        repository: "jenkins/jenkins"
        tag: "2.539-slim-jdk21"

      # Ingress
      ingress:
        enabled: true
        className: traefik
        annotations: 
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hostname: jenkins.sakul-flee.de
        path: /
        tls:
         - secretName: jenkins-sakul-flee-de-tls
           hosts:
             - jenkins.sakul-flee.de

      prometheus:
        enabled: true

      additionalExistingSecrets:
      - name: secret-jenkins-forgejo
        keyName: password

      additionalPlugins:
        - locale
        - dark-theme
        - matrix-auth
        - job-dsl
        - pipeline-stage-view
        - pipeline-graph-view
        - gitea

      JCasC: 
        defaultConfig: true
        overwriteConfiguration: true
        authorizationStrategy: |-
          globalMatrix:
            entries:
              - user:
                  name: "${chart-admin-username}"
                  permissions:
                    - "Overall/Administer"
              - user:
                  name: "anonymous"
                  permissions:
                    - "Overall/Read"
                    - "Job/Read"
              - group:
                  name: "authenticated"
                  permissions:
                    - "Overall/Read"
                    - "Job/Build"
                    - "Job/Create"
        configScripts:
          locale-config: |
            appearance:
              locale:
                allowUserPreferences: true
                ignoreAcceptLanguage: false
                systemLocale: "en"
          job-security-config: |
            security:
              globalJobDslSecurityConfiguration:
                useScriptSecurity: false
          pipeline-graph-view-config: |
            appearance:
              pipelineGraphView:
                showGraphOnBuildPage: true
                showGraphOnJobPage: true
                showStageDurations: true
                showStageNames: true
          theme-config: |
            appearance:
              themeManager:
                disableUserThemes: false
                theme: "dark"
          content-security-policy-config: |
            security:
              contentSecurityPolicy:
                enforce: true
          credentials-forgejo: |
            credentials:
              system:
                domainCredentials:
                - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: "forgejo-credentials"
                      username: "Jenkins"
                      password: "${secret-jenkins-forgejo}"
                      description: "API PAT Token for Forgejo Organization Folder Scan"
          seed-job-config: |
            jobs:
              - script: >
                organizationFolder('forgejo') {                                                                                                                      triggers {
                  periodicFolderTrigger {
                      cron('H H/4 * * *')
                  }
                                                                                                                                                                                navigators {
                  gitea {
                    serverUrl('https://forgejo.sakul-flee.de')
                    repoOwner('Jenkins')
                    credentialsId('forgejo-credentials')
                    
                    traits {
                      branchDiscoveryTrait {
                        strategyId(1)
                      }
                      originPullRequestDiscoveryTrait {
                        strategyId(1)
                      }
                    }
                  }
                
                  projectFactories {
                    workflowMultiBranchProjectFactory {
                      scriptPath('Jenkinsfile')
                    }
                  }
                }

# - script: >
#     job('Job-Seeder') {
#       description('Job that runs all Job DSL Groovy scripts from SCM.')
#
#       scm {
#         git {
#           remote {
#             name('origin')
#             url('https://forgejo.sakul-flee.de/SakulFlee/Jenkins-Job-Configurations')
#           }
#
#           branch('main')
#
#           extensions {}
#         }
#       }
#
#       steps {
#         jobDsl {
#           // Process all Groovy Job definition files in the repository.
#           // This will add each Job definition to Jenkins.
#           targets('**/*.groovy') 
#         }
#       }
#
#       triggers {
#         // Run every 5 minutes
#         cron('H/5 * * * *')
#       }
#     }

#                 organizationFolder('forgejo') {
#                   // orphanedItemStrategy {
#                   //     discardOldItems {
#                   //         numToKeep(-1)
#                   //         daysToKeep(-1)
#                   //         pruneDeadBranches(true)
#                   //     }
#                   // }
#                   triggers {
#                       periodicFolderTrigger {
#                           cron('H H/4 * * *')
#                       }
#                   }
#                   // properties {
#                   //     organizationChildOrphanedItemsProperty {
#                   //         strategy(inherit())
#                   //     }
#                   //     noTriggerOrganizationFolderProperty {
#                   //         branches('.*')
#                   //         strategy('NONE')
#                   //     }
#                   // }
#                   navigators {
#                       gitea {
#                           serverUrl('https://forgejo.sakul-flee.de')
#                           repoOwner('Jenkins')
#                           credentialsId('forgejo-credentials')
#                           traits {
#                               branchDiscoveryTrait {
#                                   strategyId(1)
#                               }
#                               originPullRequestDiscoveryTrait {
#                                   strategyId(1)
#                               }
#                               // forkPullRequestDiscoveryTrait {
#                               //     strategyId(1)
#                               //     trust(class: 'org.jenkinsci.plugin.gitea.ForkPullRequestDiscoveryTrait$TrustContributors')
#                               // }
#                           }
#                       }
#                   }
#                   projectFactories {
#                       workflowMultiBranchProjectFactory {
#                           scriptPath('Jenkinsfile')
#                       }
#                   }
#               }
