apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins-operator
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins-operator
      version: '0.8.x'
      sourceRef:
        kind: HelmRepository
        name: jenkins-operator
      interval: 5m
  releaseName: jenkins-operator
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: disabled  
  values:
    jenkins:
      enabled: true
      name: jenkins
      namespace: jenkins
      image: jenkins/jenkins:2.539-slim-jdk21
      annotations:
        fluxcd.io/ignore: "true"
      basePlugins:
      - name: kubernetes
        version: "4392.v19cea_fdb_5913"
      - name: workflow-job
        version: "1559.va_a_533730b_ea_d"
      - name: workflow-aggregator
        version: "608.v67378e9d3db_1"
      - name: git
        version: "5.8.0"
      - name: job-dsl
        version: "1.93"
      - name: configuration-as-code
        version: "2006.v001a_2ca_6b_574"
      - name: kubernetes-credentials-provider
        version: "1.299.v610fa_e76761a_"
      plugins:
      - name: locale
        version: "614.va_6a_5a_1a_f2b_38" 
      - name: dark-theme
        version: "574.va_19f05d54df5"
      - name: matrix-auth
        version: "3.2.9"
      - name: job-dsl
        version: "1.93"
      - name: pipeline-stage-view
        version: "2.38"
      - name: pipeline-graph-view
        version: "712.v9ea_78cc1e8a_4"
      - name: gitea
        version: "250.v76a_0b_d4fef5b_"
      - name: gitea-checks
        version: "601.607.vcea_0049b_27e5"
      configuration:
        configurationAsCode:
        - configMapName: jenkins-casc
        - configMapName: jenkins-casc-auth
      # seedJobs:
      # - id: jenkins-operator
      #   targets: "jobs/*.jenkins"
      #   description: "Jenkins Operator repository"
      #   repositoryBranch: main
      #   repositoryUrl: https://forgejo.sakul-flee.de/SakulFlee/Jenkins-Operator.git
