apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins
      version: '5.8.x'
      sourceRef:
        kind: HelmRepository
        name: jenkins
      interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-volatile
      size: 32Gi

    controller:
      admin:
        username: SakulFlee
        createSecret: true

      # Ingress
      ingress:
        enabled: true
        className: traefik
        annotations: 
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hostname: jenkins.sakul-flee.de
        path: /
        tls:
         - secretName: jenkins-sakul-flee-de-tls
           hosts:
             - jenkins.sakul-flee.de

      prometheus:
        enabled: true

      # additionalPlugins:
      # # - locale
      # # - matrix-auth
      # # - dark-theme
      # # - blueocean
      # # - job-dsl
      #
      # JCasC:
      #   securityRealm: |-
      #     local:
      #       allowsSignup: false
      #       enableCaptcha: false
      #       users:
      #       - id: "${chart-admin-username}"
      #         name: "Jenkins Admin"
      #         password: "${chart-admin-password}"
      #   authorizationStrategy: |-
      #     loggedInUsersCanDoAnything:
      #       allowAnonymousRead: true
      #     globalMatrix:
      #       entries:
      #         - user:
      #             name: "admin"
      #             permissions:
      #               - "Overall/Administer"
      #         - user:
      #             name: "anonymous"
      #             permissions:
      #               - "Overall/Read"
      #               - "Job/Read"
      #         - group:
      #             name: "authenticated"
      #             permissions:
      #               - "Overall/Read"
      #               - "Job/Build"
      #               - "Job/Create"
        # configScripts:
        #   jobs:
        #   - script: >
        #       folder('testjobs')
        #   - script: >
        #       pipelineJob('testjobs/default-agent') {
        #         definition {
        #           cps {
        #             script("""\
        #               pipeline {
        #                 agent any
        #                 stages {
        #                   stage ('test') {
        #                     steps {
        #                       echo "hello"
        #                     }
        #                   }
        #                 }
        #               }""".stripIndent())
        #           }
        #         }
        #       }
