---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins
      version: 5.8.x
      sourceRef:
        kind: HelmRepository
        name: jenkins
      interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
      size: 8Gi
    controller:
      admin:
        existingSecret: secret-jenkins-admin
        userKey: username
        passwordKey: password
      jenkinsUrl: https://jenkins.sakul-flee.de
      jenkinsUrlProtocol: https
      jenkinsAdminEmail: jenkins@sakul-flee.de
      image:
        registry: docker.io
        repository: jenkins/jenkins
        tag: jdk21
        pullPolicy: Always
      # Ingress
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hostName: jenkins.sakul-flee.de
        resourceRootUrl: jenkins.sakul-flee.de
        path: /
        tls:
          - secretName: jenkins-sakul-flee-de-tls
            hosts: [jenkins.sakul-flee.de]
      prometheus:
        enabled: true
      additionalExistingSecrets:
        - name: secret-jenkins-forgejo
          keyName: token
      additionalPlugins:
        - locale
        - dark-theme
        - matrix-auth
        - job-dsl
        - pipeline-graph-view
        - gitea
      JCasC:
        defaultConfig: true
        overwriteConfiguration: true
        authorizationStrategy: |-
          globalMatrix:
            entries:
              - user:
                  name: "${chart-admin-username}"
                  permissions:
                    - "Overall/Administer"
              - user:
                  name: "anonymous"
                  permissions:
                    - "Overall/Read"
                    - "Job/Read"
              - group:
                  name: "authenticated"
                  permissions:
                    - "Overall/Read"
                    - "Job/Build"
                    - "Job/Create"
        configScripts:
          locale-config: |
            appearance:
              locale:
                allowUserPreferences: true
                ignoreAcceptLanguage: false
                systemLocale: "en"
          job-security-config: |
            security:
              globalJobDslSecurityConfiguration:
                useScriptSecurity: false
          pipeline-graph-view-config: |
            appearance:
              pipelineGraphView:
                showGraphOnBuildPage: true
                showGraphOnJobPage: true
                showStageDurations: true
                showStageNames: true
          theme-config: |
            appearance:
              themeManager:
                disableUserThemes: false
                theme: "dark"
          content-security-policy-config: |
            security:
              contentSecurityPolicy:
                enforce: true
          build-resource-url: |
            unclassified:
              resourceRoot:
                url: "https://jenkins.sakul-flee.de/"
          performance-optimization: |
            unclassified:
              globalDefaultFlowDurabilityLevel:
                durabilityHint: PERFORMANCE_OPTIMIZED
          forgejo-server: |
            unclassified:
              giteaServers:
                servers:
                - credentialsId: "forgejo-credentials"
                  displayName: "Forgejo"
                  manageHooks: true
                  serverUrl: "https://forgejo.sakul-flee.de"
          credentials-forgejo: |
            credentials:
              system:
                domainCredentials:
                - credentials:
                  - giteaAccessToken:
                      scope: GLOBAL
                      id: "forgejo-credentials"
                      description: "API PAT Token for Forgejo Organization Folder Scan"
                      token: "${secret-jenkins-forgejo-token}"
          seed-job-config: "jobs:\n  - script: >\n      organizationFolder('Forgejo\
            \ - SakulFlee') {\n        organizations {\n          gitea {\n      \
            \      displayName('Forgejo: @SakulFlee projects')\n            serverUrl('https://forgejo.sakul-flee.de')\n\
            \            repoOwner('SakulFlee')\n            credentialsId('forgejo-credentials')\n\
            \n            traits {\n              giteaBranchDiscovery {\n       \
            \         strategyId(3)\n              }\n\n              giteaPullRequestDiscovery\
            \ {\n                strategyId(1)\n              }\n            }\n \
            \         }\n        }\n\n        projectFactories {\n          workflowMultiBranchProjectFactory\
            \ {\n            scriptPath('Jenkinsfile')\n          }\n        }   \
            \               \n        \n        triggers {\n          periodicFolderTrigger\
            \ {\n            interval('30m')\n          }\n        }\n      }\n  -\
            \ script: >\n      organizationFolder('Forgejo - SakulFlee University')\
            \ {\n        organizations {\n          gitea {\n            displayName('Forgejo:\
            \ @SakulFlee University projects')\n            serverUrl('https://forgejo.sakul-flee.de')\n\
            \            repoOwner('University')\n            credentialsId('forgejo-credentials')\n\
            \n            traits {\n              giteaBranchDiscovery {\n       \
            \         strategyId(3)\n              }\n\n              giteaPullRequestDiscovery\
            \ {\n                strategyId(1)\n              }\n            }\n \
            \         }\n        }\n\n        projectFactories {\n          workflowMultiBranchProjectFactory\
            \ {\n            scriptPath('Jenkinsfile')\n          }\n        }   \
            \               \n        \n        triggers {\n          periodicFolderTrigger\
            \ {\n            interval('30m')\n          }\n        }\n      }\n  -\
            \ script: >\n      organizationFolder('Forgejo - SakulFlee Container')\
            \ {\n        organizations {\n          gitea {\n            displayName('Forgejo:\
            \ @SakulFlee Container projects')\n            serverUrl('https://forgejo.sakul-flee.de')\n\
            \            repoOwner('Container')\n            credentialsId('forgejo-credentials')\n\
            \n            traits {\n              giteaBranchDiscovery {\n       \
            \         strategyId(3)\n              }\n\n              giteaPullRequestDiscovery\
            \ {\n                strategyId(1)\n              }\n            }\n \
            \         }\n        }\n\n        projectFactories {\n          workflowMultiBranchProjectFactory\
            \ {\n            scriptPath('Jenkinsfile')\n          }\n        }   \
            \               \n        \n        triggers {\n          periodicFolderTrigger\
            \ {\n            interval('30m')\n          }\n        }\n      }\n"
