apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: jenkins
      version: '5.8.x'
      sourceRef:
        kind: HelmRepository
        name: jenkins
      interval: 5m
  releaseName: jenkins
  targetNamespace: jenkins
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    controller:
      admin:
        username: SakulFlee
        createSecret: true

      # Ingress
      ingress:
        enabled: true
        className: traefik
        annotations: 
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hostname: jenkins.sakul-flee.de
        tls:
         - secretName: jenkins-sakul-flee-de-tls
           hosts:
             - jenkins.sakul-flee.de

      prometheus:
        enabled: true
