apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins
  namespace: jenkins
spec:
  limits:
    - default:
        cpu: 1000m
        memory: 1Gi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      max:
        cpu: 2000m
        memory: 8Gi
      type: Container
