apiVersion: ENC[AES256_GCM,data:XwM=,iv:0XIsHy24ukM+VuJiMGsRL2lbroj2Z9Szl4sqOpqtRIw=,tag:Ov5Prg1Ewex8zjZCTJwh7g==,type:str]
kind: ENC[AES256_GCM,data:MZXMxxRg,iv:K6hm52MZ4kIx+oUO1mIX9wHP48/1drae6uT24/iohlM=,tag:/xPkG3KGDja/v3oMiarTHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W9kJg5bF4kzwz5/BcT3j,iv:nLgGIF126aBG2pKvbpUsF6nRgnC8VvDAbV11klqDnvA=,tag:IezWJ11zeqjHFIQAlfIc6Q==,type:str]
    namespace: ENC[AES256_GCM,data:pcIqbOuK4A==,iv:cPtIl+iscY5HMxxicnDdqQrRsg9bzGxEgds0wtF/cf4=,tag:+P8r14ydNSnhcJaUVS/j0A==,type:str]
type: ENC[AES256_GCM,data:hEZjq7gW,iv:Tuz6kjPjPwPJSwlCVIsJQyq0Xbgg1oQOCPfVzoOLNOA=,tag:qmWZYc6w2AXkwKEbE9qB8A==,type:str]
stringData:
    registration_shared_secret: ENC[AES256_GCM,data:X9xp4ssWeKOIGEwp+aDLLCvCVfBA7hQ4sZYBlNrWzmXJoCvAjrujrSyZ3w3kwAS7n3iVrDKQgx5GN1cNwanriw==,iv:xHvkJYh8SYbupMnOT2yffdWY/4YoHHNIOSbKL0WQqJg=,tag:isngn61HcwQX+iS8LdcvzA==,type:str]
    macaroon_secret_key: ENC[AES256_GCM,data:5DK3mMkHsKJbymmjLzaNHkSu+N8WJ3bW4UNqieeVRcd4ipe9MJchgFy4dHcc93VCMP6sdtKYUL8MoWBztinj+A==,iv:Jrpdhin8CULWcnZNQkrIQnlfn1yKODfi08xCAXYfGig=,tag:flRIyhHvc1Lho6C5HBDzdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaHovbndjVUI1OVppLytt
            ZytrM2xvZmFHa1B3WHhwbVlGT0xqY0VPSHcwCkcxd3JmUWl0bVBTaVhMWCtNQXAv
            TXI0YU9sRy9mWXFrL3BRZ3ZJM3owYnMKLS0tIHV2R3VhNjFIa0ZRdDRMVWVwQnV6
            RTFJMm9nUWR6NlBKOTBWWUxBTkRMclEK4JelztuZHjysOqvm5BKUMh2l69sAOfMd
            pbOKVgcvQJ4MyyY80o1w466VKLhWotpXbaHh8BHgbeafoiUXO6WNRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNzhIM1lKaFBvYUNIRks3
            dmg4MnpwWHlKOXRuOHAwWWR1eFBYZDBRcVI4CndieXdsd054MWFOVEppUlJFWlFZ
            TXVFU2UxcSswRFduZGlTQ2p4aWhQbVEKLS0tIHd1b0UxMXA3ZnZKcW9qaFE1Sklx
            ekNzSmRFRGx6ZXZUQkR1dW1ERGhqNjAKH842HCo0SZlpfTNM34RkfqhGX2QKPMCG
            3k6Lh622CN+wKyhmCZutjPSa0oZuvULwVowZvu2pXjHC5XONC/E/2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VGc5cUNhL3Yza1E2SG1S
            VFZUSkw1cDhRRU9KcEw0WSt1ZEg2c1J6K0FZCkhUc2dEWVlFYnA4MWNqSHlrYWdv
            V1JqUXJuQ2FnbGpWa25xQ24zMzVObzAKLS0tIEJQQUlyNlFuVzVTb0EyWUsvd05u
            eFgzcnozbGZSYnJ3b2RoZVFTYU5sRTgKRIJc0YXoQxBW8LRw0YHbwGBEXZ10oh78
            gJC/otelYhl3Z6rvjJHL1StFLaJmSHrE8nPB8CNnaYhS/yd+H90vkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-22T20:50:26Z"
    mac: ENC[AES256_GCM,data:4+mHPzbIcv0BdRdQsDlY62ylT4iXEDKa3XxyL/PI8/aP1CXaq4i0T9bTkri9OdaT+1IkON5ONhBRH4+/2Kztjw0SevSiXr7ys9fW1NcK1o+V8tUdhlL9iLRxIRbz0Ua2B6+d5K/CC917X75V7rmpbK9SgEp6bZhqfROQBOfVjmc=,iv:dnmo5wYw/g7I755eolE4wC/R/rhUIDZ+s/f2WslmNO8=,tag:QSiK6zbtc5kmN3/VYm/nWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
