apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  releaseName: forgejo-runner
  targetNamespace: forgejo-runner
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    forgejo:
      url: "http://forgejo-http.forgejo.svc.cluster.local:3000"
      existingSecret: "forgejo-runner-secret"
    image:
      repository: registry.erwanleboucher.dev/eleboucher/runner
      tag: "12.13.0"
    plugin:
      image:
        repository: registry.erwanleboucher.dev/eleboucher/runner-k8s-plugin
        tag: "12.10.9"
    runnerConfig: |
      runner:
        capacity: 3
        timeout: "3h"
        shutdown_timeout: "3m"
        labels:
          - "ubuntu-latest:k8s:/config/podspec-default.yaml"
          - "ubuntu-24.04:k8s:/config/podspec-default.yaml"
          - "default:k8s:/config/podspec-default.yaml"
      plugins:
        k8s:
          address: "unix:///plugin/forgejo-runner-k8s.sock"
          options:
            namespace: forgejo-runner
            poll_timeout: 10m
            labels: "app.kubernetes.io/name=forgejo-runner-instance"
            resources: |
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
      cache:
        enabled: true
        dir: "/data/cache"
      log:
        level: info
    podSpecs:
      podspec-default.yaml: |
        automountServiceAccountToken: false
        containers:
          - name: main
            image: node:22-bookworm
            imagePullPolicy: IfNotPresent
            env:
              - name: DEBIAN_FRONTEND
                value: noninteractive
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 500m
                memory: 4Gi
        restartPolicy: Never
    serviceAccount:
      create: true
