apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  releaseName: forgejo-runner
  targetNamespace: forgejo-runner
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    knownLastVersion: true
    image:
      registry: registry.erwanleboucher.dev
      repository: eleboucher/runner
      tag: "12.13.0"
    dind:
      enabled: true
      image:
        repository: "library/docker"
        tag: "27-dind"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
    runner:
      config:
        create: true
        instance: "http://forgejo-http.forgejo.svc.cluster.local:3000"
        token: "kNrq8IoTMZPRTCu5gwF7NXw4gQnfsddOVdnkGWW9"
        name: "forgejo-runner"
        file:
          runner:
            labels:
              - ubuntu-latest:docker://node:22-bookworm
              - ubuntu-24.04:docker://node:22-bookworm
              - default:docker://node:22-bookworm
            envs:
              DOCKER_HOST: "tcp://127.0.0.1:2376"
              DOCKER_TLS_VERIFY: "1"
              DOCKER_CERT_PATH: "/certs/client"
            capacity: 3
            timeout: "3h"
            shutdown_timeout: "3m"
          container:
            docker_host: "tcp://127.0.0.1:2376"
            network: "host"
            privileged: false
            options: "-v /certs/client:/certs/client"
            valid_volumes:
              - /certs/client
          cache:
            enabled: true
            dir: "/data/cache"
          log:
            level: info
    securityContext:
      privileged: true
