apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  releaseName: forgejo-runner
  targetNamespace: forgejo-runner
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    knownLastVersion: true
    image:
      registry: registry.erwanleboucher.dev
      repository: eleboucher/runner
      tag: "12.13.0"
    plugin:
      image:
        repository: registry.erwanleboucher.dev/eleboucher/runner-k8s-plugin
        tag: "12.10.9"
    runner:
      config:
        create: false
        existingSecret: "forgejo-runner-secret"
        file:
          runner:
            capacity: 3
            timeout: "3h"
            shutdown_timeout: "3m"
          plugins:
            k8s:
              address: "unix:///plugin/forgejo-runner-k8s.sock"
              options:
                namespace: forgejo-runner
                poll_timeout: 10m
                labels: "app.kubernetes.io/name=forgejo-runner-instance"
                resources: |
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    memory: 1Gi
          cache:
            enabled: true
            dir: "/data/cache"
          log:
            level: info
    podSpecs:
      podspec-default.yaml: |
        automountServiceAccountToken: false
        containers:
          - name: main
            image: node:22-bookworm
            imagePullPolicy: IfNotPresent
            env:
              - name: DEBIAN_FRONTEND
                value: noninteractive
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 500m
                memory: 4Gi
        restartPolicy: Never
    securityContext:
      privileged: false
