apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  interval: 5m0s
  url: oci://git.erwanleboucher.dev/eleboucher/charts/forgejo-runner
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: ^12.10.0
