apiVersion: v1
kind: Secret
metadata:
    name: homelab-restic-password
    namespace: kube-system
type: Opaque
stringData:
    pw: ENC[AES256_GCM,data:KnFxzXBMGRhsffvWI5KEEMoyFbEQQFAK+a30m/q1traI8vClxvI43SJn6IsCnAR3DC5XoAEak7B7UXi3jnR8UQ==,iv:pTL+PdOBK+kXgBCwS79Ix6J8aVAgAMPvLo7/rtj2xt0=,tag:8Jj00YUlPHj8U6hGMDYFZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvclNhNnpBTU9McWJrNVg5
            cHFPejVudkp6VUdpcDJTZEladlI3aWswbGlzCm0zV1JHUE9kR3RrWUVrSEZhYTg0
            MmREVFAvZGw1RlNhSVp6aFFZaDJIMEEKLS0tIHNzYVJFVDRmMjl3MmF6cFl3NmQ0
            bytHMk1vNldOYkdYUjVoMVZIdHpzWkUKnkl4aFzHXi++ddROJzFPPtzbBtvDI9B0
            Mz6G/VWzdzNYZ/Pi9JVuYBI56G8qECTRdWBwz6An+Or7pJF5QcECaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS2FaM08xWEVRQUJrcm9E
            cXR4Y0VJVHlJeXZId0ExeG94VkhqS29GK2dRCkEreUU1ZEJMVHc3L1N0MGZRL3FU
            QmNKYXBlL3MvemMwUmRQWGRNTlcrVGcKLS0tIGtLYkZWQTJBTkFSMDQ5czFNVzQy
            VXdPVTAyVEprRW03SDJ5VC96cHJ6UmcKoF/1yb1G0hYcqd1nSmL8/uGJ1RM+hewi
            yG7PpuxicRILOaijDETJdhefxPo1GS5U5/DQCw3wiAi7owGOJz9rGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVHA4c0d5SkpyK3NCaUFZ
            Uk1FUGZtRkQweXUvOWl3R3NQRzVnVEdGWlFVCmJBMDFsWmZjUitOVHJBZnAxU1p6
            ZmxXQlZMOTJwTWFtVXYwbGk5OVVxbW8KLS0tIEExdFkrcERmb29qSUJXTzF5SENl
            RDd1R0VmOGFyUFQ0ZTgvV2NodXJJa2MKdf08747iaFpaRb5LeDUakprvj26Y7+5B
            B4YtWmZ77Ipd0njEinKRP89G5dSCC5ZUEw78KC3mm68NcXROyg/ADQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-23T00:23:31Z"
    mac: ENC[AES256_GCM,data:NXeGUnAYkqdhOxOcKViAmFT1dIpDsJrTFX1I3wBoZcgZYbyDpt4oJN/cFIGg3wk16n8UktaSH9rAXfz0KsaydPJfgXRGK3oa3kDe4ykwHof5eFjzz4vYaFBtGSYqVurY2+WAf+d80/znFateFL4Yhoyvmb58id4fqnsQ3TdaMgc=,iv:dE6HAnnI5yVS875giHxZrsQHeZxLWA4fqU/JxQed4Sw=,tag:/VSY0yOsh2JULkFDlNRI3Q==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
