apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-backup
  annotations:
    defaultVolumeType: "local"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
parameters:
  nodePath: /var/lib/rancher/k3s/storage/backup
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
