apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
