apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: mc-router
      version: '1.4.x'
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      interval: 5m
  releaseName: mc-router
  targetNamespace: mc-router
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    nodeSelector: 
      kubernetes.io/hostname: k0s-controller 
    services:
      minecraft:
        type: NodePort
        port: 25565
        nodePort: 30565
    minecraftRouter:
      autoScale:
        up:
          enabled: true
        down:
          enabled: true
          after: 300s
      connectionRateLimit: 4
      defaultServer:
        host: minecraft.minecraft.svc.cluster.local
        port: 25565
      mappings:
        - externalHostname: minecraft.sakul-flee.de
          host: minecraft.minecraft.svc.cluster.local
          port: 25565       
        - externalHostname: mc.sakul-flee.de
          host: minecraft.minecraft.svc.cluster.local
          port: 25565
