apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-swap-config
  namespace: llama-swap
data:
  config.yaml: |
    healthCheckTimeout: 500
    logLevel: info
    logTimeFormat: ""
    logToStdout: "proxy"
    metricsMaxInMemory: 1000
    captureBuffer: 15
    sendLoadingState: true
    globalTTL: 0
    unloadTimeout: 10

    macros:
      "default":
        /app/llama-server --host 127.0.0.1 --port ${PORT} -fa on -c 65536
      "with_fit": "-fit on"
      "with_mtp": "--spec-type draft-mtp"

    models:
      "Ornith1.0 9B @Q4_K_M":
        cmd: |
          ${default}
          ${with_fit}
          -hf deepreinforce-ai/Ornith-1.0-9B-GGUF:Q4_K_M
      "[unsloth] Qwen3.5 9B @Q4_K_XL [MTP]":
        cmd: |
          ${default}
          ${with_mtp}
          ${with_fit}
          --spec-draft-n-max 6
          -np 1
          -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
      "[unsloth] Qwen3.6 35B-A3B @Q4_K_XL [MTP]":
        cmd: |
          ${default}
          ${with_mtp}
          ${with_fit}
          --spec-draft-n-max 2
          -np 1
          -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
      "[unsloth] Gemma4 26B-A4B @Q4_K_XL [QAT] [MTP]":
        cmd: |
          ${default}
          ${with_mtp}
          ${with_fit}
          --spec-draft-n-max 4
          -hf unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
      "Qwythos 9 @Q4_K_M [MTP]":
        cmd: |
          ${default}
          ${with_mtp}
          ${with_fit}
          -hf empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF:Q4_K_M
          -m Qwythos-9B-Claude-Mythos-5-1M-MTP-Q4_K_M.gguf
      "[unsloth] Gemma4 E4B @UD-Q4_K_XL [QAT] [MTP]":
        cmd: |
          ${default}
          ${with_mtp}
          ${with_fit}
          -hf unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL
      "[unsloth] Gemma4 12B @UD-Q4_K_XL [QAT] [MTP]":
        cmd: |
          ${default}
          ${with_mtp}
          ${with_fit}
          -hf unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL