apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-swap-models
  namespace: llama-swap
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi