apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: pgadmin4
      version: '1.50.*'
      sourceRef:
        kind: HelmRepository
        name: pgadmin
      interval: 5m
  releaseName: pgadmin
  targetNamespace: pgadmin
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
      hosts:
        - host: pgadmin.sakul-flee.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: pgadmin-sakul-flee-de-tls
          hosts:
          - pgadmin.sakul-flee.de
