apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: overall-alerts 
  namespace: flux-system
spec:
  providerRef:
    name: notification-provider-discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'

