apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-notifications
  namespace: flux-system
resources:
- relay-deployment.yaml
- relay-service.yaml
- provider-fluxer.yaml
- alerts-overall.yaml