---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notification-provider-telegram
  namespace: flux-system
spec:
  type: telegram
  secretRef:
    name: notification-provider-telegram