---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notification-provider-fluxer
  namespace: flux-system
spec:
  type: generic
  address: http://fluxer-webhook-relay:8080
