apiVersion: v1
kind: Secret
metadata:
    name: headplane-secrets
    namespace: headplane
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:M6jVXDn/K28ujT2YhdowS/W9bWxXD2SPEtKdpzRvwsHb1d2fDnh1fD7KtqpVtErxj2DdKAlCpjXRw2kj1Aq7Mh9aPgYxcWAdkqx9WHclOnnKVADivkRJSJjD2RElZwCIo/J0cRIg1Lw42kEN/21RHEGGALcmGQTJtnI9htY0bs1x8NWyaz9XNkzxzcOTYWbXCZ9WNDNwViK9IdSGQuEH0mcW/VBRFj8uNUAiWbuGW5OKZ+syy4kQIREjBVP6AenddQxqOMv17t//r4RmAcLpm3G59dv/41ZehyhuHo9u3rtwx3ukXH2u3XWaPBkq8uuzGuYY8jofCzzNVofv63b8BjJXcAqhlSNXRfDO8Bi+eEHE1REXBJ/ywNG7G5QEhoClM6TyBFvLTOJUrJRqPIK7sItzpwQiiH2xTW77IBo/Xrf8uLIpbrPypIpxdkDSI1sjv/LO5F3QY+F0DW0VwS0PEvBSoOqReM70dVf27z1oo9fF2qsaLJReq2JZVHXLqme5Wvv3pTQ9znvOwjyTJwbqEnk3kJZXx3z3t4U=,iv:d33xV4K0GjuL61zFLAQ07roNsk3mRo66mz3BBkRcqpE=,tag:QO8/itpV/Tlhjalc5j+CxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SGVkOGJHVjlvZk5aekdE
            bXpCWEVqakZRSEE1QjNXaE04bjNvemRKcDNjCnVwZ0ZPb0lPZ0RZb1E1Unp4QmRR
            U2JINVdrYWJONiswakErYkx3Zy8wc2sKLS0tIERXSlBFTVlzYVZNU2FjQXllQU1x
            OHJyMm0zREZVZnA4Q2ltdEpxS1J0UkEKWth74LaDXuEU1qDNROqSQLB3Abv4t3uM
            Krk71kCDLSoqCsvCJwYtDVzmrPhfJhNJKAQFCd96fG6lEgQZMCwb2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY0tZc1hPdi9jRlk0WnJC
            VmM0UXRrUWxvN1l3cEdGeFl2K0pQbkMrUWljCjZOaVFxcTB5WDR1UlVBSWRBRHEz
            elN5YzJXUUxJazlzelN3cE9oS0JiOEEKLS0tIE04UWpOTUlWRGdMaFJRdXB2NWJ2
            RDNLQVBBbEp1RGtoZFI5WUxoZkZjTmsKD6XFYuhXyFETsGkOIKb2hJQfKyV5IZd4
            bvgxuuTLdQ0gYP4qUpHXlA3Sq9V291AwOFrpdd5os8sTNV+5vKs39A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b2lXZ21LRjlpQkFKK0hy
            Q01NcGZjU2ZEK2lSQ3M4dTZHZTQ1RXJKNm1ZCnByN3dhbTcya3VUTGxmM3VVYjZP
            bVBWaGlWRzNWZnJXdFVYa2wzRFdTT2MKLS0tIDdJcG9lWjcrK2RBN0RqNkRqYU5B
            T3FIbTFCUTZ4NDdybkZiUlFWUUF6Q2cKFjvHY1XcvetmPaWevcP+II7kTAbFLoaS
            /DW4cSxxkq2CouA8qDvqYHZAWJ5W1jKOefseSwCpu2hnVuKIx9+XcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T19:31:31Z"
    mac: ENC[AES256_GCM,data:9bFRmqgceECRAeHqPOOnmGXX7Scqc1xzDQI/Gu5fkMhx2RwBVZfHz4VF0W2qpkL59F+LVf8BlJNQqjMO9IUKstLSAZXucX7XswRXKK46eVRk7xnhyu13GQV4e4UhnA03jEbNGW5Sf0/DvlPIaHq0iCXJks/9a78jZntlpbupwfg=,iv:cOGza9In+yfucUICqVsmC2rBD1zbek2etatiUZZPAlA=,tag:Usiq9Hm63CoJwx6E6/DWhw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
