apiVersion: v1
kind: Secret
metadata:
    name: headplane-secrets
    namespace: headplane
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:Iz+UVmg5SBD3paSrDDL8EouUGQ2NMffxuYjNPD5zL6ynUg1+zz7T0xjkr71ZICqBm50IBr1ZPIo7+mwc+n9mpI36A3bcW4mKqui/7lajPJNyKIQf2asSfu9d3Is7OBa8n9TZTCNRnPX7XkCxpXOr8ns6oDEbPoyhGcV4zMbGya9fONFSw4dfTobzpk97NgyM0wAs24hfEpaQ8o3CtJaTjE0FZvR8XHlGqJnJdp2FyUhg4ANVcXpGaPbySvIP11hUb9q5uvUNK/9382u+/83KJu1K77Is8SRXBiW7ksIyUWh+8pbnqpxRBeK8JzH+n/sQlguZsuXzjQGasenAyBWW9lwKmRM4HlbDkbslF3bBRP+tw3sEcJeVxlh6kk0ognsKd15PFodmekKPVPn2XbOAkGYzSZ/iGTKTE7S3Ox3sb+98u5sjaCOHlM+arslSPCq041TT2JFdopi9+rE6HqIBegPl+retH0bs0m/cQ2ihbNvvkqo+hx4vHA/JbgQWyf/ZxY93kYPkwejz6UVH8Ag05iGJxG6DDLsuuzI=,iv:ZIv7OtGkUShktnT2xctpr+YZLhxuwWe8ZYLqrdMEpr4=,tag:enPeUj0njOBSZceglixBhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd3k0NW5QUmtHYmpEYWFq
            ZGN5T1NDV3Q0VzFCbFpIVi93RkNseVVaQWhrCnVvRWVDUnVPbkZRM1NxMDNrWndE
            WWdCWDVqRVZTczRuOXBiZW9DSkR2dm8KLS0tIFNqa3NTRzNFVVFranVYTy96V1Js
            bUk1SUp6UWZmM2g4QlYvcmdkMlRGTUEKNkGsnITB0EaHrjuQlGQ2lVoFlgPJt25N
            dq0bbhPLSTaRXFd1zU/jSrUxyzovTgRZthRQbbm+R7Oh9VLN/Cp1PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS0ZqWFZhQlM2SXBQVFFl
            c0o0bkp0YmZFM0hSckhrVXRkWGNuVVZDc2pVCjhZU0xreCtRcEZ1SkdvMTcrOTJS
            bkwzb0ljNStGWGN5Mk5vMk83TVliUEkKLS0tIDlFZTJ0UnJVQ1g2ZGYwUGtzK1pG
            c3dtc2F2TjNkRnN6TDJJZlBKOTR0V28KDv2PL+h1PKqNeAjuHq/5oSe+7Xykc7QW
            VeS50JcomEhXXIfNZpxHgxv45v0y1EcR3jysUIzmdNp9A/qNpTk1EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dlJYakdselBrNk0xMTBM
            Z3NYRldUYTVuZ2s2MkxpeE9rU1g0cW4xOFFVCk8vdEhGY3phODJ2TVRQK1VKbUxH
            dVprTFZYTGNtZnhzTzVVMktJNktMKzQKLS0tIEFKTUlHM0gwSE1IZkZVOHNTRDcx
            dUNpOVhxODAxNldqMWVoSm9pQXgzWFkK0Qx+zmjt7hmfovzKdHmebejp6n0ou7Nt
            /3jTCgTQyI/30tYGNCotHlNoiGZrb9GFDbA0wIbZ9eZqNqrW/KrfJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T19:43:27Z"
    mac: ENC[AES256_GCM,data:n3irzJ24mXV1N5Lkziiygl9YEpx6ZeUUMZ9dyXbaUf0r2nvqNRnl03ZdoImWkRI8FYhHm8gRxnnAbXiZpGhIu4LzAxM6HjktMM+xSYJ06F8ei3K8YHW8Y0PB2RNAS+Xct0eNle4npw8rhZKjHK3QKY3Y01zecEKpDTGlKLpfFCk=,iv:cHQfkL+cgwuv9dnSUn7N4vy1XH/rB6yUYV9jaB5gf+o=,tag:ye1kvKDLdBmF+1ypYag5fQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
