- name: Configure Woodpecker server
  ansible.builtin.template:
    src: woodpecker-server.env.j2
    dest: /etc/woodpecker/woodpecker-server.env
    owner: woodpecker
    group: woodpecker
    mode: '0600'
  notify: Restart Woodpecker Server

- name: Upload SystemD Service file
  ansible.builtin.copy:
    src: files/woodpecker-server.service
    dest: /etc/systemd/system/woodpecker-server.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Woodpecker Server

- name: Ensure Woodpecker-Server service is enabled and started
  ansible.builtin.systemd:
    name: woodpecker-server
    state: started
    enabled: true
    daemon_reload: true
