- name: Create a system group for Woodpecker
  ansible.builtin.group:
    name: woodpecker
    system: true
    state: present

- name: Create a system user for Woodpecker
  ansible.builtin.user:
    name: woodpecker
    group: woodpecker
    system: true
    shell: /bin/bash
    home: /var/lib/woodpecker
    create_home: true

- name: Add user to docker group
  ansible.builtin.user:
    name: woodpecker
    groups: docker
    append: yes

