apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.26.*'
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 5m
  releaseName: cloudnative-pg
  targetNamespace: cloudnative-pg
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
