apiVersion: v1
kind: Secret
metadata:
    name: fluxer-secrets
    namespace: fluxer
type: Opaque
stringData:
    FLUXER_POSTGRES_PASSWORD: ENC[AES256_GCM,data:81/EoMxc5vrwfjOFqol0WvcWuHCq3OXfuID4DMyD9XP6i+Oo6AchnztFi672cYAnw94vcz2sUN2glBOb9sF2Kg==,iv:OhNpszElfC1PDW9YBVl+6jMxw7Y1lduPiaKkEqF29cQ=,tag:nENUSFj1XSemqSweal72BQ==,type:str]
    FLUXER_SEARCH_API_KEY: ENC[AES256_GCM,data:hVwcnzwC06WwVKxPy6egY5Bz9f4GY9Hu+84iAB1dlBtQkitl7LWkIwBHVZLnNx4tvXcahtxbOWYMDc1YBCh8gw==,iv:oXGUa4evGIdZrpxHahiZK3ruJBGw52MhEXRg9Sf/ge0=,tag:Vjzr3D0sn5cyubt4z1CskQ==,type:str]
    FLUXER_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kU9pMhvJTSSOST3pU6M6OiKbnkGueroEi5y+9XgqTo2nxCy+7aPBXDidFSaL12rkZXL0hyC7d0xFrWWuXpVkqA==,iv:YoJtWa95F+0BwyYMQcQnSsOqfS9eP1mVp40CkD/a8W0=,tag:MTvIqwXILqgvvM4KaXqwIw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DH7+tZqENKOV2gJGyNltz/6TgHm+fQmsaL+dEIhWMggLLzWC43J+YNeBd1GHWQI71mDgUdcPCLhnym99CL2vXQ==,iv:5avG5KN7pxPNhwAeR3Ze6jL5zFXIv0ZUCl+5386jD4U=,tag:CLb2xkRlhQPWOhxBue+fgQ==,type:str]
    FLUXER_SUDO_MODE_SECRET: ENC[AES256_GCM,data:T61PoYCvkezfEkWxYwTCRvtcbiwy9IA2jYIKk8AegCC/zuj8Vcb750ywiKGTN4vOiMo3H7UlCgrVyDSOVpOUdw==,iv:P4+4sRV201tOOfakQ0U//5sDNz0QIzYoVCZjiKcnMQ4=,tag:ge5PXSJ1WXVJ49yX49esOg==,type:str]
    FLUXER_CONNECTION_INITIATION_SECRET: ENC[AES256_GCM,data:J9TBCiKLXDME63ngo4JfjXpsQ4MSVwjUO5X/gzEvXeWrt3AfeHHAIm8k2RuaeaYPEZwm1U24YwH6UHxHd+E3eQ==,iv:ahhaibiHKXZ3p9YXwwdY/uROpmTeDnHyhBk1FBSooko=,tag:nt2VEY59BGfdWmd64fBIIg==,type:str]
    FLUXER_GATEWAY_RPC_AUTH_TOKEN: ENC[AES256_GCM,data:3O5gq9h9R5n2l1NfN668UZp1fipA8fpPCP2uJ4FvyJVoNSZsgTM63G6xH4GzHsUN7IpHGiA6rVU15t2VjzxPPQ==,iv:20O4I0AFgrB3+sa7Bt5UDdJdMnJnAYL9k9p6XHTu8Rs=,tag:WBx/YIjP1cZif0bssDKGVQ==,type:str]
    FLUXER_MEDIA_PROXY_SECRET_KEY: ENC[AES256_GCM,data:Sqkjum/d2wjm70acqfFUaB6+lYZl5iSDR8SAUGPda5ynDUrxbJsxAvBC7xuFvX3xClSFHUOUgZ6Iexi7AaWv2w==,iv:ZqEtH/KBZ3K4lmwk8TEgx3JvqrUe3v8+305FQK8n+Zo=,tag:VAVTnXxIl4ubsd0vRhpSNA==,type:str]
    FLUXER_MEDIA_PROXY_UPLOAD_RELAY_SECRET_BASE64: ENC[AES256_GCM,data:eBBzHUlY3O6isgQpAlKfoUhqB+M2ZgNhP0qdB2JqGr5dvgyiGEmwVy0XNt8=,iv:lAGiqqGhMHB998i0T5qCkrX1qo/z1QaSyxFGmt3Gl8E=,tag:8p3QA7v7BUugrOFLlxx+gA==,type:str]
    FLUXER_ADMIN_SECRET_KEY_BASE: ENC[AES256_GCM,data:BkSzo2wxgv4DbLlpUxsammVxc7kLoLmHbZS7sEo0mY2dVEXx+2jlsVLWEE739mTA7dOu8wzF0Ooq+3IhCk5Amw==,iv:AcUbGtX+7nnXWDIXeM8/p9JZX7bpfzXb1YaAcWzHlm0=,tag:7tqG3UAib7SQ4tnZsF7dyw==,type:str]
    FLUXER_ADMIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:bRFN0QWRHtSL419RVz8mLrS3IhaLk6hifODRDFM52sw3UwR/9+NfPbWlW9LD6tNhnY5QcV1B1aA4dbnU63qx6Q==,iv:lkIRFPQ6uoPCyQTLtTRzRifzsz3YNlY7Y8rD7/SXRmI=,tag:O8pKzwg7HcqR55hW8Z8t0Q==,type:str]
    FLUXER_VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:rX0lNExP5/3CBOJbD7Sdl9ZMi4IX7dqlP6d9hwkYgNevzVIQgw7OIiT5o5nOenjR265H0z2h4oKuJabVzzsZ2RGapU6LE/bpzqJSQDkv4gUsBqRy2NqV,iv:2gm3usLL+dQ8CblU5iXO/bj4V3Le5v9f+srWJOoSw5I=,tag:8MPa5QfABAWRfF3Vf/7u7A==,type:str]
    FLUXER_VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:rW3AgUmYpckIdWAZvPzG1BmSNHK8Qxh/60VoFV6FZGrtBuH5mfDDbnjGSw==,iv:BHy3iyNCgqeDbEhGOJ16AUHYSSybJgok6SqX4t0EW80=,tag:fGlKaksAiOlc43Y6Lyin7A==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:m0Vt2l41uYAFVyA8Hav71Oj4KvUJiXnTeIXFGXzcSWrn5G9++g3hzMRdKv/njGTIR5g+iAt8ZmOaiw8Mpjbaig==,iv:HrsMnr9OVbWCcRS7qk8UKTgUfF9H9Kn4AboAej+KbT8=,tag:13fA5Yc+oQeg0AAjl4ZssQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVWtDMWtGR1hSTDF0Q05k
            QitCUGlYa1VtS1dyUUFHQmFGa1ppMm55WmhBClF6cTVZMmVObkljY1VxNVlmdWFI
            Vy9zVjNaMWJHQllDYU9EVFNmZlQyZUEKLS0tIG1VTkJ6NjF0T0xKcVYxMXZlZHFG
            OVdrQzdFR2VqQVNWNWc2N0I0Uk1lU00KjSERD6hlVbJB1XrM/jrpZYWURBl7Eyf1
            seViz23NB1OuXN2cAk1Wd1WkfnOJGaIW7tADNiW6FvhjQym8bhub8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc2xNejRDSjQvZHNTc1Zp
            aWM1NHZIaTlTOTNtWjNqWXVkYjIzV1JxbFZvClA3WHZBZEF5dUNqVG9ObE10a3dm
            Smpvc01hZUZqZER4S2FPMndZUForcnMKLS0tIHVJVWQ5Q1pEOHczS3RTdkdKT01C
            ZWRTaFd2bW4vRVkzR2gzMDI2Z2hiWVEKJuP77/De3IDyloyqntCbdyVO4DJOO/Sz
            b2LRW3ggc7uLDgsXsCgRgaHJu+pVllOjTDgu85BzO5fXI/l12tUBwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U3dxbmVFZmRTcklsOWly
            ZEVXSEM1RHg3WTlWUURuMGgzUmNpR0tMTkhBCjZQcnljUzV2cEtIWUNoNDR4YUQ4
            RmpKaUVyRjlpaUR6eWNSTDBWMG9ya1EKLS0tIFZGdlR6V1ZOc01yOFJrczFNN0tv
            cHRncjBlUWUvUVZPTElSTXVhNE1ZYzQK4Gg9qs8ky90uqy284NvKfN18c/bl4yMG
            3O1je8z22IFRaNNDmXHB52ZhB/xx1Hcim+/b90Y2Xrvyi5S2+NPeGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-28T19:16:50Z"
    mac: ENC[AES256_GCM,data:ifNpjY7WpDYLid7aYwcz24lHp1Y+/2OywPXpNxlonJLW+KrIIKcnVHZcg9hm9O1aEGrMIDj85A2HuEYMeL9tiZxIOu9pPs1akz7Ny21JaFer/IA4AhaaTu2Pk2yexEZD2YoYR25LnUDZ9k2lSTWGQIszaFcl2ZVWyI/p+15mMdo=,iv:1fpgovvteuH2hZIQscbRcDXgKFaG7CfaE9EHap9R+ig=,tag:2lEYjSYq3BskjJLcXh3Huw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
