apiVersion: v1
kind: Secret
metadata:
    name: fluxer-secrets
    namespace: fluxer
type: Opaque
stringData:
    FLUXER_POSTGRES_PASSWORD: ENC[AES256_GCM,data:gaHz+2JVEsuN0SLzoF8wjw4qhipg7KphoqPCbqasU+j9ODR2kYZqs2pS3WNktS0bhyzFqjSK7ZYuNSgJGXDdXQ==,iv:WXjxYRNDN+sTi0DVxT1G+oWg3OwFdtZcPE2A13uT4aw=,tag:KNMl/dYse8XnU1FxHplWZw==,type:str]
    FLUXER_SEARCH_API_KEY: ENC[AES256_GCM,data:VeA2mcztKQZiLiTPWKp8vPNbc8IO5mKx1tpv24tUojAmMIjcPQo38BAwx9TYoAvQnx/dTZuUNiaYP9MZ/Hnt5w==,iv:494fwDpIC60+H5P+Ys3jyMYLCoCkKi+ilFmJ+xFrpTg=,tag:74Wn4ZaJ4MIEfrcTCXa9Uw==,type:str]
    FLUXER_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tkHVwDXiiKEfBYKigPrMpgT2nzZ097VkaP02OZYUgkGD0MwQ1HP0Q1DjwTS1A3LTAPsqZ0n/Dt2Z/5u6qb351Q==,iv:VaGDh4F5mUzcGY9IhsResAgoaPAIOfoi4bEk7Pyp/5Q=,tag:kaVsDLaCQzo90V7pjztc1w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UxYOwccSa2PN4j56m0pbrrd6c/EOH7P83yar0AqZ99eGVkn5082HIq/4yGQ/TAYl7W78skGzscEiWkU3uGQBYQ==,iv:rCnRswwJi1iIkjP/NgRZ+g9xewb1x2FprpIiYNXa75A=,tag:sW+zEFvqH9JIjRlVQ2GO/w==,type:str]
    FLUXER_SUDO_MODE_SECRET: ENC[AES256_GCM,data:L9T4cGkUK9P1XbOgyJahTaqy9ZCSGcHiA3cGi6Ej+6jCB0KL8fzX6mI1fEc3wC3pU8mhGbJ9D/VBXIwA4fk3jQ==,iv:Cd5sWxAISlJAWMvktBF9es8vSb+mPELO4XcLBBHwsec=,tag:7oQjzwm/9FjDa8ChaZlUCQ==,type:str]
    FLUXER_CONNECTION_INITIATION_SECRET: ENC[AES256_GCM,data:UHL9TWHYtbhxK9GFaxPYxaQDyACqhNVbGfgYEnFFRJHUBSSwHye37XYr1/PmLBUayEVWt5zBCnAf4ShDaBQKPA==,iv:iCjRI23f8lTy0xAQCgCAaKASRNsN3gM0QhHFyFvP8JY=,tag:owgaxavhgc19nN2FlKIUcQ==,type:str]
    FLUXER_GATEWAY_RPC_AUTH_TOKEN: ENC[AES256_GCM,data:EexPSqA/paUNn80WKQpOxpJfomK30Ti92NDg+SRWotSHECYlXUdGrz+sZpf9vhMX706jU4ecXjQwiS3S25rPZw==,iv:aZjE100XFNzi+mY4j+XZ18M55nrubXEdSoreyIq32QE=,tag:kOhKwwosaaC2LGq0nt19kg==,type:str]
    FLUXER_MEDIA_PROXY_SECRET_KEY: ENC[AES256_GCM,data:WME3flLn2nV702HL10wDH0NBzLFpZpAh9Du3ipRCOFNAA7ca3O3oEBQggkxzbNAU3v92HolWXHbvrJOlEMl98A==,iv:jNE4DzXc1PLUm7BkSk2UVO/Nop+55UFPFLuG63tmByY=,tag:rcZVRHtAhKWQZ54CLY0gqQ==,type:str]
    FLUXER_MEDIA_PROXY_UPLOAD_RELAY_SECRET_BASE64: ENC[AES256_GCM,data:fttzoiWqGgc4oHKTZXn0o+Q0T3COgaM/DhB0AaRVEpI+C7uE/2THgUMX4VQ=,iv:JtUPUVHAR65GoLfC38Lok1aj5FWKfuw5XXQFCur7kGQ=,tag:3qATlNa7xlouI816eh2yQw==,type:str]
    FLUXER_ADMIN_SECRET_KEY_BASE: ENC[AES256_GCM,data:9nFprlrGMAPSuYOQRsAZnNOtjyoEbifFgN82Bka9h3OurO4gAGxJSrQ5hKnKFf6/2GOeE+iKrxCwQCzth6GE8w==,iv:0CnQXdh2F05myEGu7xLUnaUo5Aed/tKIXbB2TpWBbY0=,tag:b0tR3eRpk5rR7NonPbt9OQ==,type:str]
    FLUXER_ADMIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XnkCsk3dadW1fjCBf03EHnLJj7yRYPDsWm5SCmVBjsj12CgV3YBvz8vHQNGP8dnq8ToOUfpvBofqhOzWcY/8GQ==,iv:UK0D2Z49KqbUz+SK9aUHduTAeqVC5z1BqE1AfSUMvEU=,tag:2Zb8TCvOB+gJp0L0GDaa+Q==,type:str]
    FLUXER_VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:P4ZV+FemVIzp27gJGcmt4dGin6XgKuADxH0iZAvUj5C5n3Wk1HT+QSGUfYqe7lx923wqouXqOj6esWz4AB0/m2GSiKAA58DG1HCvZgczyFh7dGctjoxy,iv:NRJBUF4iJAvzQ+LHguabmycwZ0wps26DaPGZzE8Fw9Y=,tag:Q8DfmFTwtnHwnwhN1wKreg==,type:str]
    FLUXER_VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:y88Wnatp/TYBZuP+LOqA422EiryREA1ooXS1LKYfgfIeb6lt5YeiHGNdDw==,iv:MI/UoGEMR/EBF/UzTkk6seASC+f8Ft5xp5NycmFFHjk=,tag:+aN4p/j7w9Dp3FdcC/r56Q==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:TGo4T4qsYiR6OHcz4kb1W3x9+MCYVvqEhGRN1iQyYQwb/4GSmCluCvmB9k1jeMU6bFjg2YS56319Dic+Ck8J5A==,iv:f8DfXDjjjkzv5xY1sXtFBYUKNjb7uX1njrkgj9JS0cE=,tag:Cl0nvQj63Gmi4xzbRKbHrA==,type:str]
    FLUXER_ERLANG_COOKIE: ENC[AES256_GCM,data:+9gnNqrjA4XC338xEzeVeFltKAQDHjs8DOGrNAIA6g4umQTJ2/gr7l8tVBwyw30CSqDS4Ooam9UdlfpqLgpowg==,iv:eFl8nNR2bUo7Re0VolEzyY1NgnA+VQX5jkOfzSuG3xA=,tag:wOs0CkWAkMiAleYzJHDBBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ2xuNEg1OVNGZGthbThl
            MGxBb081WUN4QkxxVTJQalR4WmQwK1VCVFdZCjNLbkNrVkd3NFBMUmVUM3BlREpM
            Ni9OcmVoQWNBQll1V0ZuaUVvSm55TVkKLS0tIHFjM2Nva2RYRnVDYVZyWTRrd1Mr
            a2E4UG0wbGhtQ2xrMUJYbkUxODFYVm8K9icVBl1ryn39+rOltxEQOH9ybsElTi/B
            hW28H+BzUMkACe/bh2fqW6wBQiOVd2vdW+zVlcE+FbrgAP09Z6irOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaGRCWXpLMTQvbnNqTXNE
            YVl4TTFFNTlGT2c5L1F6a1Rmc2hlbDFuY0JZCmhYSFNObGNjS2VpTGRGbmJSRk1a
            TzVyY21HOW54NkJZZUwrb2N3MjlPNEEKLS0tIHpOMVpBaUtxTE92aEt1c2JsNHBG
            ZGhzbEo3Qm5tTmRJZzl3WUIvNm1rSDgKFy6PF7AY6z1MoJ0cxNZjUQ9d+UtTpEjG
            vPmsdnUotxPMJ+7/HFi4cV61E3Q6U0Vrfa2KHnkCAH2dOt95O0zFfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUjdoTmV6dDBOc1ZPN2Fu
            VlFSZmhGa3BsWkdFRGdMVHdCMHh0Wlp5dFVvCmFRbnQrTW4xajJ3clE2MlBFUUZY
            WHNTNkxOQ3MrZldiSU9MVXFpUStrZkUKLS0tIFRKWWR1NDhQQnRTTWoweUxaTlJ6
            UFhRZkQyYTUrb2pzWGdGemp0bndQUjQKaUj2a/rMoycuAnND4MCLgUExnqKGtHKJ
            MDIGPSwp7nM6I/TmC1+WkLPi9acgSTabrpx3fv0yOXQy3ewVmdHLBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-11T01:09:16Z"
    mac: ENC[AES256_GCM,data:wPPKL94WrT3GO4vDPVcmcsQ6VOmlR8l0CX+erOXYaq02YTK2hA+wYZIdinBu09I2yrGIaD1zRgbcvkLXAY0T2WtGPPXw1V4S4if8xL7H3znNXLm1zlzf3zhf/7EYlu6NHdrUyQPjUSCJ4XuyElcayQ5xdCx6D8rxvaJj/O8S/zY=,iv:OZzPFRxMMB8ryW7b4BSrNt6kgIUCVpgk61dVOfgtH8g=,tag:vRgPDE32Fha7PBiIwD81TA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
