apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuwunel
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: tuwunel
      version: 0.1.x
      sourceRef:
        kind: HelmRepository
        name: tuwunel
      interval: 5m
  releaseName: tuwunel
  targetNamespace: tuwunel
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
            patch: |
              apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: any
                labels:
                  recurring-job-group.longhorn.io/trim: enabled
                  recurring-job-group.longhorn.io/snapshot: enabled
                  recurring-job-group.longhorn.io/backup: enabled
  valuesFrom:
    - kind: Secret
      name: tuwunel-app
      valuesKey: host
      targetPath: gitea.config.database.HOST
    - kind: Secret
      name: tuwunel-app
      valuesKey: dbname
      targetPath: gitea.config.database.NAME
    - kind: Secret
      name: tuwunel-app
      valuesKey: user
      targetPath: gitea.config.database.USER
    - kind: Secret
      name: tuwunel-app
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: tuwunel.sakul-flee.de
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - secretName: tuwunel-sakul-flee-de-tls
          hosts: [tuwunel.sakul-flee.de]
    persistence:
      data:
        enabled: true
        size: 4Gi
        storageClass: longhorn-replicated
    config:
      server_name: sakul-flee.de
      allow_registration: false
      allow_federation: true
      trusted_servers:
        - matrix.org
