apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "" # Empty backup target to get rid of the PVC creation warning, THERE IS NO BACKUP THEN THOUGH!
