---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: s3://longhorn@us-west-1/
  credentialSecret: longhorn-rustfs-credentials
  pollInterval: 300s
