apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k0s-controller
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    default:
      path: /var/lib/longhorn/
      allowScheduling: true
      storageReserved: 34359738368
    storage:
      path: /mnt/longhorn-data/
      allowScheduling: true
      storageReserved: 0

