apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-trim
  namespace: longhorn-system
spec:
  cron: 0 23 * * *
  task: filesystem-trim
  retain: 0
  concurrency: 3
  groups: [default, trim]
