---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-replicated
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: '2'
  fsType: ext4
