kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-replicated
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fsType: "ext4"
  reclaimPolicy: Retain
