apiVersion: v1
kind: Secret
metadata:
    name: cross-seed-config
    namespace: media
type: Opaque
stringData:
    config.js: ENC[AES256_GCM,data:tQWqhxXjxcOpwxpxdDoMmlXzdjxXSVrXH8pQEmFTS2+HvKA5+OtT7fCJoIYIh9A6FeVnuXMW5erwVMSh1hTicdEkatfho2bz2x8jImEVo29rqghYCv8mKWkLLU6m1zmujsGbLLFDTNV+/J1xr3dpzeh9d6GtsQBmnO+lsCpNxqXqksmS3z/hjcYs5W/1bjx4F+A+udCdVXtVkbt8bD/KXi0ExIyru6TkPNnpUVqHOjwx5lDXjfmMjdYQx3sPIFnxnFxbMSJCFFGC+OspuVcJyTsve+zOWIf6kRSCZnMlX6L65OdVIF2kf1xH36F2imSLtNjhdy8x7cUjyi+F42+6Z1gmLYT8/bjs,iv:/hy0CreKmk4fbn84/jHw0HDDkhCCxXENKRztl5rbXcg=,tag:3SyVULEMU7lSkpFcUXUiEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ1dqdE1CY0c0YWU3Uzd0
            SW9KcWxLVHB6WWFNd1lHTjZmU2tNQ3pyOHdNCndLQSs1NzJCUE5xT1VIdDdrY1lC
            bmxMN3BhaEtWOVQ1RzFnZzU5Yzl4UDQKLS0tIEJ6RG9McnZucERDNjYreUtFd3hm
            L3ZGMG83SkVqM1Vqc3RLalcwRS9RS0kKe/lCx6mX0Yp4gd5KtYLvpU5OIQwDzjgl
            Lkvv2p5IdSwxKH94/j1bQLzrC8wF1UXeIlU6G1icvb8Qd3qXK4xFCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OGE5TjlHTHdubFNEY3h2
            WWZvZzhweDdjamZBNVlXRWY4NVFwbWo4bWxFClJtbGVXbnFrSUlRMmhYQzlFNUNh
            U0FSTm9zaVF1c2RrL0tmeE03TUNRQmsKLS0tIGUrQnJvd0xOOEg3VjRJVlk4eUVw
            ZXRsejA0bEZtdDZOcWpBNFFiNWxlWlEKaAsBapZt4rkzSnH7kHaG2H1dvoZWjDFn
            WPrp6SshUJgmE0tRyb7e5aqQKGqJBDTHjnV/JbLIql7kBB8YlVIMkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza1F3UW8ya2c2TnkxQzFX
            TWd0SlpGVUFuMzNWb3hsQzlUY1haR3pvZFFvCjgzZWNueXJwQ041SVFnWUNYSXlh
            dUxWeTlqOVI1WElDMG54WFp6WTVMSTgKLS0tIE1lQ3dYSGJSaEprcG5SN0oraGJQ
            eUpVQ2hDWko5T3JDSUM2U3o4cVFubUEKwGv8JnPRt545F6t9bDnGaPg0U3HvwrEO
            Uy5/4Wd+ZhNqWvQsduTXKPQdY/8P5JwNrVBiZkG4yt6JikE9XrRr/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-23T18:47:40Z"
    mac: ENC[AES256_GCM,data:rCp2B675o2/BukVTbQfzl557yMGW66DeIh0HRnwZCtR0FUSXQ5ix+9iQEgzTjCJKNvtQxaKhCHOTzUz1OLWKK8+E73A2eCq6qzGUMPHZFriI7xjbA466+CvzCHwLeBAR1S+ZcLK+5bak1WJfTV92oMkpdZpQgVrnpqLZVMmRx/g=,iv:N95YfQgEa4L2TXBS1zO5kAgBu5nMW4+CbhXSxjlzC3U=,tag:PJFlG7pXbh1fKAIc207O5A==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
