FROM docker.io/eclipse-temurin:25

# Minecraft Java
EXPOSE 25565/tcp 
# Minecraft Bedrock
EXPOSE 19132/udp 
# BlueMap
EXPOSE 8100/tcp  

# Dependencies & Updates
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
  sqlite3 \
  libsqljet-java \
  libxerial-sqlite-jdbc-java

# Server directory
RUN mkdir /app

# Server file
copy server.jar /paper.jar

# Plugins
COPY plugins /plugins

# Entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["sh", "/entrypoint.sh"]
