FROM docker.io/eclipse-temurin:24

ARG MINECRAFT_VERSION="1.21.7"
ARG PAPER_BUILD="17"

EXPOSE 25565/tcp
EXPOSE 19132/udp
EXPOSE 8100/tcp

# Dependencies & Updates
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
  curl \
  sqlite3 \
  libsqljet-java \
  libxerial-sqlite-jdbc-java

# Server
RUN mkdir /app
RUN curl -L -o /paper.jar https://api.papermc.io/v2/projects/paper/versions/${MINECRAFT_VERSION}/builds/${PAPER_BUILD}/downloads/paper-${MINECRAFT_VERSION}-${PAPER_BUILD}.jar

# Plugins
COPY plugins /plugins

# Entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["sh", "/entrypoint.sh"]
