apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: open-webui
type: Opaque
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:Um/Q/1Th66DPb7IojXOXiAkRcsx8pQalVsyVXMKh08bD0iLMtUFdCqXRphAO1S0/OpZqwSlhUncfEzO5fmmvgw==,iv:fLLLO9c2OMSNtaDInl/NZCovR3OUimQsEQDNhlwhu6w=,tag:F0kC+65DdvIPXfB+ARSE/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGNieVBabm9XcUV6c2s5
            bjg1c3ZMV3RIejlaVGRZOWlTS2M0eTROeFZzCksvM3M1MUkzaHQrZ1U2YS9UUlBG
            NjFSUlAyc2Z3OTNNTDlJOVNzb0FBc0EKLS0tIHV5YTZ2enk4R0lwWVlHckhJN0Nt
            SFc1aUZBSGU4MWhEWU5SUlhtb284ZmcKgC3vM/6QmPLNfYy+7dU7K8rOMjRh1VpL
            UPHTjkOKWNgxdjUe4bIcp8EZ6nP8hXaSRdV/28Dy+n44wfkaMnUcxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNUFxNGZFdVdZbjQ1ank2
            RnE2U2hIWC9zYm9WbXhwZ3dIY3lBRHRKb25FCjI2R3NhOTVVQ2ZxWEpxUVUybmQv
            Y1F0Q0ttTGc4Vzc5M2U4cVRFdEo1ZjAKLS0tIDZ0Z3FhM3JkeDBmRSs1RWlLakRp
            cVJteFd2aWg5cFlnUCtidVdGVkFxWVUKBx/Z/3wvVU4sUzfEMs0W8DFLMmlzZCcZ
            ElTQfcoNNNbPvo+ch3A+6x0EeROEb5wl/tys2faNM9OAQedfhIsJNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL1pZemc2YmlMSmNTQldh
            NlFGc01uV3dBYWhEWXNoRVBzV2tqazRQcVhjCkliclVRUjlRa0xETzc3cC9xWXB4
            UmhjQmpxdWNUcUxINVBqQlZMNERGWTAKLS0tIHhpSWE0VGtmVFhUWWJYYnljMkhC
            dTVESDRFbjk3QTAxa09rV0dyU2NiM2sKeoPwwgXWYSYe3OJdybFsYJi2osH2jfgN
            Bs63WflY714fVRCv5nhPxs17dTmqJpGrfmD/cIuHZ0gznGRJOhhjNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-27T18:02:44Z"
    mac: ENC[AES256_GCM,data:h918TUM2FSMnhlzqkGFF/TQEPl9b4AXaDFOM3rQMGMePORJvWcSYen3CBmK4CBCgHJDs+6FztjlIDth3F5BxSY1BgvUTs/Ga0lwX+tJrVAITtm7Efg1LnlQTpnKGXISdCPDFqIPEh/bE5iaO+a3inYbdVTIHbHnvBWmpJjf3TcA=,iv:afnhge3E0meUv8qfQMStbD6z//lMWiEMatl3lPVWgoU=,tag:8GdnryhZ7KCBwEilgoAwFg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
