apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet 
      name: minecraft
    patch:
      - op: remove
        path: /spec/replicas
