apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: media
spec:
  storageClass: longhorn-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
