apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: sonarr
          persistentVolumeClaim:
            claimName: sonarr
        - name: media
          hostPath:
            path: /mnt/nas/Media
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 7878
          volumeMounts:
            - name: sonarr
              mountPath: /config
            - name: media
              mountPath: /mnt/nas/Media
