apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-access-server-data
  namespace: wireguard
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
