apiVersion: v1
kind: Service
metadata:
  name: bitmagnet-postgres
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: bitmagnet-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
