apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitmagnet-postgres
  namespace: media
spec:
  storageClassName: local-path-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
