apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: cloudflare-ddns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:II/rT/HByrEbPoLXB7xcFKJz5MtHrmCJ17oAYbZp0SFref3CfmfKwxWkAbC9bfJvd9MC/hc=,iv:rODNQTg9TGENrPxWAL3Mn/nmY3/cOe8aGvXGcgASuWo=,tag:Z3vYxoXtYRHd2Tu8LdAs+Q==,type:str]
    zone-id: ENC[AES256_GCM,data:hkXdOtMfLGkb9udRI1KDISmmDC7g1r4WVmrtWLc5Nlw=,iv:Rxw5bfXJuWTeoZHSy/ATdSlknHK5jmLadj8mWgbSsqY=,tag:AZvxurlIHPyDRg8lfni3qw==,type:str]
    domains: ENC[AES256_GCM,data:tXjmSDDKqafjxgr6Eg==,iv:C4dALecR18DswvVC/mdJnwuROuMTNkUTxf+FHxA5KCw=,tag:VEf1dayRxKKxiDJ75CTE3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTkNoV1I3M0syNDRPQ09K
            UW93dVQxYXY2VHZ4eTBFbk40aEhnV1FaQWl3CnpJanZxalNmTXR1aUE2VUZBQy8v
            L2JjTlQ2Y3gxOTZzbDVqQmtOa1V5T00KLS0tIFFnTHczVzF4U3VPZlZMdkMvMUpl
            Q2JFODBUM3RFcVZMZnR2bzJ1MWtzdGcK/s/BA/lPuJw8VbdReZRafYNx6EtUP/yo
            Noa5DlQ9TAWLcGef3UcfAqXc3xD+2zoUjubiUQMIDglij0ptOi5E/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RGY5VWF2bzNRMWdXTlV3
            UUR1U2IxU1dUekVwenN4MTg4YUJ2Nm1tY2dNCitNV3ZsdWh4V0c0N3VFNFdIRnNa
            YmFJWjU5R3V1NFdiY3hoV0NMOExPd2MKLS0tIGJlcjJoS3BoUFBUNFZyN0ZZMDl1
            MVhwUzMwaVdHV28rUUo4ZG43MHBnclEKQ+ueq1bz2NmLz1NiTa+DuujJPtJpZTms
            HyBt8OXBrBpMt5x9MeTZEB50b+qRDq/FWPMcCpnQUS+CgTSwH4HGBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VEVJNTZJNWR3T0FUWFRZ
            TGlhRmZ0TE0zWjlXdjR3ZFN6aFBRdk94UjBrCktZMTlnaDIrVzZjLzNtbmVYRW5G
            azd4SERyZUtyWjVGTU44dmJlMWw3NFkKLS0tIDRzMDFiTWVGbjVpVWtUNlcrM3R4
            Z3M3c2xjOHN2M3grMkFVMVBocENCZWMKTecqMHOhWPrdPMhYLoqZyE2duL8LhNyA
            rO8QBxMEaTaxqwedzD4Z42R3prml8RAIyCt2jxPc5Mtp8kyBnoGHuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T23:20:47Z"
    mac: ENC[AES256_GCM,data:aFqxEgfPiJ0FJaIKZadTpuZDExAWA6PBfy8Ubqgwqe6+8lHyBEz+g5kUB/e8+Tni8AbF9/HfnLS/CxYmIseVBH+Nvlg+RfZxMA+xlWX3vLLPBOaXs4WdEadVXHTywEEog7+sSVWNiQqa3/GWxFtw3r17C8hPdIt6/moWxk1tLUE=,iv:tni5CNfu94rumsBzw9kOWYHMQ7saxyaQDTEmRyMvXOY=,tag:A2G8ZPU0vird9x+X6wcYeA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
