apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo
  releaseName: forgejo
  targetNamespace: forgejo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
    
    gitea:
      config:
        indexer:
          REPO_INDEXER_ENABLED: true  
      additionalConfigSources:
      - secret:
        secretName: forgejo-postgres-app
      admin:
        existingSecret: forgejo-secret
      signing:
        enabled: true
      metrics:
        enabled: true
      íngress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - forgejo.sakul-flee.de
        tls:
          - secretName: forgejo-sakul-flee-de-tls
            hosts:
            - forgejo.sakul-flee.de
