apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo
  releaseName: forgejo
  targetNamespace: forgejo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
    
    gitea:
      config:
        indexer:
          REPO_INDEXER_ENABLED: true
        cache:
          ADAPTER: redis
          INTERVAL: 60
          HOST: redis://:$(REDIS_PASSWORD)@forgejo-redis-master:6379
        queue:
          TYPE: redis
          CONN_STR: redis://:$(REDIS_PASSWORD)@forgejo-redis-master:6379
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://:$(REDIS_PASSWORD)@forgejo-redis-master:6379
        "cron.task.queue":
          TYPE: redis
          CONN_STR: redis://:$(REDIS_PASSWORD)@forgejo-redis-master:6379
      additionalConfigSources:
      - secret:
        secretName: forgejo-postgres-app
      admin:
        existingSecret: forgejo-secret
      metrics:
        enabled: true
      environment:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forgejo-redis
              key: redis-password
    
    signing:
      enabled: true     
      existingSecret: forgejo-gpg-secret
  
    ingress:
      enabled: true
      className: traefik
      annotations: 
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: forgejo.sakul-flee.de
        paths:
          - path: /
            pathType: Prefix
            port: http
      tls:
       - secretName: forgejo-sakul-flee-de-tls
         hosts:
           - forgejo.sakul-flee.de
