---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo
  releaseName: forgejo
  targetNamespace: forgejo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  values:
    # Upgrade strategy
    strategy:
      type: Recreate
    # Persistence
    persistence:
      enabled: true
      storageClass: longhorn-replicated
      size: 12Gi
    gitea:
      additionalConfigSources:
        - secret:
          secretName: forgejo-postgres-app
      additionalConfigFromEnvs:
        - name: FORGEJO__MAILER__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-mailer
              key: password
      # Admin user
      admin:
        existingSecret: forgejo-secret
      # Additional config
      config:
        admin:
          DEFAULT_EMAIL_NOTIFICATIONS: enabled
          DISABLE_REGULAR_ORG_CREATION: true
          SEND_NOTIFICATION_EMAIL_ON_NEW_USER: true
        service:
          REGISTER_EMAIL_CONFIRM: true
          DISABLE_REGISTRATION: false
          ENABLE_NOTIFY_MAIL: true
        repository:
          MAX_CREATION_LIMIT: 0
        mailer:
          ENABLED: true
          PROTOCOL: smtps
          SMTP_ADDR: smtp.purelymail.com
          SMTP_PORT: 465
          USER: dev@sakul-flee.de
          FROM: forgejo@sakul-flee.de
    # GPG signing support
    signing:
      enabled: true
      existingSecret: forgejo-gpg-secret
    # Ingress
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: forgejo.sakul-flee.de
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - secretName: forgejo-sakul-flee-de-tls
          hosts: [forgejo.sakul-flee.de]
    # Service
    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: NodePort
        port: 22
        nodePort: 32222
