apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-redis
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: redis
  releaseName: forgejo-redis
  targetNamespace: forgejo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    architecture: replication
    replicaCount: 3
    sentinel:
      enabled: false
    auth:
      enabled: true
    persistence:
      # Redis is only used for e.g. file locks, sessions, etc.
      # We do not need to store this information across restarts!
      enabled: false 
