---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mc-router
  namespace: flux-system
spec:
  interval: 30m0s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: mc-router
  timeout: 3m0s
  wait: true
  path: ./apps/mc-router/
