apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx 
  namespace: default 
spec:
  interval: 30m0s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
  targetNamespace: default
  timeout: 3m0s
  wait: true
  path: ./apps/nginx/
