apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-enterprise-operator
  namespace: flux-system
spec:
  interval: 30m0s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
  targetNamespace: redis-enterprise-operator
  timeout: 3m0s
  wait: true
  path: ./apps/redis-enterprise-operator/
