apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
spec:
  storageClassName: local-path-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
