apiVersion: v1
kind: Secret
metadata:
    name: notification-provider-telegram
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:eeWZmc3PBNxG76ml6gDu82ShvLDjNanVqbvy9ctjW46XvjkQob/jz/Iw0LHSjA==,iv:npbh8XCkHUJEGWn5jufX/0Lt2bT1XGI4DWjymZeXz10=,tag:bcazbdOkndbqVFGzrcwVYw==,type:str]
    chat-id: ENC[AES256_GCM,data:vVkcv5Res+VwVQ==,iv:qscTf/XSXg1JZYZS6HN8wli4B5EpgfUH7NPb+XDGXEw=,tag:nEcT1MHTsSBT+bFkkHdWgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbjRiMU1DdnZ6aloraEIy
            SjR4dDdGUjZpTjRGNTM3L2dxWEVpdVNVNVNVClNqMThZTUJOZVNVeXVmOGE1d2J0
            VXVkQXp4M1hSMnpOaEMvQ3lreU8vMnMKLS0tIFNjQlRwc2REL0hBTzJKalZWV1Uw
            cTVCYmNHUE5ZZU5WVTRLZjFTUWVqWEkKclJp68NIAcWd/PnS8NQatUkX304AbybO
            oh+fIFNIBfvyvgS4AR2a4C/lfEcD9bHfUax9ofF/9soJIHdPR0GFuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWjBvdmJxVndIQkllZDJB
            RHdEc2RHOXBrNWNaSkhvZ3orUHduNmFZVG53CkdyT2NpQmdrT3ByaWMzWlhZZUVo
            VDBUemtGODdmWXA5MjYza0U0Tjkydk0KLS0tIFJsSUZra2xEdDc2TnAzdzVDS2ZE
            Vk1OdGhyTWFqN1VBNnlaS3FLNk9pVWsKwk7BdOorb+ldrUGZVv+pw+9v++xwT2gH
            6z846mSAc3XG5tzupLKpBhwgtsOgoq9Rn0fpj8DBphMhcZYQ4REtXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN24xbEhUeDJ5MndiMTE0
            Q3AwRlFveU9HSWFsREdaQy9tQzUxa0V6OVd3CmdLdDl6M0dUaGd3YjU1bDA1Z3lv
            QkRBeFZmdGxIM1NucWRiWFNqVDk3dmsKLS0tIEJtdGR1NnRHUStObTJEYW03MnBq
            aGZ0Y1N4Z283MGdSV3JieDY0WGpuN3cKriB5UFXxpQCHMi8eQ5PlJgQ+BftFQLgC
            SXoHY6DHrwbW3LTsTnChckYOHaBDvpm8kRXYqJcUgRLnIiGK0kQ+Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-24T22:26:33Z"
    mac: ENC[AES256_GCM,data:YSMtlr7qzFblI2L+cASnCeJJexq98bgk4Yksw4pGlsvx7OgOYj273Y4zF28dJaBt1ZHwNlcoCjHZPSn6gnESrAr/L0vXSvPCGGofe/4Dx6BcUoEB+baS0HIr7YklkHeOxhmH+88sXi1zUAw8bZW0PKQbRcne/nRJ4QF7r8QgXmA=,iv:cMA1lox+3qobvNDXTpt3bUwfsvYqOmykfgRYaPrJl6s=,tag:QgHeQIKYiZ0wT8fhNkqRwQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
