apiVersion: v1
kind: Secret
metadata:
    name: woodpecker-forgejo-auth
    namespace: woodpecker
type: Opaque
stringData:
    client: ENC[AES256_GCM,data:oh5wkV3K0VKwUDHFtQFDgLFXK7eq2atEVIMHFck7GXpXYA6F,iv:avePZJtCaIrRa9MMdIDFOhRsHcwHBxr8g3SW1NYGg+A=,tag:sp2lTwLLzPJ+1QahsGAGqQ==,type:str]
    secret: ENC[AES256_GCM,data:ScxnWLxVyeh4kOaq8Kyu18m9t+LXYgLcdElPaIFuC/6fuMky7BjlvtCaQPESQAcaXjOKa8/NTOo=,iv:PIy2kbVgieib3waPZ0pBplp1IJwy1XzboGlZt/JpGRI=,tag:LzUvjwICGAhdMmHCHsM43w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdzBWZlhoYmVZRmxWbTg0
            N0p5ejlNN1c1NFE0b0drQ3FmUXQ5aWplMHhrCnNBQ1d6ME1va3FSd2xMTUphckl3
            aFU5RERIZlNFY1EvZVNSY1BrbUpWREUKLS0tIDNwMVNRdDhiR2Jtby95YlI4TCth
            ZE9iZy9sNUUvZmwxcTNSdnZiK3h4RXMKJ4eG1TXRsFQdrjCJolGV7tXK8mFL+VLh
            ETQEjp/lgPuqje+m8b0G9MIwYgv+8WeZV8hafbudrATxqMXuXJeLtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTkE5cWlYR1NGeGsySWht
            QnYrUzJXN3NvaHl6Y0RFSWZycmxJRktuOGs4Cjk2UTZDemtEb05SRUd6SjZ6RzZ6
            TmVFMlZzeE1GSGNleW5vL3lXTUVmUzgKLS0tIHJ1OEUrckdBemVnSmdDRGlEUStJ
            YjFGY05QV1NIVW52NnZCK3dTdTZGcUEKIqY8gYtUD8hdFjAuoMbO2IsztseTGwUP
            UhcNW5XdxYPCWxC9TpEYXNJXkFS032ofWx0kaM5+W3iqvJd1cGeZ7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNUs2RGNVWnNVMTJQMXZW
            L3VYYy8vS1BmazF0VDlUVmhMWXJSaVUvWVY4CnY3U3htUW0rcUVTM3JGQzdCN1Ix
            c1lJR2FZbEl0aEFwNFNESnQrU1dpWFEKLS0tIDVibTlLZUhTd0lnN1c0eGpaemwv
            L2VLZFIzYWs3eFViblNHQTZUMUNqVE0KuxY17BLcj+4arCCYEUMoP32EZti3OlHg
            wkkajmdCpNGh0Fzb96RC9DDZ1vFQdxUBu62Kb/yh5CnsDONL6eEJZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-24T22:27:13Z"
    mac: ENC[AES256_GCM,data:/XG6Vy4WIHK6/wsfKVqnCo8LL6PvMiscHyh/757Rv0lHTY82CowsHSV7Ny97gD2u2PJfiB34deS3JwTFIudNpeh49PZv4T5Wa+pFCMCTKZ82Zg50HpuQmWcU9OWsXn2QeDyO9XoPOcZqGbPyzUJ0g5/9GWu8+oJBOts6q1Q1dig=,iv:s2TV32cK+BeiJhd01aqIXaBxGn2sEKX/F1GGcKeBFcY=,tag:S0dQ+InOXn3vHBkA0RWWUA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
