- community.general.docker_container:
    name: website
    image: forgejo.sakul-flee.de/sakulflee/website:latest
    state: started
    pull: always
    restart_policy: always
    published_ports:
      - "80:80"

