apiVersion: v1
kind: Secret
metadata:
    name: wg-access-server-secrets
    namespace: wireguard
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:hYnGCr1EgMR5h4UdB+QA/XWE3i4Kp3QLPZXAJdvI,iv:fEGdRs6Ie1fiYvtYiUy3jKI0ow2L98br4g2I8iyFjBQ=,tag:etfPB0qC5WEM4glp5WqTvw==,type:str]
    wireguard-private-key: ENC[AES256_GCM,data:FZiGXEJ5n284K3/o/MA+8jYe4y9Ps1+Hb2sKEMaMf/VgACbJnHfCaeD1YXs=,iv:YHllTLB3XxyWwMQveJlYCfDQHrdOzvKx6pxvqrkeYCo=,tag:JpuPkgXcmpN/nMfdRDZLZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSVVEV2Y2Q2NxMTlxQTA3
            UUY5cTNYZElOeEZvQ3RyeU82WEcyc3RNTjJjCmRLdVg1S3N4ak9IWHN6c1VKT04x
            clYxc0l1c2dMdUxLVEVUMjlobVFTU2sKLS0tIDVVU2txcEFiY2YxTWtyYTMxSlVq
            dG1QK29WRXBla2VvQlBYZjRjdkNVd0kKU8y2uDYYyfhk47kSIDIDrk0NQ6XsqqV8
            MrTOQ032QEIvEonkwdHCgHCkgw1qboFUGIvKx5BhXdcpKxe6xr2uIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NHBYbVlZSHZkVGcwV0Vh
            UFZUMHVzNkZJSjh6NnFnRzdTakoxYlJlVmxNClZjb2hFckFqcXBFMlpPY0ZGN2pt
            V3k1M1JXd3VBQitaV0dzRGE1Zm03Q1EKLS0tIElzK3FnOU5VemxQUys5WkRpQmVH
            YWszSTBURUFCUGI3SnZFZUtXL1NiYzQKp2pE3QAxohogKVTugmYa216Od1SljeZN
            xpkE+c5WJRzSAy6LDOki1ucxkta4wjz+eTYVdYKK5+jPwxzJaicrYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMjFlV1ZpVXRyMTNoa2lB
            Y2dHeEFQS1E0UjdHTDl5ejRiSHkyTTlaWHprCmRXZE41SHJaMFg5THV0NVhhMWU5
            bmFCMlNWZkJMZlNGVGJuSGJEb250ancKLS0tIHFTVnFTSHp6NFVJam4yUTBsRU5P
            ZXdnTXhlMjYwanZEUVUraFFzeTB1ckUKW0BAZXGGW5x6i2ohkEMDi5pnKxcBIPb9
            i/1r/HepGO25uX8tPYzV5Y3M7DDKI3Fc4uRDfUb3WeM8zVNwydBpjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-23T21:47:37Z"
    mac: ENC[AES256_GCM,data:3RssD31IpZWDLPOCcM71Ei9MvnA2z/TASf8bW94BnGfm3IFbm/Cz1G5j5ic5qdwlw6uVa/78+SfwvGxlld0p/kzxd+pZqIKd4AI+qUNvaF5v+BrmYkQgWID+5PfwisWHzhMjefwxqZ2CSaH0GAr/fhBtR1j0BhHsmoLT0rzO1Rc=,iv:pE5XuXGXtGAMhLKX7vSsH35azBBH+tV9N8eGofnJ3jg=,tag:iU7FKDTiHPC+UcLjU9DiFg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
