apiVersion: v1
kind: Secret
metadata:
    name: subnet-router-auth
    namespace: headscale
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:+EEnPVVsbowGs9CAUYL+wt8TDXFGFUIv08SIxSYo9YM5+fCkqZlvK6/Q0yp0JVpamwct+CnCo/Aco18mfBhzOR6gtM+3kVd/LpgWF6O37BipKnPs35Ifpg==,iv:MM9gSVxvI2/VNMPqlsTcdl0dfpt6mdq6fSw2gqGnSG0=,tag:IJ6/g02Aj3EQdlRzYmVTuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjczl2aDR1WVdQa2tNWUgv
            eTlNTXIrblozL3VINFdmeEYyalYzMWtUUVFBCk1DZGl5dHhVaGxZbFhkTjhvc0sx
            aHFLM0VZNG5NRHhvYklPVTh5RVpPU0UKLS0tIGxpbkxkVEk0Q2xuVzhjaDI5SENY
            N3Mrc2NRY2I3YUhhbnY4bjd2QjY5VGsK8Uozq6PTIqJLCDIfY2Vw0LNDj195IDRh
            fpODzfyPW+O8+hAY0RzpK85Da8QIGTEiDmdkR9NPbuXaV6e6uFgXGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSGxRSmVLZ0VYVnFlQ1Ns
            dS9TakFkSG5LTDE2L2xxclZTdXdBVzEwZGh3CmdWNGpnb21yVnNLS0IvQWdaUy9a
            SUtCVWZKTXN1dGpkSTdyNmd2YmZkUkUKLS0tIDZXQ0ZFaUhRS3pscG44N3NMTGlo
            WXQ4MlpaUi9rV2QxRlE3UTBMTCsyYmsKYza8Zjkdsq8Ui7h9n0ED6jDzaJJ6/GLj
            BKhVl029H/HnrrJRScf+pYECDYGyBwy0LmPHbTpTbQFTrV6CRa9Nkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTENIcG83dEd3UEpYMHph
            d2VtVHlZMWxFUjRxb3kvZmxSdWdSM29iSVZnCmtySnlDenpkNDU4UFlxSEpCN3Uw
            WERpc0F3eTkraGNZamQ3cEI4djBPWmcKLS0tIDNWOVdxcnZndm1iNWtJWXp4UXlj
            U2o5cUVudGhmdkRZRzlsbmdoeWlRWFkK6hDHBKvkB/KIt+3IXU0UBxvmhF7QAKvg
            fCgXcsyyM8jBudPaYv0Qil/RYyaFF5SCNnQ6D6s4K9CSkyuVum6lxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T19:43:23Z"
    mac: ENC[AES256_GCM,data:QTphbdZGUmhOY4inAPBZjiiyovztBBH2+QTTG8JlefFyWRNQLuFvMXrtKie99D+3wSLIW5Gr212eTjvnRv1wSKWHBlt1ijcJou5Cli94ugWQUJVIS6CMAuWTm7y11gm7KmrENkPuYcyM2ZNnaDmP16e7uJmZ0tmAEoJYlxYeoJw=,iv:369VmGtOb8E2M9LdamEKpTBnAlQSdIeqj0H4SwE3EvY=,tag:DynAjhpLaHtref3mflOJBQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
