apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:H/PE9JlBj9RuaUB/jVZDaqnseolc2MuFTjI0GNjnqlfBmm5QP3gu9bnfl7qX1eAmYt+RKdKnKGXMrDTKpAwZHA==,iv:fz/PZdFoN6IOMNKQONQf71cxl3w4b7nlGNWkOMT6OOI=,tag:jNZhGUG5q9I6H6tY1u2Biw==,type:str]
    HERMES_WEBUI_PASSWORD: ENC[AES256_GCM,data:NgwW6MBCMtiKft03EpQlij5k1ZOfTVfk,iv:SjOPlXbRYq4CXSY2lF2GSuF59XIIIFtTx5i0DtFS7fU=,tag:MuV1gnfprdiQg043JE6nCg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:9PRvL24n,iv:E9jUJ+fSyViUSaSb0ploJLj/GTG6Ox+ZRNKcPyVz5IU=,tag:ol3Ytp1B+Ew6Z3ixHb9yXg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:hxsoMWB9rv2B4CUz33Vnz8i+0QoibVYt,iv:Ua7gmExUsE2AkHjodOqFd+a8+UXAgxE932NBaoXxDEk=,tag:lLv0eNjkyFyKf+Ierke7kg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:JIoo30dF3lCW2e2D95E9aFHJZB7O37rfrfUOYhPnkyY0pfFZ9XOixeK524OFAYMhlQu0mn+KAobOu1WBM2g0cw==,iv:1u6MEh+DlDl4a70+QvU2P9/LnH10QBWd7+g94hDZ+EM=,tag:eJj/kYqGAlQQ6R8+RgPLhA==,type:str]
    UNSLOTH_API_KEY: ENC[AES256_GCM,data:smBygQQfr4UJDA==,iv:ykKxG0KyFMETr5eGLdPG/NNtJU3jLBFC01h+DKVS8MI=,tag:bVWdoPhxIAoFHAE2rjzK/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmc1c1hRM1hmeHI2elRk
            cDBMeXY5UmZwY243bWhKSU1TQmZoYUdaRVVRClU3dFJaVlloRUZXdVM3czkyVGdY
            eUszUklrbDhuR1Y3YUhGbnJadmNjRDQKLS0tIEVFbmFoczdvcW1IN0pYNVdGQXNy
            bjBoT3JSRnk2K0VFd3FWRlpkNGYyUzQK456q8bboRZRkRAGwb21cpF8vDqlRfwtK
            Kdo5pEY4W/qLXwIGyo7qIE9cQTeH1yxeVh3WC2fij4HkIKs+VxvKMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU05ETjNWRUNiOEFpd0M1
            REZJQWEvY25ka1JQRFBDSWNuVWpIUDNIaVdNCjN5YWhDcEpUcUFsbC9NbTU3OUVP
            RDFiVXpPSDJPTko3WVV2cVQrYkViL0kKLS0tIGgwVzhONENuM0M0TkJpakVlMlhR
            M3pSUExoekFLT0pGcU9zSTNHWGorNHcKVYDLZAVJAxdsxS4n2eeym6nY3Euv7lPf
            Ak8k/1WE0G6VaLdsNipAIREV9whKtXPhuY66v96tZ3lof9yMwC9Bqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZGh3RmY3YWlHdzcvR0RV
            cE1GbXhEUHRiZS8ybzhQUjB1WnhUNC9CZ1dRCkkrT2d0TDl4M1hndHAzSG9TTms5
            aVRDcVZRZmFpVUNUa0Y0bElTL2xSRDQKLS0tIDRYYllCREU4cnVtNmZubWlSeWZn
            NXc3RldZYUdkdzdhMFpkSklRa0I0aGcKFma3xlCG6jO3l/E7T3sHOW3vnPUmM/3b
            4Ioz9BYFK9qLThGw/7ukTctKvseQcG8rVP6LBKX09xm0jUvwy87NIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-24T20:53:50Z"
    mac: ENC[AES256_GCM,data:0L6Ch8cardSVv/EtLregISTaNMAp6p8scUSNE3uT9KFHVNxkvfl9jtGCQ2aOzsIfnbgo4dDZf2MQRIspt9UPE38BJCxFaTv8+GhSZeeOlSFPLPAUaUB2d2ejvFzWqj1I2yw6ZEzgJSq+nZCyHmTsbvmg9hbTuYr9tvNTWxsargo=,iv:CSlAk2NjFLCsG9E49ZlOH2O934U05a8kSsI9ZhrOelg=,tag:uWz84WW4yRF3h0/Se7tkTg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
