apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:7PdtPmPK9oULz/By8T+xo1uXB0lItUjjKei0DIT9Vm0h3m9AXh1JxgIKUiETiFhrNVWbwsjz2AXYBSytLv/ilA==,iv:0XU6umUD/LumhuJ34KTkSXqSp8maXo4oYiZct60oeDY=,tag:nY96kjVrLmi5vl6ZkE+DpA==,type:str]
    HERMES_WEBUI_PASSWORD: ENC[AES256_GCM,data:7eCrt7fFLSUots5moRWDOaUFKQkyw8qC,iv:7D0C1pXAruBTHiDtZ5pOB5ykiFveVX3bw+ZHR9mM61o=,tag:ej8iiaIJhUdDlreArRqTfg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:41pTGzri,iv:sRWF0j+683m8oCtCqN+d5kAQrDGvG/x27L/bSI8vGGs=,tag:ukP+6t8iO3ChTY6J0Se7kw==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:NeMiFb+14ruDBiQsY4ZPFdQR64GNDf2K,iv:x6dIWn52+reVQ7GL4dkJ4QV8+TnuGKGWLBJDNYjzFFA=,tag:+66xr/DrnoI9k0F/rsIhlQ==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:xnqVjCNkC3R1FV79lRgbBZJgTdGR0rclTIxEs0IZu477SQU5LYOxD/NiJl88/EE6KIY+I0LSuTIzmOzghkUCvw==,iv:1lzt60H8XVgQkEIIQagQWQY3qysx5BhDaeoK9jL79hw=,tag:xQe02aPSo/f84LWa4sJRbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWVMMUNMUUxMNGxZMzFy
            TURPWU9JMTIwaEczbHpTeVlXak1NNEtFSVdZCkhPZERMY3J6RkJ6K3RDQjZIUCtP
            UGpWMFJDQk55c0lubDRiQlloR0NRbkUKLS0tIG5IVDQxM2NjZGlhTml3eE9UNG8z
            QXlTcHlmWjUzeEVUb3U1bXVyanRpK0kKaXMn/4Oh7CG38RUEKcBQZKap8mVoz5bs
            dteaC7s2FAef3C/QMjxcKGATzn3cS7TVhvJ84AANYOyIT2+NzF+IAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eENGQlI5YWNIZGtFbkdw
            T1laaHFEcFlaL1FLOHNldHBIVnBmcjZDRVFVCmZaSmZLQUxCeTBZTTdNSlhseUxW
            Zk5peEdWMFRGMjhXZ0Vod0dvZGZPSGMKLS0tICs0R251VmhQOXpEOHhuQ3NLMXRG
            MHhmeFJ4aXlZQTBLbzk2c2x6dFZGZnMKdOgGkQgXafssUnCjXegcAXXfDQTPztfh
            puH1sJG03kIKOiy3IQXke5GwIljs20B9mOfuqz875UmboTQmzUn9Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY1JkS1VPWU5oaUJUMnBm
            U2VBdFB2aUVTWU11WkdMMGl3YTlRbDRqR2o0CjNpd2pHOEJIK3lOTDNjVStzM0JR
            TFVyTlZuUkNwTFFBMjFrSXdnTGpCd2sKLS0tIFZCaGEyQThIVGx4TlRwbGJKanMx
            SUYrZnVNU2FCZGVocTZWOVJmd1ZqU0UKTLrkkermfb7EUipFTxeAmhl+TcGDe1jg
            kXEbgPTWdJoZj34r0KoV1fP2FL6cH0FrhTaEjq3q1bTbMRo7UdXAyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-09-27T18:10:01Z"
    mac: ENC[AES256_GCM,data:cyvsMJuv5Pa+fPlhdQGobAwmUKRPnbCeQNQNrUFsuyPq2BbG9/5KWiAlar2bDyICBvLLt1heet7IuMKEnAgJkAbY6/mVmyLPj9ACkuoARSWujZDWwfh7/hf57kReBgwoou9P/KG7ypq0RuMS1v5zaNM7hSXE3B7mdebRsCjKnsA=,iv:HnixQ7cMIfcJtI/o3vUKBSEEK3MlMcX3I4D0PgrMbH8=,tag:cZOrRYr5vEbN8DQAGV3I9Q==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
