apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: syncthing
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: syncthing
      interval: 5m
  releaseName: syncthing
  targetNamespace: syncthing
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    persistence:
      config:
        enabled: true
        storageClass: longhorn-replicated
        size: 150Gi
        retain: true
    service:
      main:
        enabled: true
        controller: main
        type: ClusterIP
        ports:
          http:
            # -- Enables or disables the port
            enabled: true
            # -- Make this the primary port (used in probes, notes, etc...)
            # If there is more than 1 service, make sure that only 1 port is marked as primary.
            primary: true
            # -- The port number
            port: 8384
            # -- Port protocol.
            # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
            # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
            protocol: HTTPS
          listen:
            # -- Enables or disables the port
            enabled: true
            # -- Make this the primary port (used in probes, notes, etc...)
            # If there is more than 1 service, make sure that only 1 port is marked as primary.
            primary: false
            # -- The port number
            port: 22000
            # -- Port protocol.
            # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
            # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
            protocol: TCP
          discovery:
            # -- Enables or disables the port
            enabled: true
            # -- Make this the primary port (used in probes, notes, etc...)
            # If there is more than 1 service, make sure that only 1 port is marked as primary.
            primary: false
            # -- The port number
            port: 21027
            # -- Port protocol.
            # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
            # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: zerossl-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: syncthing.sakul-flee.de
            paths:
              - path: /
                pathType: Prefix
                port: http
        tls:
          - secretName: syncthing-sakul-flee-de-tls
            hosts: [syncthing.sakul-flee.de]
