apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: synapse
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: synapse
      interval: 5m
  releaseName: matrix
  targetNamespace: matrix
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  valuesFrom:
    - kind: Secret
      name: secret-synapse
      valuesKey: signingKeyB64
      targetPath: signingKeyB64
    - kind: Secret
      name: secret-synapse
      valuesKey: regSharedSecret
      targetPath: regSharedSecret
    - kind: Secret
      name: synapse-db-app
      valuesKey: dbname
      targetPath: postgres.database
    - kind: Secret
      name: synapse-db-app
      valuesKey: host
      targetPath: postgres.host
    - kind: Secret
      name: synapse-db-app
      valuesKey: password
      targetPath: postgres.password
    - kind: Secret
      name: synapse-db-app
      valuesKey: port
      targetPath: postgres.port
    - kind: Secret
      name: synapse-db-app
      valuesKey: user
      targetPath: postgres.user
  values:
    serverName: sakul-flee.de
    replicaCount: 3
    storageClass: longhorn-replicated
    ingress:
      enabled: true
      hosts:
        - host: matrix.sakul-flee.de
          paths: ["/"]
      tls:
        - secretName: matrix-tls
          hosts:
            - matrix.sakul-flee.de
