---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: matrix
      version: 3.11.x
      sourceRef:
        kind: HelmRepository
        name: matrix
      interval: 5m
  releaseName: matrix
  targetNamespace: matrix
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
  values:
    persistence:
      enabled: true
      storageClass: longhorn-replicated
      size: 8Gi
    ingress:
      hosts:
        federation: matrix-federation.sakul-flee.de
        riot: element.sakul-flee.de
        synapse: matrix.sakul-flee.de
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: zerossl-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hostName: matrix.sakul-flee.de
      resourceRootUrl: matrix.sakul-flee.de
      path: /
      tls:
        - secretName: matrix-sakul-flee-de-tls
          hosts: [matrix.sakul-flee.de]
    bridges:
      volumes:
        storageClass: longhorn-replicated
      discord:
        enabled: true
        defaultVisibility: private
      whatsapp:
        enabled: true
    coturn:
      enabled: false
    mail:
      enabled: false
    matrix:
      adminEmail: matrix@sakul-flee.de
      serverName: sakul-flee.de
