apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: matrix-stack
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/element-hq/ess-helm/matrix-stack
