apiVersion: v1
kind: Secret
metadata:
    name: secret-media-vpn
    namespace: media
type: Opaque
stringData:
    PIA_USERNAME: ENC[AES256_GCM,data:Kvn2CmicXNU=,iv:FFtyHmuW9Jg5lqeRkgPLr1K0G1pFxv6KbJUbTA3AI+o=,tag:GckpPflQg9fwd4c+YIeFCQ==,type:str]
    PIA_PASSWORD: ENC[AES256_GCM,data:jR0O8UILYil+9MMQRpuV6uO05w2hsHdaBTKHV2Ft/l0=,iv:BGUnZd1Q/t8LdAJbm/y3dTX5Fue6kKSr+vaixTQoi80=,tag:o5ld5hMp+8JJoMBzd0MYVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZkIxOE1FTmNBT3JjNnM4
            eUUyMHBOVWwyL3pIeFpNalRscjNxcDVWY1RBCmpaamhDTEN0a2Z0TUczVjRvdHFw
            U0pBSXZDOGR1SmVsc2s2WHUxSDB2TDAKLS0tIGtqcW5JZXk2RlVKSTZLMjhoVTFx
            S1JyU2J3eDBxbWsvYWVmSTE4YnFPRjgKyJZnbgD8LJpYB32WlN4nIibH/a3NM1pg
            /A/Q1Tx7j8UxgMxIfEsQLaO7qO6DLqPjIKXV6oLnIkrzvkc3cUBvrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUUtQMytFdVJGcjNxS3JM
            QUMvNjVTdFdLazhjcDFMTlREUDNjK05TVFZFCkk2UHJwZ05PbDdxcjVXYm1Yb25U
            aERwdGlkNnZONDdJK1owL0RJNjBFdDQKLS0tIGlpZ2JVZXgvenhQRHZNM095WWxh
            dUhib1FmdjBCQ0tZVzVKZWtSZUVzcmMK1bIA8AJSdF/70JKDaRizZRrKBALEhsda
            zSPG9DgjGpgylxKuY1bqhg/zxkAgibKawCVRsV+LF6WVMXgYWUHl0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSTl5M2FNQ3FBSE1zdHYv
            MGs5WEZMWnEvZHRwbm1MTVRCOTNVMDNvbFFVClhFQStPTlNKQ0dVQWw1aDBmb0sx
            OG5QZmtkaDlCRkp6bWpITW1ocFNicnMKLS0tIFZCdzNpcmFVZ3FtV0lnMjgvVC92
            US9yR1dXSkVnb3k0eEc4di9UVy80dG8K3QsZ2Cap/EpPF99scrDntcwwcwAk19yt
            9S57UKC7cIZPvBepAZIkPgjGAbx3Wtij4D3SG8X07nWIA0ZS/ynxKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-23T16:32:43Z"
    mac: ENC[AES256_GCM,data:g6LSj5WfYBQHqW4+M3hwSyBNs0Mdgplfwt995ubDdylzgQKvmX8a36myEf7WJ2fzkbmPu/io8THNokcrAeHhsFbQ1XYOOR7HObjT1xhInb5X2e8JniLvHQYVlFArcayPzqlgkukUJ+/QZSSmJhWRM0BKx08z3a6chx2Pcu5Rq6c=,iv:0TG6wqOf/Ph+HEAd393Q7bNbpz5EV+OyF0JrkpBfaTc=,tag:sd5a2dT0sdd/XHj+2l84mw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
