apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: media
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
