apiVersion: v1
kind: Secret
metadata:
    name: subnet-router-auth
    namespace: subnet-router
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:eKjXi1/Iq2UB6jJwI7iS8HI+62DgwosV41N09joBmXSdaT0sIHaPvavQX3e6im3GbOJqw1doBq5J9XwCg9re619CUZdoO+QRnGx+ubquk8cAr/xDUMYPUQ==,iv:fNH3uBPrnSnZxKvEr8arI8PtHOzZGgAzwdcXQfg4Tac=,tag:3WRv8WUOQvaTLzUj5JDv0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbDY2dlE0RU5ESDVCMW53
            cmI0Q1YvQlV5d1ZoZEFHWXBvZHZHWEdrZ25zCitEN2JDeVhSdE1wb0pwK0oyaG5R
            eGJEVlNFZ2cza0lNOTJwUk9TUXlMa28KLS0tIFFjQVdpYmt0azh0SlhLdkZWelNt
            MHBkWVFoMXVLWjd5dk9adG1UeVpwVWMKliSib4tjne7Nw11zNxPoMlbUovY0RZ9G
            +YL6O1OruRVsXBe3hYg7+ZHoZMmoBd3lxS97EmRzZ3WGJkMj33tBUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONTZWUFB6QWtBZ3Z1M3ZU
            NkU0TkF5WFFybmlEL0lVTXFRWjJPY0UrRFRvCjJIUmt2ZkMrKzdkNUY1ZVhBOGtt
            QzZJc2VGb1R2cHNuNHRaRmRxdk5iS2sKLS0tIEdabWxHWTBtU1ZaN2pVb3dkQTMv
            T3JZL3YwUHdmRHhDb25YUHdXWUVXV2cKPxgFLWZdawoU5D2MEI+0BHYUBvUutJOM
            Pg7ygB33eIiVEfwsMlPNLJVGdOryCwieeCyfK/IC2mlluXHTcG8VoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY1BUUXQxNllqNnp0UUt3
            SFF5OFdhenJ6eldBdXZqVjhGRHQrZjJHVkRNCjI0Ry9kdnhsRGMyOHpZV293Wld6
            bkozaUVuREh3UGsrSTJpa0Zrdm9PcHcKLS0tIDVybDVKUzNsUDY3dm5kamkvMGpF
            QThVcDRsRVlsaDJpdHN6SzdnL2JHS2cKQ9QOJHCwGsBv/GBH2bs6Ade1y6Gh3AgI
            8Z+CH+NCfXP6/oiT17tSI44/3J3wHbZOBUSq0YtbkEBYK6+X9a1VVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T15:37:30Z"
    mac: ENC[AES256_GCM,data:ybrkwEbVvm7jgiDnPvKoZnSSuaLymgj4MOAOZl22udrjwsLp8/SIZo3pvfziqav3lzTyszA5mnnSfrhT6he38teTarFRRY5OX9tWCfBe5SzajlFQuO2YNwIpwYTv4SewGpgqU8nbBQT6ZadZgG6OR9spwyS1AVeJt3MT7OeFPfs=,iv:3H4RAvhoF3HTLrUiOSPrfH47VOzS0dhZxw5xpYp5nx4=,tag:5Gjcit9wgjZDgzAu3G064g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
