apiVersion: v1
kind: Secret
metadata:
    name: subnet-router-auth
    namespace: subnet-router
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:ud/6TQmBmiVhsldWzMRH9i9Qdet4QF8Hz8ux6EpXt/a1ZYRVpTq47swsD5xIcn41SLwzOXXDhbhdXHf4AC6FdaM/uUM7pCfoXlRRhw+6/2hn0JqvikHdXA==,iv:wLaHMJQwByzU2K2SJmIPBfQd4IbRVv/VuDpuI3G7cq8=,tag:DzVlZQSLEhOrYFqwXQfv0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R2xtS0ptRFl5UGNUV283
            eGJNemtrMnBUNWdGUmxVUXFXdTZ1NlpkR3cwCnFaTFNreTdNclhEaW9XWXpLTk5k
            TC83WVJlbzkzVmpUb0pLV0wyMjZYTFUKLS0tIDdUUmlOcE54MC81em9ZNUVzTXhW
            WldYUWxreDQrVmN1OE93MjBLaTlTY00KB7+1ZBSLRze3OAsJDblek5DSRaotlFJK
            diBB68gbdWyBygeEzIZf6vkLnhZheecttKHUQQOM1d3E6QlRVlP7Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYVo4MHQ3T3BQbENjSE4y
            ZS90clZTVHlCVStNMUFCTHBCb09lOWtra1NzCjFXczRSa2x3Q1pZK2R1OHV5VGRu
            aG81Kzc1dmpHZlpVR1NzZHYyN2kwa1UKLS0tIGFwVkpwQ3pvSWk0bFErQW0wc0d2
            OFV5OGlPTDlGZmRYZGRDc3B0RWwxT0EKs8hqJrX4PnUqtSEz9YM5m9O55tmPg/KV
            TjT4kdLqphdmXCWc8/wJLBl/s0n7beuXOZZxuYisMtJrprJ7G/s8mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdTFqbFJlKzlGMEF0MGZ6
            RFZQeFdJMjlXU3hKSzdJTVUweVZNc0tUa3dzClJkRVUvUHpubGhQMDFHSzhoK0tv
            d2owMURIVmJoMm5nL1VwYW0zK3c0c3cKLS0tIGRQeXJoYWJFMEZqdDRNSmNzS3pH
            WmxpOUJacFNDeTlwRTZUZjJIckRuS00KquOH9zqk0DV/l4Vpux+kswH8Qlfry3KG
            37TIerFvWgiOxfKvjgBU0EzF716EYuYOirIQNY5SbGn0aVYqfVqWug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T19:22:13Z"
    mac: ENC[AES256_GCM,data:292QUGH3Xu8/wmqsiTelD4xfG6ImaMqJ/iBSXVkv0P2C5qazj4EqGdlSrFjFRtZgNtdADC6iQ6B7NtMFhW7jhxcMW8rMci8jaFX5E6QIoV2T1ICGS121jdTxjcX5HFqyroG1xtrNvNTysV4SsCHuxAYCLXUGSfLl6liRXc+fwaM=,iv:K2RcMxtJoGbKMwzu2W3LzI5PRO418QC0L40Dkbkv3S4=,tag:L7hlSwjNOq6kNOUgWr+lMA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
