apiVersion: v1
kind: Secret
metadata:
    name: subnet-router-auth
    namespace: subnet-router
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:cclzMYE5qhznNpoCfxk6lJPwITTGVRnx87/VuTZYPkcJ2RRjFug8Rv+TtfQs0qozYqe2MvXMsQGIPLoJ6x351XrdLL8HQUCchHWm64zB+q7sJznAa7SwRg==,iv:jm7UeS5zFFnyV0DE1dLYoi3+/op3N4f6mYKjFtOd3SQ=,tag:ldcPMK/qCcJBSvWqz1Swkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N1NTVEZMQ3RnTjlWVW93
            Slo2Qmo3VG9KNENEcUNCWTU2V3YrTWd5Ymx3ClVYWWlIUjZCbXZzeGV3WHdjYndz
            bTQxcmZTVUN4L1hhcUlPTzlvR2lxVFEKLS0tICtjZzJGZU8xQkdxQWVoT2o4SnFK
            c0tlNkx2UEVBb05NanFnNUx2UGdvdzgKAmKWmrIK2t7ohHAp3TQB+Gr9SfAn35lu
            k0ipdTReAaKztJ1pV27VEpVmLZsBtDMK0j+5Bsf9e17wQ57Z9LDftQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWnBtZHpBNDhGT1BWbkM0
            SEpCVEpJVDI1SHc0ejdRbkdQSzdBM3E2TVVzCk5Rc1pqeVlSK080akc1UE1FR3NI
            RHFVVmFFUUx2djJBR0VCSHg4ZENaR1EKLS0tIElFTExORTlYK0RnMmtsdlF1Y0Ey
            SHdPWmxlRjhERUtOaGd5UC9Iak1qM1EKETQvAi6KqfGvnphisLvaAcW5jopR0LwB
            QbZUKBDnfV20/YARzz11Lukah861xmCpN/0eohZ7fTlS53tTtUDTRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TWJob3FUNW4zZGJuL3JH
            YktHR2ltenROVnNlUkVzb1VvcE1QQVlWb1RNCmxHK0gzN1MzaGM3eDAzMWpINnFL
            dWlTSEEzc1hVTlRMb2lHNzNUK1lzekUKLS0tIFBXV0t1cXhmMmxvSU9JMlVkbEVQ
            VnE1WXlQZytZeDh5STZtM0IvVUFZeUkKaMWQmES8X4SYowCHtHZI7oxwpAIuqm4B
            6KXyugGheR8s2lKnzrBz0MqItr3yqM7pt7AlgetALmt+EZUX60zIuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-25T00:44:04Z"
    mac: ENC[AES256_GCM,data:D8tATnMT7lLHTes8N17FIAUqJIdv5FFYuZG20VY3psL9vTrI7efg7cJeMZje2JMwZ22Wd/5SJlm+9ZjX+iIU935RHNmKSSO2uiVD/s4OPyyb7q0g34fpaGj/t2YPmb+dUC4pSR577SL+sU0sGPwGWLAxIbZr7aLX31Z0M0hAhJQ=,iv:zGQRy57V5LmJ4uFIFeQzgz0fuhzJNRnHjVa/a4zu9Cs=,tag:epaCEuBPYzHByGGgLPxwkA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
