apiVersion: v1
kind: Secret
metadata:
    name: bitmagnet-secrets
    namespace: media
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1XwLuM1yQqovQVojJKd3ACnC8GMe35FJ69b21q25ZkM=,iv:5YVR+HTxr0SHh3OTcbWWizoHQHGyFeoV/fY/f279E20=,tag:kAdFsn7MFa1OcnA31BUBLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aXN5TTJ3OElwc1RZOFVa
            NmRoeGVvYlhzTWJQK0g0Q1hjNjBldVVtOFJrClp2YnM1Ykl6c09YVkswSE9lcSt2
            MUVRMjFGZG9MZkQwek96ZHJNWEdodkUKLS0tIDlsS0hzYXdVelpNMlJLc0xxbXRi
            V1BEbXZ6Rm1XUS9kRGp3QUlZMkV5ZDAKPqZhrmLRThnTfmPxGRNIUxWC12oDT3zA
            jLHcBQ1po8nhV45T63NkIpdm6bY87zkck0fbfWUQRCtPauVki4n2Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb25vQjdQd0Y0Q3Q2REh4
            bjZ1YW9xMS9McmdicXNqMWZiQzJFT3BNS3o4Ck9xZ01TNEcveUM1Q0V0SENiV0hs
            OTRUSnhZODZ3SGVjaktmMjk4VmhGb2cKLS0tIFJwRlMxd1RFUzVVUmZKbEdmYkVp
            Ky9Ba3JIUlQyZ0wyeTUvSkNLVzZRQXMKEdNTR84nYG36KGGYGpzDG3OMjjTPaiQH
            R04YxdAod3M3FtGb1tFpZjXZ0G3klSnqoclkSuE11byu2JsGljdwZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MHA1emVCVkQ1cVEzRDhO
            NEp2bUxRL3czazU3amQxSmRQVFpvSk95RkhFCllTOU5uZTdPOTMweDZYUk9wNWp3
            dHgzOE56V0N2M0h2TWloSDJ0WFJIaGsKLS0tIG5oaVFPemI5L2NMdTZuWGJoOFZ5
            UVQ0TWc5emNPQ1RtYTlSVTZvcU1oTDAKJC0MNNSLyx4sk2WbPkKck59Y4wzSY+QS
            QKT9kXY4tg+JJayA4jCuaZ2zBERX2F/KHVpTawaQg+LGCVHDa4B7qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-24T20:55:50Z"
    mac: ENC[AES256_GCM,data:uVAoL4nnSzmfh9UaxSvDylIUm8GQePHfjCyx7Quh0VBKWb90meGUOn2W0ljRpAKO3UJZUp6T8shpHqaM/Z1ABXdQQoc4R9iLnH7+nZ/gdS8jC1Hp9bWxTfHfwKBemy1HzdiSQ+YO4gFCTxxHrQYrsjYAKt1fgJd7HzT7Rn2IMvc=,iv:F52JohmWFq1MMkhzNBVIEegUHxvZVYER96SGl0HBoiY=,tag:X0k1wl8syYSgn2kJEsrC3g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
