---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-data
  namespace: youtrack
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-conf
  namespace: youtrack
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-logs
  namespace: youtrack
spec:
  storageClassName: local-path-volatile
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-backups
  namespace: youtrack
spec:
  storageClassName: local-path-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi