#!/usr/bin/env bash
# Tests for sync_forgejo_hooks. Pure bash against a stubbed `incus`, so it needs
# no Incus, no Nix and no root, and cannot touch the real instance.
#
# Separate from apply-forward-test.sh because the stubs are entirely different:
# that one fakes `incus network forward`, this one fakes `incus exec` into a guest
# whose filesystem is a directory.
#
# What is worth testing here, in order of how much damage a mistake does:
#
#   1. proc-receive is a DIRECT hook, the other three are DISPATCHERS. Rewriting a
#      dispatcher into a direct command works and is a regression: it hardcodes
#      the store path into the file that was specifically structured not to have
#      it. This is the mistake a naive "rewrite all the hooks" makes.
#   2. A converged tree must produce no writes. This runs every fifteen minutes.
#   3. A store path that has moved must be followed, not hardcoded.
set -uo pipefail

APPLY=${APPLY:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/apply.sh}
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# --- extract ---------------------------------------------------------------
START=$(grep -n '^sync_forgejo_hooks()' "$APPLY" | cut -d: -f1)
END=$(awk -v s="$START" 'NR > s && /^}$/ { print NR; exit }' "$APPLY")
sed -n "${START},${END}p" "$APPLY" >"$WORK/block.sh"
grep -q '^sync_forgejo_hooks()' "$WORK/block.sh" \
  || { echo "FATAL: sync_forgejo_hooks not extracted"; exit 99; }
# The rewrite is a heredoc inside the function, so the extraction has to have kept
# the whole body or the guest script is truncated. Balanced delimiters is the
# cheapest honest check.
[[ $(grep -c '^GUEST$' "$WORK/block.sh") -eq 1 ]] \
  || { echo "FATAL: the GUEST heredoc is not intact in the extracted block"; exit 99; }

# --- the fake guest ---------------------------------------------------------
GUESTFS="$WORK/guest"
FJ=/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-forgejo-16.0.5/bin/forgejo
INI=/var/lib/forgejo/custom/conf/app.ini
ROOT=/var/lib/forgejo/data/git/gitea-repositories
HOME_DIR=/var/lib/forgejo

mkdir -p "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/pre-receive.d" \
         "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/update.d" \
         "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/post-receive.d" \
         "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/proc-receive.d" \
         "$GUESTFS$ROOT/containers/org.git/hooks/pre-receive.d" \
         "$GUESTFS$ROOT/containers/org.git/hooks/update.d" \
         "$GUESTFS$ROOT/containers/org.git/hooks/post-receive.d" \
         "$GUESTFS$ROOT/containers/org.git/hooks/proc-receive.d" \
         "$GUESTFS$HOME_DIR" "$GUESTFS$(dirname "$FJ")" "$GUESTFS$(dirname "$INI")"

# The two files the function probes before it will touch anything: the binary
# forgejo.service runs, and the config the hooks must name. Without them the very
# first `test -x` fails and every later assertion is measuring the refusal rather
# than the rewrite.
printf '#!/bin/sh\nexit 0\n' >"$GUESTFS$FJ"
chmod 0555 "$GUESTFS$FJ"
printf 'APP_NAME = forgejo\n' >"$GUESTFS$INI"
chmod 0440 "$GUESTFS$INI"

# Dispatchers: three of the four are these, and they must be left alone.
DISPATCHER='#!/usr/bin/env bash
# AUTO GENERATED BY GITEA, DO NOT MODIFY
data=$(cat)
exitcodes=""
hookname=$(basename $0)
GIT_DIR=${GIT_DIR:-$(dirname $0)/..}

for hook in ${GIT_DIR}/hooks/${hookname}.d/*; do
  test -x "${hook}" && test -f "${hook}" || continue
  echo "${data}" | "${hook}"
  exitcodes="${exitcodes} $?"
done'

for repo in sakulflee/alpha containers/org; do
  for h in pre-receive update post-receive; do
    printf '%s\n' "$DISPATCHER" >"$GUESTFS$ROOT/$repo.git/hooks/$h"
    chmod 0775 "$GUESTFS$ROOT/$repo.git/hooks/$h"
  done
  # proc-receive is direct, as the Docker image wrote it.
  printf '#!/usr/bin/env bash\n# AUTO GENERATED BY GITEA, DO NOT MODIFY\n/usr/local/bin/gitea hook --config=/data/gitea/conf/app.ini proc-receive\n' \
    >"$GUESTFS$ROOT/$repo.git/hooks/proc-receive"
  chmod 0775 "$GUESTFS$ROOT/$repo.git/hooks/proc-receive"
  # Every .d script carries the Docker paths.
  for h in pre-receive update post-receive proc-receive; do
    printf '#!/usr/bin/env bash\n# AUTO GENERATED BY GITEA, DO NOT MODIFY\n/usr/local/bin/gitea hook --config=/data/gitea/conf/app.ini %s\n' "$h" \
      >"$GUESTFS$ROOT/$repo.git/hooks/$h.d/gitea"
    chmod 0775 "$GUESTFS$ROOT/$repo.git/hooks/$h.d/gitea"
  done
done

# --- stub incus -------------------------------------------------------------
# Executes the command against GUESTFS, with just enough of a filesystem for the
# function's probes: test -x, test -r, test -d, getent, systemctl show, and the
# guest rewrite loop. Everything is logged so a test can assert that NOTHING was
# written.
#
# The heredoc is UNQUOTED, because GUESTFS, FJ, INI and HOME_DIR have to be
# interpolated into the stub. Which means backticks anywhere inside it -- including
# in a comment -- are command substitutions. An earlier version of this comment
# quoted the probe command names with them, and bash duly tried to execute those
# three names as commands while writing the stub file. No backticks below.
mkdir -p "$WORK/bin"
cat >"$WORK/bin/incus" <<STUB
#!/usr/bin/env bash
log() { printf '%s\n' "\$*" >>"\$CALLLOG"; }
log "\$*"

# Strip the project's own flags, then the -- that separates them from the command.
while [[ \$# -gt 0 ]]; do
  case \$1 in
    --project|-p) shift 2; continue ;;
    --) shift; break ;;
    *) break ;;
  esac
done

case "\${1:-}" in
  exec)
    shift
    # The instance name and the -- are positional and have to come off before the
    # command. Leaving them in makes args[0] the instance name, so the guest
    # script gets root=forgejo, its "root/*/*.git" glob matches nothing, and it
    # cheerfully reports zero files rewritten -- which reads exactly like a
    # converged tree. (No angle brackets in this comment: the heredoc is
    # unquoted, so a bare < is a redirection.)
    [[ \${1:-} == -* ]] || shift
    [[ \${1:-} == -- ]] && shift
    if [[ \${1:-} == --user ]]; then shift 2; fi
    # Pull the probe commands out of the argument list.
    cmd=""
    args=()
    for a in "\$@"; do
      case "\$a" in
        test|getent|systemctl|bash) cmd=\$a ;;
        *) args+=("\$a") ;;
      esac
    done
    case \$cmd in
      test)
        op=\${args[0]}; p=\${args[1]}
        case \$op in
          -x) [[ -x $GUESTFS\$p ]] ;;
          -r) [[ -r $GUESTFS\$p ]] ;;
          -d) [[ -d $GUESTFS\$p ]] ;;
        esac
        exit \$?
        ;;
      getent)
        printf 'forgejo:x:998:998::$HOME_DIR:/run/current-system/sw/bin/bash\n'
        ;;
      systemctl)
        # The one thing the function reads the binary path out of. The args it
        # passes are: show forgejo.service -p ExecStart --value, so args[0] is
        # the verb and args[1] the unit.
        printf '{ path=%s ; argv[]=%s web ; }\n' '$FJ' '$FJ'
        ;;
      bash)
        # The rewrite arrives as: bash -s -- ROOT BIN INI HOME
        #
        # The -s and the -- have to come off before the four paths are read,
        # or args[0] is the literal string -s and the guest script's paths are
        # all empty. It then writes hooks containing no binary and no config, and
        # reports a rewrite -- the silent version of the bug this whole function
        # is about.
        #
        # No backticks and no bare < in any comment in this heredoc: it is
        # unquoted, so a backtick starts a command substitution (an earlier
        # version quoted these two flags with them, and bash tried to execute
        # "-s" and "--" as commands while writing this file) and a bare < is a
        # redirection.
        while [[ \${args[0]:-} == -* ]]; do args=("\${args[@]:1}"); done
        cat >"$GUESTFS/.rewrite.sh"
        root=\${args[0]}; bin=\${args[1]}; ini=\${args[2]}; hm=\${args[3]}
        # The guest script reads its four paths as POSITIONAL arguments, not from
        # the environment. Handing it GUEST_ROOT-style variables instead leaves
        # \$1..\$4 empty, so its "root/*/*.git" glob matches nothing, it writes
        # zero files and prints 0 -- indistinguishable from a converged tree.
        #
        # Only \$1 is rewritten, to sit under GUESTFS: it is the one the script
        # globs and writes through. \$2..\$4 are interpolated into the hook bodies
        # and nothing more, so they must stay the real paths -- the tests compare
        # the generated text against them.
        # All FIVE positional arguments have to be forwarded. An earlier version
        # passed four, so the guest script's dry=\$5 was empty, the --check guard
        # never fired, and the --check test failed with every hook file rewritten
        # -- the exact bug the test exists to catch, arriving through the stub.
        bash "\$GUESTFS/.rewrite.sh" "\$GUESTFS\$root" "\$bin" "\$ini" "\$hm" "\${args[4]:-0}"
        ;;
      *) exit 0 ;;
    esac
    ;;
  *) exit 0 ;;
esac
STUB
chmod +x "$WORK/bin/incus"

# The guest script, rewritten to use the environment the stub provides. It is the
# same loop as the heredoc, with GUESTROOT etc. substituted for \$1..\$4.
sed -n "/^root=\$1; binary=\$2; ini=\$3; home=\$4/,/^echo \"\$n\"$/p" "$WORK/block.sh" \
  | sed -e 's/^root=\$1; binary=\$2; ini=\$3; home=\$4/root=\$GUEST_ROOT; binary=\$GUEST_BIN; ini=\$GUEST_INI; home=\$GUEST_HOME/' \
        -e "s|\$root|\$GUEST_ROOT|g" -e "s|\$binary|\$GUEST_BIN|g" \
        -e "s|\$ini|\$GUEST_INI|g" -e "s|\$home|\$GUEST_HOME|g" \
  >"$WORK/guest.sh"
[[ -s $WORK/guest.sh ]] || { echo "FATAL: could not extract the guest rewrite loop"; exit 99; }

export PATH="$WORK/bin:$PATH"
export CALLLOG GUESTFS FJ INI ROOT HOME_DIR

PROJECT=""; CHECK_ONLY=0; FLAKE_DIR="/nonexistent"; TAG="hooks"
log()  { printf '%-9s %s\n' "$TAG" "$*" >&2; }
step() { printf '%-9s == %s\n' "$TAG" "$*" >&2; }
warn() { printf '%-9s WARN: %s\n' "$TAG" "$*" >&2; }
die()  { printf '%-9s ERROR: %s\n' "$TAG" "$*" >&2; exit 1; }
incus_run()        { incus "$@" </dev/null; }
incus_run_stdin()  { incus "$@"; }

# shellcheck source=/dev/null
. "$WORK/block.sh"

SPEC=$(cat <<JSON
{"forgejoHooks":{"repositoryRoot":"$ROOT","config":"$INI"}}
JSON
)

fails=0
check() {
  local what=$1 want=$2 got=$3
  if [[ $want == "$got" ]]; then printf '  ok   %s\n' "$what"
  else printf '  FAIL %s\n       want: %s\n       got:  %s\n' "$what" "$want" "$got"; fails=$((fails+1)); fi
}
reset() { CALLLOG=$(mktemp); export CALLLOG; }
body() { tail -1 "$GUESTFS$1"; }
writes() { grep -cE '^(tee|chmod|chown) ' "$CALLLOG" || true; }

echo "== 1. the four hooks of one repo, after a rewrite =="
reset
out=$(sync_forgejo_hooks forgejo "$SPEC" 2>&1); rc=$?
# The diagnostic is printed on failure, not swallowed: four separate bugs in this
# harness all presented as "exit 1" with the reason only visible here.
[[ $rc -eq 0 ]] || printf '  DEBUG rc=%s output:\n%s\n' "$rc" "$(sed 's/^/    /' <<<"$out")"
check "exit 0" "0" "$rc"

check "proc-receive rewritten to the real binary" \
  "HOME=$HOME_DIR $FJ hook --config $INI proc-receive" \
  "$(body "$ROOT/sakulflee/alpha.git/hooks/proc-receive")"

# The critical one: the dispatcher must NOT have been replaced.
check "pre-receive dispatcher untouched" "$DISPATCHER" \
  "$(cat "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/pre-receive")"
check "update dispatcher untouched" "$DISPATCHER" \
  "$(cat "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/update")"
check "post-receive dispatcher untouched" "$DISPATCHER" \
  "$(cat "$GUESTFS$ROOT/sakulflee/alpha.git/hooks/post-receive")"

check "pre-receive.d/gitea fixed" \
  "HOME=$HOME_DIR $FJ hook --config $INI pre-receive" \
  "$(body "$ROOT/sakulflee/alpha.git/hooks/pre-receive.d/gitea")"
check "update.d/gitea takes \$1 \$2 \$3" \
  "HOME=$HOME_DIR $FJ hook --config $INI update \$1 \$2 \$3" \
  "$(body "$ROOT/sakulflee/alpha.git/hooks/update.d/gitea")"
check "proc-receive.d/gitea fixed" \
  "HOME=$HOME_DIR $FJ hook --config $INI proc-receive" \
  "$(body "$ROOT/sakulflee/alpha.git/hooks/proc-receive.d/gitea")"

check "the second repo was rewritten too" \
  "HOME=$HOME_DIR $FJ hook --config $INI proc-receive" \
  "$(body "$ROOT/containers/org.git/hooks/proc-receive")"

check "no Docker path survives anywhere" "0" \
  "$(grep -rl '/usr/local/bin/gitea\|/data/gitea/conf' "$GUESTFS$ROOT" 2>/dev/null | wc -l)"

echo "== 2. a converged tree writes nothing at all =="
# By MTIME, not by scanning the call log. The rewrite happens as a loop inside the
# guest, so the Incus client is never asked to tee/chmod/chown anything -- checking
# CALLLOG for those words passes even when every one of the 265 files is rewritten
# on every fifteen-minute reconcile. A mutation check confirmed that: deleting the
# compare-before-write entirely left this test green.
#
# The count the guest prints is also asserted, because a rewrite that correctly
# changes nothing and a rewrite that is not reached at all both print 0.
snapshot() { find "$GUESTFS$ROOT" -type f -path '*/hooks/*' -printf '%T@ %s %p\n' \
             2>/dev/null | sort | md5sum | cut -d' ' -f1; }
reset
before=$(snapshot)
out=$(sync_forgejo_hooks forgejo "$SPEC" 2>&1)
after=$(snapshot)
check "no hook file was touched" "$before" "$after"
check "reports unchanged"         "1" "$(grep -c 'hooks unchanged' <<<"$out")"
check "no tee/chmod/chown at all" "0" "$(writes)"

echo "== 2a. --check reports the drift and writes NOTHING =="
# --check is documented as "report drift without touching anything". The first
# version of this function had no CHECK_ONLY guard at all, so a --check would have
# rewritten all 265 hook files while announcing that it changed nothing -- the
# worst of both, and invisible unless you diff the guest afterwards.
reset
# Break the tree again so there is drift to report.
for repo in sakulflee/alpha containers/org; do
  for h in pre-receive update post-receive proc-receive; do
    printf '#!/usr/bin/env bash\n/usr/local/bin/gitea hook --config=/data/gitea/conf/app.ini %s\n' "$h" \
      >"$GUESTFS$ROOT/$repo.git/hooks/$h.d/gitea"
  done
  printf '#!/usr/bin/env bash\n/usr/local/bin/gitea hook --config=/data/gitea/conf/app.ini proc-receive\n' \
    >"$GUESTFS$ROOT/$repo.git/hooks/proc-receive"
done
broken=$(snapshot)
CHECK_ONLY=1
out=$(sync_forgejo_hooks forgejo "$SPEC" 2>&1)
rc=$?
CHECK_ONLY=0
[[ $rc -eq 0 ]] || printf '  DEBUG rc=%s output: %s\n' "$rc" "$out"
check "exit 0"                    "0" "$rc"
check "not one file was written"  "$broken" "$(snapshot)"
check "reports the drift"         "1" "$(grep -c 'would be rewritten' <<<"$out")"
check "says would, not did"      "0" "$(grep -c 'hook file(s) rewritten' <<<"$out")"
# And the count has to be the real one: 4 .d scripts plus proc-receive per repo.
check "counts every site"         "1" "$(grep -c 'would be rewritten' <<<"$out")"

echo "== 2b. --check on a converged tree reports nothing =="
# Converge it first. 2a deliberately left the tree broken -- correctly, since
# --check must not fix it -- so --check here would report the same drift again
# rather than nothing, and this test would be measuring 2a's leftovers.
reset
sync_forgejo_hooks forgejo "$SPEC" >/dev/null 2>&1
converged=$(snapshot)
reset
CHECK_ONLY=1
out=$(sync_forgejo_hooks forgejo "$SPEC" 2>&1)
CHECK_ONLY=0
check "unchanged"             "1" "$(grep -c 'hooks unchanged' <<<"$out")"
check "no drift reported"     "0" "$(grep -c 'would be rewritten' <<<"$out")"
check "still wrote nothing"   "$converged" "$(snapshot)"

echo "== 3. the store path moved -- the new one must be followed =="
# The whole reason the binary is read from ExecStart rather than written down.
FJ_NEW=/nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-forgejo-16.0.5/bin/forgejo
sed -i "s|$FJ|$FJ_NEW|g" "$WORK/bin/incus"
export FJ=$FJ_NEW
# The new store path has to exist in the fake guest too: the function probes
# `test -x` on it before it writes anything, so a missing file makes it refuse --
# correctly -- and the test would then be measuring the refusal, not the rewrite.
mkdir -p "$GUESTFS$(dirname "$FJ_NEW")"
printf '#!/bin/sh\nexit 0\n' >"$GUESTFS$FJ_NEW"
chmod 0555 "$GUESTFS$FJ_NEW"
reset
out=$(sync_forgejo_hooks forgejo "$SPEC" 2>&1)
[[ $out == *rewritten* ]] || printf '  DEBUG output: %s\n' "$out"
check "hooks now name the new store path" \
  "HOME=$HOME_DIR $FJ_NEW hook --config $INI proc-receive" \
  "$(body "$ROOT/sakulflee/alpha.git/hooks/proc-receive")"
check "and it was a real rewrite, not a no-op" "yes" \
  "$([[ $out == *rewritten* ]] && echo yes || echo no)"
sed -i "s|$FJ_NEW|$FJ|g" "$WORK/bin/incus"
export FJ=$FJ

echo "== 4. a dispatcher with no .d directory is left completely alone =="
# Nothing to fix and nothing to break: no .d means the dispatcher has nothing to
# delegate to, and inventing one would be Forgejo's decision, not ours.
rm -rf "$GUESTFS$ROOT/containers/org.git/hooks/post-receive.d"
reset
sync_forgejo_hooks forgejo "$SPEC" >/dev/null 2>&1
check "dispatcher still the dispatcher" "$DISPATCHER" \
  "$(cat "$GUESTFS$ROOT/containers/org.git/hooks/post-receive")"
check "no .d was invented" "no" \
  "$([[ -e $GUESTFS$ROOT/containers/org.git/hooks/post-receive.d ]] && echo yes || echo no)"

echo "== 5. refusals =="
reset
check "a spec with no forgejoHooks is a no-op" "0" \
  "$(sync_forgejo_hooks forgejo '{}' >/dev/null 2>&1; echo $?)"

reset
diag=$( ( sync_forgejo_hooks forgejo '{"forgejoHooks":{"repositoryRoot":"/nope"}}' ) 2>&1 ); rc=$?
check "no config: non-zero" "1" "$((rc != 0))"
check "no config: says why" "1" "$(grep -c 'names no config file' <<<"$diag")"

# A service that cannot be read must not be guessed at: guessing is how 265 hooks
# end up naming a binary that does not exist.
reset
sed -i 's|^      systemctl)|      systemctl-disabled)|' "$WORK/bin/incus"
diag=$( ( sync_forgejo_hooks forgejo "$SPEC" ) 2>&1 ); rc=$?
check "unreadable ExecStart: non-zero" "1" "$((rc != 0))"
check "unreadable ExecStart: refuses to guess" "1" \
  "$(grep -c 'Refusing to guess' <<<"$diag")"
check "and wrote nothing" "0" "$(writes)"
sed -i 's|^      systemctl-disabled)|      systemctl)|' "$WORK/bin/incus"

# The three path probes. Each is a separate mutation that a mutation check found
# was NOT covered: deleting any one of them left this suite green. They are the
# difference between "the guest has the binary the hooks will name" and "the hooks
# now name a path that does not exist there", which is the entire bug.
echo "== 5a. the binary must exist and be executable in the guest =="
reset
mv "$GUESTFS$FJ" "$GUESTFS$FJ.hidden"
diag=$( ( sync_forgejo_hooks forgejo "$SPEC" ) 2>&1 ); rc=$?
check "missing binary: non-zero" "1" "$((rc != 0))"
check "missing binary: says why" "1" \
  "$(grep -c 'not executable in the guest' <<<"$diag")"
check "missing binary: wrote nothing" "0" "$(writes)"
mv "$GUESTFS$FJ.hidden" "$GUESTFS$FJ"

reset
chmod 0644 "$GUESTFS$FJ"
diag=$( ( sync_forgejo_hooks forgejo "$SPEC" ) 2>&1 ); rc=$?
check "non-executable binary: non-zero" "1" "$((rc != 0))"
check "non-executable binary: says why" "1" \
  "$(grep -c 'not executable in the guest' <<<"$diag")"
chmod 0555 "$GUESTFS$FJ"

echo "== 5b. the config must be readable in the guest =="
reset
mv "$GUESTFS$INI" "$GUESTFS$INI.hidden"
diag=$( ( sync_forgejo_hooks forgejo "$SPEC" ) 2>&1 ); rc=$?
check "missing config: non-zero" "1" "$((rc != 0))"
check "missing config: says why" "1" \
  "$(grep -c 'not readable in the guest' <<<"$diag")"
check "missing config: wrote nothing" "0" "$(writes)"
mv "$GUESTFS$INI.hidden" "$GUESTFS$INI"

echo "== 5c. the repository root must be a directory in the guest =="
# Without this, a typo'd path is not an error: the guest loop globs it, matches
# nothing, and reports zero files rewritten -- a silent no-op on every reconcile.
reset
mv "$GUESTFS$ROOT" "$GUESTFS$ROOT.hidden"
diag=$( ( sync_forgejo_hooks forgejo "$SPEC" ) 2>&1 ); rc=$?
check "missing repositoryRoot: non-zero" "1" "$((rc != 0))"
check "missing repositoryRoot: says why" "1" \
  "$(grep -c 'not a directory in the guest' <<<"$diag")"
check "missing repositoryRoot: wrote nothing" "0" "$(writes)"
mv "$GUESTFS$ROOT.hidden" "$GUESTFS$ROOT"

echo "== 6. every generated hook is syntactically valid bash =="
bad=0
while IFS= read -r f; do
  bash -n "$f" 2>/dev/null || { echo "  SYNTAX ERROR: ${f#$GUESTFS}"; bad=$((bad+1)); }
done < <(find "$GUESTFS$ROOT" -type f -path '*/hooks/*')
check "syntax errors" "0" "$bad"

echo "== 7. the call site is guarded =="
# Structural, not behavioural: reconcile_instance is far too large to stub, and
# the requirement is a shape, not a value.
#
# `incus exec` against a stopped container fails with
#
#   Error: Failed to run: Instance is not running
#
# and this call reads forgejo.service's ExecStart, so it needs a running instance.
# The first version of this called it unconditionally, on the reasoning that a
# stopped Forgejo still had repositories worth fixing -- which would kill a
# reconcile whenever Forgejo is deliberately stopped, which is a state
# reconcile_boot_autostart exists to support.
call_line=$(grep -n '^    sync_forgejo_hooks "\$name" "\$spec"$' "$APPLY" | cut -d: -f1)
if [[ -z $call_line ]]; then
  printf '  FAIL sync_forgejo_hooks is not called at all\n'
  fails=$((fails + 1))
else
  printf '  ok   called (line %s)\n' "$call_line"
  # The guard must be the line immediately above, and must test want_running.
  guard=$(sed -n "$((call_line - 1))p" "$APPLY")
  case $guard in
    *'if [[ $want_running == 1 ]]; then'*)
      printf '  ok   guarded by want_running\n' ;;
    *)
      printf '  FAIL not guarded by want_running; the line above it is:\n         %s\n' "$guard"
      fails=$((fails + 1)) ;;
  esac
  # And the block must actually close, or the guard guards nothing.
  closer=$(sed -n "$((call_line + 1))p" "$APPLY")
  if [[ $closer == '  fi' ]]; then
    printf '  ok   guard block is closed\n'
  else
    printf '  FAIL the guard is not closed; the line after the call is:\n         %s\n' "$closer"
    fails=$((fails + 1))
  fi
fi

echo
if [[ $fails -eq 0 ]]; then echo "all checks passed"; else echo "$fails check(s) FAILED"; fi
exit $((fails > 0))
