apiVersion: ENC[AES256_GCM,data:XiA=,iv:IcHWOHw+j9aIjZlrKgJ9/4a3S9PdnB6VWx/bELA7+N0=,tag:PiWMCWjKOv7EHfimZXQhqw==,type:str]
kind: ENC[AES256_GCM,data:wX/+0+SJ,iv:20jGEoKlz0lvpcsZz6si3NZv/tZdflctwQ2lVmcqebw=,tag:ZcHpHFyS7BC2ebsWkAEhGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OsvKJHIH+dkLgX0mxN4=,iv:skTBaEsY7C4/L/gCxMxcXpyg1G8sCac++gxPhoR3XOs=,tag:AfOIhAuR81mOa+vDFDb3aw==,type:str]
    namespace: ENC[AES256_GCM,data:m2ypvwsRmw==,iv:+uKuCHObKGt0nlgbL+o8GnZuVD44//x3RKrn+KPC8CY=,tag:t1N8tvt7jVqvUsxvmaxLaw==,type:str]
type: ENC[AES256_GCM,data:EmRphMcY,iv:ElEZJig2QkI+MYG0Mu9ZI7m4iPgLqIMN2eN0RfA7BYg=,tag:Ns++hiqWoxvXNosTGOAuAA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:R8RHTpBEDTPM,iv:SBsfTI3l9LTfFuWl1u91SZ1sP3yUu1YOfefY4tLdeWM=,tag:9rK7PMWgsJTEJg8f++R3ug==,type:str]
    password: ENC[AES256_GCM,data:5Le1xu4IOnn9BycRe/zfZc+CzD9UhJEFLFl2L2g0tNqgt8+5RLswV6odsHIK5pPCcutyhUjMfOLYXoWE1MLnJw==,iv:2cRQJjA6qBbDVB0WR5U2KG6RG+83gh2hpoLJteZM5KY=,tag:GuYLJcWHIsIM8f3/EIdWkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZHpBK2dhNVhUa1VVKzVI
            MXEvVy83eFFUUjRCQm5UVU1PVkJOZzgvY1N3Cm5RWlQwZzFGVlRDWTNhRFgyMDNM
            V3RzRElIYWJzVzlnaG5RL29DMFRTS0kKLS0tIDdFOStwMHBhZUZJd2tqSmVXZ0Jw
            WTBxRkxMU3Q4WmpXYk9zd3g0MG56ODAKPBxzUnwnUDjxsKZW/A5iao/PlFnNCmN3
            XYFXOb2yQMBPyP0xaVc1R+8B3p9Efdw9R2utE+65i6XYYBvY9KU12g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRzRxZUpYT2tQMGY2UmhD
            eUZpZjFYekJpaklhTFg4Y0dlbWpYQ2tzNkNBCnhvZE1WcGxVUTFiRWFPV0o2bjly
            TUo3Wm1Fbm9EbnlzY25jQm1Ka1IxNEUKLS0tIEtRcnJHWXB2bm0wbzhTOXVNQ1Jo
            SUVNRXhONTRQK0Q3WnVLQ3J0WnM5NWcKDluZ+gycOt0e1ACe+ZAGjz+XeB+yl1Yb
            FRIu37E/4DdOMJXBIXJN+Nxq2OGKLmmrQV8AzfDx8fcVtEJ9Px9VnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZTQ4RVhCRGMyK3NOUmQ1
            U01BSTBVVTlDQTk3RFE3bG9XTUJLSWpDMWw4CkR1bU9pSWU5VFRNTVg4ZFp2WG1v
            ZS9TNU80N1cwQklRRVRieGZtWjZkY00KLS0tIHQ2bndURW9rd2o0SjZHM2U2cDhH
            cmd3OG8rdmErbkFUV04xNUpXYU94L3cK/Sp4eojohUaINmKrxoT8IjUorANkNICX
            N6LGe8leXhXPpRzxxVGVDYPvdVAgH3Dior7LjIIQOSbD2YxKPBMtRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-19T21:40:07Z"
    mac: ENC[AES256_GCM,data:NWC5dtyvA3djo6cftybr+JVjRIYPhSWNYrISs8eZxJWgjhY9afuDM2nw7yOZm1OAs2Dblyke276NjqBW0qKkOlHT7Lds7Axawl9js4HkdAfUwv9mojjpD67oOOvYMF6G5lCZvc667ghiqskDonHUv9hdLLMNHMNEC0/SreHW/QE=,iv:ziOwnA3LD+eEdx7B4uNiNmUC0BkRq97h+csEUsxASQs=,tag:VMLdj3hHBbiif6Hj70+rsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
