apiVersion: v1
kind: Secret
metadata:
  name: forgejo-gpg-secret
  namespace: forgejo
type: Opaque
stringData:
  privateKey: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----
    CHANGE_ME_GPG_PRIVATE_KEY
    -----END PGP PRIVATE KEY BLOCK-----
