apiVersion: ENC[AES256_GCM,data:v80=,iv:7oyFhlLvh7urTa1jHxGWBFMN0/pkRwAPxPKtl5qU8u0=,tag:CdktHi4fFk/nBdPypq1qPg==,type:str]
kind: ENC[AES256_GCM,data:fSH3YaED,iv:TYVEiUcCd8YB/3wcAPmNfAHTWvaXN98gXQ5EkNv7jiw=,tag:XQ8h94B4CfnoBT/zbARsyQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oPNKEwfST7VKyugKfng=,iv:6k4TJC7zhRWnvo9oerm5gPD2ofIrWXi8Fwlsa0eYfhA=,tag:GzWJraCMMP3jxzF/O7OsoQ==,type:str]
    namespace: ENC[AES256_GCM,data:K2FCfFirqA==,iv:b6iMOc954I3EJ6ALfB7IWidEUX0PX+9McIQr4R8FoP0=,tag:ctzsKbJ2OyshBJNhZ1f1KA==,type:str]
type: ENC[AES256_GCM,data:ZmzppYpu,iv:UWMimay7lVPu1covR8XhTeJbYU6wolP1Cgt8vtMv58U=,tag:V9YfmUPJyrZV0rDZaYqT7g==,type:str]
stringData:
    password: ENC[AES256_GCM,data:ij95xHgi8xCYIKOPay7fqiiSFOI=,iv:SyIJiqVj7Fa6qPtF6Ry2TmLwte5oRKLMKZe0eKflDDw=,tag:UVW5MBr5qi64T2Ld7T6ysw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwajAva29jM3Zab3Q5djdK
            SzBodFN5VFBacVpKaXZueVVZdVYzNm9iZW5NCkVSU1E1T1R5NlQveE5ld2p2NVVw
            WEk4bkpBamZoTmhiMm5rNU1GcWlwUW8KLS0tIFBsVXNWb2JTRHRNU0Y2b242MEZr
            eEJpYWpVNk5aWE9BTWU5MzQ0ZGQvYkEKQuRHa7LvuejlGMQz7JpJBxoXDUZy9RTR
            n35imnOu9FbWZjN90n55Owz03q1M9fVfLK6ld2lJW7mRpJFZl0cCIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aVpPWUpjVDJVYlZoQWNE
            K2IwNEJzREsraEhaWjBUcW9DR2pqclFhb3lrCnY4TFhvMUtLdTV0SWViWm54V0JR
            cU5udmhWN2xMQU9KZjNFRkZDY3E4OFUKLS0tIFIvK2R5MG5relVEYWpRVFBQQ2xV
            VzlHZHFlTUhRdFVpNVBIQVNwUDUzbWcKr/gi3b090wFr7X0YwNfqI2d2RxGNhISK
            GREMZ/Lf/517QvgQXkmU9NpWEpKFGOz2npfvRZM4fc8YqmQtlirOiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWWNBUjBDWkxJb3lEVGRV
            YThndFJTS1gvdTU3U2JEWHU0RGVnR0pMK3pnCmJtdXQzVmZMalRJNzRJbVUrR3Z5
            UXBaRjFiS3JBcU5TYkZ0Z0tzLzlJQTQKLS0tIFdNQnFWWWZGWHVhNmhRbmpzVXdk
            L3lrOXAxSVFqbTh5cnFmWDgxZ29yaUUKrICgGF6ZC4OMuHS9QHPwM4fd/XiIfGad
            nG813e/UsBfW0U8uHRUwUPJuDak0bKR8HWSCKeOwOV72HjL98WxTvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-19T22:40:57Z"
    mac: ENC[AES256_GCM,data:KmFY9LmF9cxLaw71e+TGQmd24I9XupQUTD1m5OPKT9zQ8J70Q95yXiQ0DGWwqGTP43fi/wKu8xDagTqorEyIWLq1r3Z8Msh5AtYSaLL7R0k6rGrirightQim8wXIiIV5RGBsvhNf+zuYKE0riHBYbwH+B0F9Tl3DSbieScekx5M=,iv:kwxePXlO+fYyDuZuhWJLt2gvR52oqsBdrhs4+9uf/2s=,tag:xm+wxwosl6p6oGu5CaHNGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
