apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone-garage
  anotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi-rclone
reclaimPolicy: Retain
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.csi-rclone/storage-path}"
