apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone-garage
provisioner: csi-rclone
# parameters:
#   pathPattern: "${.PVC.namespace}/${.PVC.annotations.csi-rclone/storage-path}"
