- name: Configure Woodpecker agent
  ansible.builtin.template:
    src: woodpecker-agent.env.j2
    dest: /etc/woodpecker/woodpecker-agent.env
    owner: woodpecker
    group: woodpecker
    mode: '0600'
  notify: Restart Woodpecker Agent

- name: Upload SystemD Service file
  ansible.builtin.copy:
    src: files/woodpecker-agent.service
    dest: /etc/systemd/system/woodpecker-agent.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Woodpecker Agent

- name: Ensure Woodpecker-agent service is enabled and started
  ansible.builtin.systemd:
    name: woodpecker-agent
    state: started
    enabled: true
    daemon_reload: true
