---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fluxer
  namespace: fluxer
spec:
  entryPoints:
    - websecure
  tls:
    secretName: fluxer-sakul-flee-de-tls
  routes:
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/api`)
      priority: 30
      kind: Rule
      middlewares:
        - name: strip-api
          namespace: fluxer
      services:
        - name: api
          port: 8080
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/gateway`)
      priority: 30
      kind: Rule
      middlewares:
        - name: strip-gateway
          namespace: fluxer
      services:
        - name: gateway
          port: 8080
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/media`)
      priority: 30
      kind: Rule
      middlewares:
        - name: strip-media
          namespace: fluxer
      services:
        - name: media-proxy
          port: 8080
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/livekit`)
      priority: 30
      kind: Rule
      middlewares:
        - name: strip-livekit
          namespace: fluxer
      services:
        - name: livekit
          port: 7880
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/admin`)
      priority: 30
      kind: Rule
      middlewares:
        - name: strip-admin
          namespace: fluxer
      services:
        - name: admin
          port: 8080
    - match: Host(`fluxer.sakul-flee.de`) && (PathPrefix(`/web`) || PathPrefix(`/emoji`) || PathPrefix(`/libs`) || PathPrefix(`/avatars`) || PathPrefix(`/badges`) || PathPrefix(`/desktop`) || PathPrefix(`/embeds`))
      priority: 40
      kind: Rule
      services:
        - name: static-proxy
          port: 8080
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/.well-known/fluxer`)
      priority: 35
      kind: Rule
      services:
        - name: api
          port: 8080
    - match: Host(`fluxer.sakul-flee.de`) && PathPrefix(`/`)
      priority: 10
      kind: Rule
      services:
        - name: app-proxy
          port: 8080
