---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: fluxer-livekit-udp
  namespace: fluxer
spec:
  entryPoints:
    - livekit-udp
  routes:
    - services:
        - name: livekit
          port: 7882
