apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: minecraft
spec:
  interval: 1h0m0s
  url: https://itzg.github.io/minecraft-server-charts/
