apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: minecraft
      version: '5.0.x'
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      interval: 5m
  releaseName: minecraft
  targetNamespace: minecraft
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    minecraftServer:
      eula: "TRUE"
      version: LATEST
      type: PAPER
      difficulty: normal
      whitelist: SakulFlee,jendrik12799,Lennart116002,Fisch246,DarkRune2214,_MinaChan_,Froggy189,zero_MB
      ops: SakulFlee,jendrik12799
      motd: "Conduit @ K0s by SakulFlee"
      pluginUrls:
      - https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.5.1/PAPER/ViaVersion-5.5.1.jar
      - https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.5.1/PAPER/ViaBackwards-5.5.1.jar
      - https://download.geysermc.org/v2/projects/geyser/versions/2.9.1/builds/999/downloads/spigot
      - https://download.geysermc.org/v2/projects/floodgate/versions/2.2.5/builds/121/downloads/spigot
      - https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.4.40/PAPER/Chunky-Bukkit-1.4.40.jar
      - https://hangarcdn.papermc.io/plugins/KingTheGuy/Portalis/versions/1.0/PAPER/portalis-1.0.jar
      # - https://hangarcdn.papermc.io/plugins/EngineHub/WorldEdit/versions/7.3.17/PAPER/worldedit-bukkit-7.3.17.jar
      - https://hangarcdn.papermc.io/plugins/kennytv/WorldEditSUI/versions/1.7.4/PAPER/WorldEditSUI-1.7.4.jar
      - https://ci.athion.net/job/FastAsyncWorldEdit/lastStableBuild/artifact/artifacts/FastAsyncWorldEdit-Paper-2.14.2-SNAPSHOT-1224.jar
      downloadWorldUrl: https://nextcloud.sakul-flee.de/s/qmcyfTQ467kmNcX

    persistence:
      storageClass: longhorn-replicated
      dataDir:
        enabled: true
        Size: 8Gi
