apiVersion: v1
kind: Secret
metadata:
    name: hytale-credentials
    namespace: hytale
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:d+FckcL2GcxfTR6UCZgJiLq5UjQkaioAVVvS3DoBVjDotc7ldlZF1f5UZvXhEC1SQ89sT7BYb/MMNkOhluGI2x66L9XPr0G/tCGnF/hdQ6wff/ipGYSx0qjJJuXdEV79QJWVWMnNpEu8Js6j1jDsrc9Lev2Dt81EWeurILBUM4TDg4RfYfP8ZXJaQgUyUCmPhtVpdNGXikkrtlXuwl7B00KK+zPjX2FVUnABDXG9WpMxlgdj4x5OFbpnYs4jzsrHzLZx6IBKMaMCvJSkn5LdvSHQpoI/Eq5QCfIcslnLRzuHy0BgP6R1JcejuZ19wUp4g1leI/w2d55thi/rzShEPlhu4TSuyXvKL8cxd6ztwrGBQK1zCqeghWJL/DTJy1Qwgiqxitl5bQiCbbXeqLLLdIWZ6tGWq88jBy/U0mShaGqMMmqhakyYR1HsMbOoYrkCN4f7AgkKeHRZ8Xq4R7CyFdeq8u/d1JQW37VekCrbRxw5sW5hMq60Du97mF10P3/ZX+F/I3p+ORTUU3IX4tqEBljeCAB+Zq9k4cG3hinFnWiRuUtpLkk1zu+wVgCMrqOGQeMIZUV4gBUXmNf2Bqktt/Bs+5bIOCIxvzxMXwQFDLBDQI1aRZgm/p55K1x/rqg83z0KDdEadJ9gDtyPRv6QoewnCcYWCojesMmB8X+jZfjrtnZPd3i7OE9CnxiH7K5o8DWuw2m7m8FLwWLpcD9z5X/A1X8hggB5X3ZJOONn6i0vDO/BgmI7kbMNbvmDCLJF/OuQPOqxjxZAY8TOwrmfJSNGEoZomZIEuXJjkcmu6KtT8se1ZNAc+OXLauDYBT1vXSlNDgXwfoqOTwM+7fp4/pXnrp2HzEWJepb0JtEoUn0wUxn9SvCdAZrCevrHx8hFxjInNKv2X7a4tWPUoZEY8YMS18LB6iZsoWfapDLTgBaIo2xTCTwe0r8rUZv48wbqPCwLq3deB7cBw8iCwkmA+7CjD9kbULys6jPhSODytzTSrVVQnce82BXV5y0ZMs6OMNswJbFD+wfyp6wbHyW9gir/IQ6Al2mkH19IPPI9F0HJ1yHMFZfFCOWWeNAc/7L763HZuNk/fk4fA9j1qbsh9tB+IXUY4p7PahlPdN86mXpSEvxFEi8Ly9NDV3HpgdXT2ulDv9UqIpEjk5s7WTPyfkja1ckd9SvU+mGVCGMVV78CeMkmW2x7prPqQzcsiTdVUqsQ8yTvKiuUTgXlNVanjSz9PaOJ9MPE0Uy7CcrYWmKlZzS8yplhiRHF+MFt+LL3eb/92AaCbyY5ThJMMw5ONBvWfCzvnutODZ4qyULODrWqK8Jfbm/+DW5dFRlRNaDckOpEYLEiGY9izlIlBHhd75bttNuAhGeYXX1rkaOG8G2iXVoBBQmhEy/aJ+LTzhAMJ/aeaQYhpbdiKl6C41Yt+CmaCl6T/srWPcMVyT3UinOd/Aosa4V1BWABJexUEPv23L1020+eZfL7CUWbDsXnRm2hPkdmavl0g/AN/qWwl1Sh7fKpTUh1wdK1DfNBKfyUVC6m5QejuUToVEm6tNKzb6e7XzVVbA4w3WvYdkXQYsJzRnj6pF8Tze3nxRwJctUV67tF1V80jYQ+Gk7xlI1egkVgn/awLHK/v+2jRzB7+NAMaOTBK9xiTjJ3BkuMXWCMUkKUK+vfK6cbBJd1gdvc+dhTe+EFnNFAjAQnD7D59ygIVWFuyVXRc6jfMNhBxQRMW5GiFpykp2wtMIOLxk944Bb9LqnArqWw/FlnOR69TD8=,iv:kxgE9YUhdfwKoxFVV4OS4BRY2tjbeAkjBCpKx5+ONX0=,tag:VhabQ4Ym3yNS59RfoliZ6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjZEcnNMdHNEVnZDN0p2
            QThVRWcyRlY3OFp6azhPWnlxTVdVUUlEcUUwCkNPaDU4K2RQWXlONDZSQXdLbUo1
            UWlkclJSVWVVb1JnSjQrbUh1cmJEUXcKLS0tIHZTVWJOVEpKbWRhTG0yckp4NDNE
            Mk1VMHBySEZlRE5YeHZVOThGN280akEK4tF9s9yPubfkiEAPnDvPKNsM5HVALJKQ
            TNhqNPUk9/m2Ysl60AYwQXmAOaNt0sKYhFTSE7WAvhEkKTO9gtkAnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcHVHRUlXZU1ZL0VaSmJ4
            ZWREdzBrTlFzOURDSWFtTEFPUFJDbEFVcWxRCi9lN0Z4NlJxYmtwTGNJeVhrUkJm
            QUFuZ0sweEh4NG1uRW1DK0t2QzNtUlkKLS0tIE9vaDR2bSttQzJ0ajBadGNwb0dv
            NWR4cExaQTdyZkVQRDFySHdQNkpCY2MK4uuU3/Siv8zqCO0a+O5HoVepGf7MpOi6
            c612t4WzCQW6+j4Y8J3JN3D71KODHbOx7xjmNsZq9ZkHDxQ1jXkbUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQTNzMC8wNmZQdkUzSDZX
            UnJNZld4MXMyczBRa3RxUVRYWVpEamE3WWhFCjM2M1k2Q3F3S0JwOElMUTNFSXU3
            OG5KSkEyZlNmWDBGSFJGaHVLYWFxeEUKLS0tIGY4ekNrZW5qTm4zTk8wNWh6WmlM
            MUtSTHp2Nk1maGxTTTA0bjNkRVkzWDQKLZpH3FCUwLhicAeqFEuPmufmKuUbZuBI
            y+jTD8QtbsUu7CBCSpkmFxVu5ri4Vq/N99kiVghUYP5d4vF/Sc9Yqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-26T23:03:00Z"
    mac: ENC[AES256_GCM,data:k0fs4fTMv7u2xvd3LTl70nOYY9PCWIaO+1afqmd77iG23QeHBBpLqrorublIB6NMA3n+tGkZdEbTNU/dNWiUoWzskhJBCLD5xYIY3bdSpZeFOaDOlVjPGWSBFHrlKzIkT+ey2bAeWfBAPIqGze21kcDgCx/3nsbqyD0D2uoUaDE=,iv:9xXWktysavnQVa6jdosyWEzeFc6JzbREj5hw4HIvpZc=,tag:7Z60xECBD8MOsyqN1Ybsqg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
