apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:K/4g0OiE7aKBhS7/OEQHkkBfhUPnyVZMDy4Z8pPCCpLB92+gXULX6g==,iv:aRWpqN8GfpQ3aAZmYbnSifLNroyhajh36S8iunLcQzs=,tag:3xrLTCTdFhJyN1pv08aJgg==,type:str]
    uuid: ENC[AES256_GCM,data:B96hfNgA+VFvybAzRpqQ2L0EqJdqjs58kLZixpmnyhAxwd1k,iv:iIfhYfjVsu6gtTG/apAkitC2HyR3Gd9s4mi1qcIQSl0=,tag:1FtCBmIQuYP8taCgj7XuiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscE5kYTgxd0RLM0UxeTJR
            QWdwdU9mVm1iMEdVVWpVQlVCSXI4OGFTNG5RCmFrTTNwMGYwQmZUdkE0TUY4MHU1
            K01jdzFXUDJuQ1BVckpydXpIK2xtZWMKLS0tIHQ2eDlSQ3VBUCtnSzl4dWlvZmVo
            bWpERU1qSUR0L09ONG1rQVVSam13bVEKxUfIJw4sPajUdWYLooY6Cpv+LEqABluI
            KxkkvYU/VuzZ0RVyS3eBMASukkTOhNiciHOcievYuhKVEVKzVc6P0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb3JmeDlyUUpWYzAyNlNu
            TDdlOE9kNmx6VEsva3lxZk1SeDUyYTNGUkhrCjQ1c1V1ZVg1TlV0V2xwRWlqMkc1
            T041dTVPU2VRa3pSUzlNMW5KWnk0YXMKLS0tIHllWjJlOUlhY1JCakJnZ2JIZ2NN
            aGcrd0xaMXJocE50UldqaUJwTEExUXcKhbBqvHynqMjgaLMtOxVVt/nNJIks08ZK
            lWaDXxcCeW3bsHtItW/AiWH2ekvSDkJCglCqjP7hqv92Mo/TmajQKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdEZGU0hqdHFvYk9nUFhu
            QnpGOVprSTNUVVpMVDdSSkQ0WFJIdFg0TmtjCnAzZ1o1ZEtVb2ZKeHg5ZEMxdDFH
            RWZLRmZONTdNd1dyY05WTVd5eGh6ek0KLS0tIERaMFZmZlRzYTRmRFhVZktRaU4w
            ZWVFYzNKQm44K2lYcWJ2bWVYMERvdVkKrw+/339p4vCba5qhcNyqWHPnY44G6cJt
            z3as0AY61PfIaJvyMxsBH64LDxFUO4ySu80aqALFL4wMO6Vjg3NfOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-26T22:07:58Z"
    mac: ENC[AES256_GCM,data:1R3ZWnBTZpAuHvttHbc5PwRHZOFeJP3CLE9FsqplbgeyWUgdjZAMs043HBOOSjE3MFBFVW8GDYGIWYIAGSkmqsO+OGuj/6kg0zx6VrIFckbub9KZtrF3+XJ3L9Fy2jAfdrYir212fTmPso78aftrEvEUXlJ1FlicB94BdTZwVrQ=,iv:WKRDV8I1vpWwzexRLSw8isXUrRrjIj1alHnbASwtAKg=,tag:Z0Bug7FfdOjrfxXLLMoVwA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
