apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:fw9Ql7WEAKs34isufvB+U+SjgeUKsryWvnEoEvAEcOce77eCWoXNKg==,iv:nzRLHZBLOPtKGG1lhusQqryyU8HKl6oYJ+EDqECE1Fo=,tag:kaStZTsmyqLL/3L2NiiHKQ==,type:str]
    uuid: ENC[AES256_GCM,data:tPZKJW9Dsvtl7FIXeUEaMXZ4xbfPqUWGc3ZdpCZvq8hVjaFM,iv:eZxEPG52cyvrC79EZomIzlOaOObuKhE1ODV0sPZnzns=,tag:nQGwcjFG3GTagtzVy3/IAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM0hVRmlvMmNlbDh1WFdk
            eHI0VlV5ZTgwYmZMYkpyM2sxZUtEeDdpYW5rCjBqcklqRG42ZWtMaE5wVXVTc1lV
            bitWRytSSVp6UWJtQmgvdW83SEljVUUKLS0tIG9STjhMNU1lY1A2ekRPTEhEZ1ky
            MjE1VFc2T3hzWWdra2pFSjMwN3YxNmMKSNXIc6v1tfj2FYDworjuwu+6/64T9AY0
            wgdDkzYi8wRdZCLOmFzhdrn0Do5ktyhmUFznc+Dv16spQYwKgLGLUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1564t00zp3r69x0n7fxwadcgxv0n5v2rkqz77ry52t05q99d6wetqqmr6l6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVakFtUkJwekhpQ0dQZHF0
            Umk2Q1lCaCtwRE84OVNGWFRtT05WRjR6dzNvCllYTXRQeHIvSGJDWnBlWllqdE1W
            M3NrZ1hNOW5OQkRseW80a0RVSDBjaGcKLS0tIFllNjB1eWwvOVFnd2VaMm1INys0
            dmxMSGJnUEgvWXZXQ0pnejExRFJvTkEKZy7hg8hYbwkCuz6LtSpfiwBafjsv9ZCM
            W3KGquqsQjopF+c/KLxAEEzpXRVsSVs78HurfrzN7CJnpMbpT4hGYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16n3ufazps5tru37l4wny0sh4f7em63j22yuhlahhfhxu5kz2ufdsmer7mw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WWxteDFQcytwTDNHR0l3
            MzBiblRwTkV5b3NrdGhHRFRrbGNCaXRPZWdFCnQ0SlJnNlBGY3I5eGZ3THdYUGJs
            Y0pBMkppUnpXZnJobjV5c0FTN0grSHcKLS0tIDk1Q0tRZUZ1S1BEM29Rc3VCdFBq
            Q0ZvZWpFSkxabVYxSlNlNTcyL0VXL00K5BmCVPGOLZEGHrKQjhCNE/2gmx7iCoDH
            n0GXA+m4wp+cSQG4BY8x/hZHE0aA77luBCck4+MmJZhSmf9ntuRxhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1suydyah5q07jdn7xrpt853pzt9ua3ygd7yuu4pys8g0caq2v6dhsmvwcwg
    lastmodified: "2026-08-28T17:13:16Z"
    mac: ENC[AES256_GCM,data:TfQn1j/RpLzdAt5tTtdcV8gA6uCmLoQC8hSCB8Bl6ogyQYh7s5Qo/+RARwHZNeaDaOPbRfmGVf7KcQP12iUGHejbJPXq4cOOTnwwtIdBIvcT6imLTg1tzzpluPRj6rTLqXo2aCUTLdcFJ2AcU6WJk6NqG2kAhxzc9VYzLzFWGMs=,iv:UvRBJnU15KtJ9CQeF5RfFfIrd5nYw4mraF9oAqcyjTQ=,tag:cqSqAuXCjgX0G+E6hDmQwA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
