apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  interval: 5m0s
  url: oci://ghcr.io/woodpecker-ci/helm/woodpecker
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: ^3.5.0
