apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qui-config
  namespace: media
spec:
  storageClassName: local-path-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
